// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace QuickER.Tests.GeneratedRemoteServiceFixture;

/// <summary>
/// Endpoint mapping that exposes the generated remote surface (I{Entity}RemoteRepository) as an ASP.NET Core Minimal API.
/// </summary>
/// <remarks>
/// <para>
/// Place this file in a project that has the ASP.NET Core FrameworkReference (<c>Microsoft.AspNetCore.App</c>);
/// no extra configuration is needed when the SDK is <c>Microsoft.NET.Sdk.Web</c>. Register the concrete repositories
/// (<c>AddGeneratedSqlServerRepositories</c> / <c>AddGeneratedEfCoreRepositories</c>, etc.) in the server-side DI container.
/// </para>
/// <para>
/// Each operation is exposed as <c>POST {prefix}/{entity}/{operation}</c> (JSON body). Apply cross-cutting concerns
/// such as authorization to the returned <see cref="RouteGroupBuilder"/>
/// (for example <c>app.MapGeneratedRemoteEndpoints().RequireAuthorization()</c>).
/// Exceptions are converted to structured JSON (RemoteError): <see cref="SaveConflictException"/> maps to 409 and
/// an unhandled failure to 500, and the client (Http{Entity}RemoteRepository) restores the original exception type.
/// </para>
/// <para>
/// A request that cannot be interpreted at all - a malformed or empty JSON body, a non-JSON content type, a type
/// mismatch, a value that fails value-object validation, a body that omits a required field such as the entity, an
/// undefined <see cref="ConcurrencyMode"/> value, or a
/// missing/malformed <c>?id=</c> key - is a fault in what the client sent, so it is answered with HTTP 400
/// (RemoteError of type "BadRequest") instead of 500. A request
/// rejected by the server infrastructure (<see cref="BadHttpRequestException"/>, for example when the request body
/// size limit is exceeded) keeps the status code it carries, such as 413.
/// </para>
/// <para>
/// The class is <c>partial</c> so additional endpoints or helpers can live alongside the generated ones,
/// and the <c>OnServerError</c> partial method can be implemented to add custom handling (notifications,
/// metrics, extra logging) whenever an endpoint responds with HTTP 500.
/// </para>
/// </remarks>
public static partial class GeneratedRemoteEndpoints
{
    /// <summary>Maps every remote-surface endpoint under the given prefix (defaults to <see cref="RemotePaths.DefaultPrefix"/>).</summary>
    /// <remarks>
    /// The group also carries a liveness endpoint, <c>GET {prefix}/health</c>, which answers 200 with an empty body
    /// once the server is listening. It is a member of the group like any other endpoint, so authorization applied to
    /// the group covers it as well; a probe that has to stay anonymous can be given its own route mapped outside the
    /// group instead.
    /// </remarks>
    /// <param name="endpoints">The mapping target (for example a <c>WebApplication</c>).</param>
    /// <param name="prefix">The route prefix for the endpoint group.</param>
    /// <returns>The endpoint group, to which authorization and similar concerns can be applied.</returns>
    public static RouteGroupBuilder MapGeneratedRemoteEndpoints(
        this IEndpointRouteBuilder endpoints,
        string prefix = RemotePaths.DefaultPrefix
    )
    {
        ArgumentNullException.ThrowIfNull(endpoints);

        var group = endpoints.MapGroup(prefix);

        // Liveness: the client's PingAsync polls this while waiting for the server to come up, so it must not touch
        // the database - a 200 states that the process is listening and the endpoints are mapped, nothing more
        group.MapGet(RemotePaths.HealthRoute, () => Results.Ok());
        MapCustomerEndpoints(group);
        MapOrderEndpoints(group);

        return group;
    }

    /// <summary>Runs a handler, writes the result as JSON, and maps exceptions to HTTP responses (400/409/500, or the status carried by a rejected request such as 413).</summary>
    private static async Task ExecuteAsync(HttpContext context, Func<Task<object?>> handler)
    {
        try
        {
            var result = await handler().ConfigureAwait(false);
            await context.Response.WriteAsJsonAsync(
                result,
                RemoteJson.Options,
                context.RequestAborted
            ).ConfigureAwait(false);
        }
        catch (RemoteBadRequestException ex)
        {
            // The request itself could not be interpreted: a client-side fault, so it is classified as 400 without server-side logging or the hook.
            await WriteErrorAsync(
                context,
                StatusCodes.Status400BadRequest,
                "BadRequest",
                ex.Message
            ).ConfigureAwait(false);
        }
        catch (BadHttpRequestException ex)
        {
            // Rejected by the server infrastructure (request body size limit, malformed request): pass through the status code it carries (413 and similar).
            await WriteErrorAsync(context, ex.StatusCode, "BadRequest", ex.Message).ConfigureAwait(false);
        }
        catch (SaveConflictException ex)
        {
            // Optimistic-concurrency conflicts are restored on the client as SaveConflictException (the same catch works as with a direct call).
            await WriteErrorAsync(
                context,
                StatusCodes.Status409Conflict,
                "SaveConflict",
                ex.Message,
                ex
            ).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (context.RequestAborted.IsCancellationRequested)
        {
            // Client disconnected or cancelled: there is no longer a response target, so do nothing.
        }
        catch (Exception ex)
        {
            LogServerError(context, ex);
            RaiseServerError(context, ex);
            await WriteErrorAsync(
                context,
                StatusCodes.Status500InternalServerError,
                "Error",
                ex.Message
            ).ConfigureAwait(false);
        }
    }

    /// <summary>Writes a <see cref="RemoteError"/> body with the given status code (the shared path for every classified failure response).</summary>
    /// <remarks>
    /// <paramref name="conflict"/> is supplied only for the 409 path: its details travel with the body so that the client
    /// can rebuild the same <see cref="SaveConflictException"/> a direct call would have thrown. Every other kind leaves
    /// those fields null.
    /// </remarks>
    private static async Task WriteErrorAsync(
        HttpContext context,
        int statusCode,
        string type,
        string message,
        SaveConflictException? conflict = null
    )
    {
        context.Response.StatusCode = statusCode;
        await context.Response.WriteAsJsonAsync(
            new RemoteError
            {
                Type = type,
                Message = message,
                Reason = conflict?.Reason.ToString(),
                EntityType = conflict?.EntityTypeName,
                Key = conflict?.Key,
            },
            RemoteJson.Options,
            context.RequestAborted
        ).ConfigureAwait(false);
    }

    /// <summary>Restores the request body from JSON (a body that cannot be interpreted is reported to the client as HTTP 400).</summary>
    /// <remarks>
    /// Malformed JSON, an empty body, a non-JSON content type, a type mismatch, or a value that fails value-object
    /// validation are all faults in the payload the client sent, so they are wrapped in
    /// <see cref="RemoteBadRequestException"/> and answered with 400. Cancellation and
    /// <see cref="BadHttpRequestException"/> (which carries its own status code, for example 413 when the request body
    /// size limit is exceeded) are left untouched so that the surrounding handler can classify them.
    /// </remarks>
    private static async Task<TRequest> ReadRequestAsync<TRequest>(HttpContext context)
    {
        TRequest? request;

        try
        {
            request = await context.Request.ReadFromJsonAsync<TRequest>(
                RemoteJson.Options,
                context.RequestAborted
            ).ConfigureAwait(false);
        }
        catch (Exception ex)
            when (ex is not (OperationCanceledException or BadHttpRequestException))
        {
            throw new RemoteBadRequestException(ex.Message, ex);
        }

        return request ?? throw new RemoteBadRequestException("The request body is empty.");
    }

    /// <summary>Validates the concurrency policy carried by a request body (an undefined value is reported to the client as HTTP 400).</summary>
    /// <remarks>
    /// JSON deserialization accepts any numeric value for an enum, so a hand-written client can put a value that names no
    /// policy into the body. Passing it on would silently fall through to the unguarded branch, disabling the version check,
    /// therefore it is rejected here as a fault in the payload the client sent.
    /// </remarks>
    private static ConcurrencyMode ValidatedMode(ConcurrencyMode mode) =>
        Enum.IsDefined(mode)
            ? mode
            : throw new RemoteBadRequestException(
                "The concurrency mode must be Optimistic or ForceOverwrite."
            );

    /// <summary>Returns a required request field unchanged (a field the body omitted is reported to the client as HTTP 400).</summary>
    /// <remarks>
    /// The request bodies are positional records, so a body that leaves out a member - <c>{}</c>, for example - deserializes
    /// with that member at its default rather than failing. Passing it on would surface deep inside the repository as a
    /// null-argument failure and be reported as an unhandled server-side error, even though nothing on the server went
    /// wrong, therefore it is rejected here as a fault in the payload the client sent. A key whose type is a value type has
    /// no omitted form and always passes through.
    /// </remarks>
    private static T Required<T>(T? value, string name) =>
        value is null
            ? throw new RemoteBadRequestException($"The '{name}' field is required.")
            : value;

    /// <summary>
    /// Marks a failure to interpret the request itself (the JSON body, a required field it omitted, or the <c>?id=</c>
    /// key). The request never reached
    /// the repository, so it is a fault in what the client sent rather than a server-side error: it is answered with
    /// HTTP 400 and a <see cref="RemoteError"/> of type "BadRequest", and neither the server-side logging nor the
    /// <c>OnServerError</c> hook - both reserved for HTTP 500 - is invoked.
    /// </summary>
    private sealed class RemoteBadRequestException : Exception
    {
        /// <summary>Initializes a new instance with the message reported to the client.</summary>
        public RemoteBadRequestException(string message)
            : base(message) { }

        /// <summary>Initializes a new instance with the message reported to the client and the underlying failure.</summary>
        public RemoteBadRequestException(string message, Exception innerException)
            : base(message, innerException) { }
    }

    /// <summary>Resolves the remote-surface repository from DI.</summary>
    private static TRepository Repository<TRepository>(HttpContext context)
        where TRepository : notnull => context.RequestServices.GetRequiredService<TRepository>();

    /// <summary>Logs an unhandled exception that is about to be reported to the client as a 500 response.</summary>
    /// <remarks>
    /// The response body carries only the exception message (so that the client can restore the exception type),
    /// therefore the full exception - including the stack trace - is recorded here on the server side.
    /// Logging is optional: when the host has no <c>ILoggerFactory</c> registered this is a no-op and the behavior
    /// is unchanged. Classified responses (400 and 409) do not go through here: they are the expected outcome of the
    /// request rather than an unhandled server-side failure.
    /// </remarks>
    private static void LogServerError(HttpContext context, Exception ex)
    {
        var loggerFactory = context.RequestServices.GetService<ILoggerFactory>();

        if (loggerFactory is null)
        {
            return;
        }

        var logger = loggerFactory.CreateLogger("QuickER.RemoteServer");
        logger.LogError(
            ex,
            "An unhandled exception occurred while handling {Method} {Path}.",
            context.Request.Method,
            context.Request.Path
        );
    }

    /// <summary>Invokes the <c>OnServerError</c> extension hook while isolating any failure inside it.</summary>
    /// <remarks>
    /// The hook is user code and runs before the 500 body (<see cref="RemoteError"/>) has been written, so an exception
    /// escaping from it would discard the original error response and leave the client with a generic failure whose
    /// cause is lost. The hook must never replace the original failure, therefore an exception thrown by it is
    /// reported through the same server-side logging and then swallowed.
    /// </remarks>
    private static void RaiseServerError(HttpContext context, Exception ex)
    {
        try
        {
            OnServerError(context, ex);
        }
        catch (Exception hookError)
        {
            LogServerError(context, hookError);
        }
    }

    /// <summary>Extension hook invoked - after the built-in logging - whenever an endpoint responds with HTTP 500.</summary>
    /// <remarks>
    /// Implement this method in another part of this partial class to add custom handling for server-side
    /// failures (notifications, metrics, extra logging). It is reserved for HTTP 500 and is therefore not invoked for
    /// classified responses (400 and 409). When no implementation is provided the compiler removes
    /// the call itself, so nothing but an empty guard remains. An exception thrown by the hook is isolated (logged
    /// on the server side and then swallowed) and never replaces the original 500 response. The 500 response body
    /// itself is not customizable here; wrap the group returned by <c>MapGeneratedRemoteEndpoints</c> in middleware
    /// to translate responses instead.
    /// </remarks>
    /// <param name="context">The HTTP context of the failed request.</param>
    /// <param name="ex">The unhandled exception that was reported to the client.</param>
    static partial void OnServerError(HttpContext context, Exception ex);

    /// <summary>Maps the common CRUD operations (GetById / GetAll / Insert / Update / Delete / Save / SaveMany).</summary>
    private static void MapCrud<TEntity, TKey, TRepository>(
        RouteGroupBuilder group,
        string entityRoute
    )
        where TEntity : EntityBase, new()
        where TRepository : notnull, IRemoteRepository<TEntity, TKey>
    {
        group.MapPost(
            $"{entityRoute}/GetById",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteIdRequest<TKey>>(context).ConfigureAwait(false);
                        return (object?)
                            await Repository<TRepository>(context)
                                .GetByIdAsync(
                                    Required(request.Id, "Id"),
                                    context.RequestAborted
                                ).ConfigureAwait(false);
                    }
                )
        );
        group.MapPost(
            $"{entityRoute}/GetAll",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                        (object?)
                            await Repository<TRepository>(context)
                                .GetAllAsync(context.RequestAborted).ConfigureAwait(false)
                )
        );
        group.MapPost(
            $"{entityRoute}/Insert",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteEntityRequest<TEntity>>(context).ConfigureAwait(false);
                        var entity = Required(request.Entity, "Entity");
                        await Repository<TRepository>(context)
                            .InsertAsync(entity, context.RequestAborted).ConfigureAwait(false);
                        // The insert leaves the newly assigned version on the entity, which the client writes back
                        return (object?)
                            new RemoteInsertResult(RemoteEntityGraph.ReadRowVersion(entity));
                    }
                )
        );
        group.MapPost(
            $"{entityRoute}/Update",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteUpdateRequest<TEntity>>(context).ConfigureAwait(false);
                        var entity = Required(request.Entity, "Entity");
                        var updated = await Repository<TRepository>(context)
                            .UpdateAsync(
                                entity,
                                ValidatedMode(request.Mode),
                                context.RequestAborted
                            ).ConfigureAwait(false);
                        // A successful update leaves the newly assigned version on the entity, which the client writes back
                        return (object?)
                            new RemoteUpdateResult(
                                updated,
                                updated ? RemoteEntityGraph.ReadRowVersion(entity) : null
                            );
                    }
                )
        );
        group.MapPost(
            $"{entityRoute}/Delete",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteIdRequest<TKey>>(context).ConfigureAwait(false);
                        return (object?)
                            await Repository<TRepository>(context)
                                .DeleteAsync(
                                    Required(request.Id, "Id"),
                                    context.RequestAborted
                                ).ConfigureAwait(false);
                    }
                )
        );
        group.MapPost(
            $"{entityRoute}/Save",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteSaveRequest<TEntity>>(context).ConfigureAwait(false);
                        var entity = Required(request.Entity, "Entity");
                        var affected = await Repository<TRepository>(context)
                            .SaveAsync(
                                entity,
                                request.CascadeSave,
                                request.CascadeDelete,
                                request.InsertWhenUpdateMissing,
                                ValidatedMode(request.Mode),
                                context.RequestAborted
                            ).ConfigureAwait(false);
                        return (object?)
                            new RemoteSaveResult(
                                affected,
                                CollectRowVersions([entity], request.CascadeSave),
                                CollectSkipped([entity], request.CascadeSave)
                            );
                    }
                )
        );
        group.MapPost(
            $"{entityRoute}/SaveMany",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<RemoteSaveManyRequest<TEntity>>(
                            context
                        ).ConfigureAwait(false);
                        var entities = Required(request.Entities, "Entities");
                        var affected = await Repository<TRepository>(context)
                            .SaveAsync(
                                entities,
                                request.CascadeSave,
                                request.CascadeDelete,
                                request.InsertWhenUpdateMissing,
                                ValidatedMode(request.Mode),
                                context.RequestAborted
                            ).ConfigureAwait(false);
                        return (object?)
                            new RemoteSaveResult(
                                affected,
                                CollectRowVersions(entities, request.CascadeSave),
                                CollectSkipped(entities, request.CascadeSave)
                            );
                    }
                )
        );
    }

    /// <summary>
    /// Collects the row versions a completed save assigned across the saved graphs, so that the client can write them back
    /// onto its own entities.
    /// </summary>
    /// <remarks>
    /// The traversal is the server-side counterpart of the client's <c>AcceptChanges</c>: both walk the same
    /// [NavigationReference(Cascade=true)] child navigations (<c>RemoteEntityGraph.CascadeNavigations</c>) and identify an
    /// entity the same way, so every collected entry lands on the matching local entity. Backends that assign no versions -
    /// a dialect without a rowversion type, or a diagram whose tables carry no such column - simply yield an empty list.
    /// </remarks>
    private static List<RemoteRowVersionEntry> CollectRowVersions<TEntity>(
        IEnumerable<TEntity> entities,
        bool cascade
    )
        where TEntity : EntityBase
    {
        var rowVersions = new List<RemoteRowVersionEntry>();

        foreach (var entity in entities)
        {
            // A null element is filtered out by the save itself, so it is passed over here as well
            if (entity is not null)
            {
                RemoteEntityGraph.CollectRowVersions(entity, cascade, rowVersions);
            }
        }

        return rowVersions;
    }

    /// <summary>
    /// Collects the rows a save hook's Before skipped, so that the client can leave their RowState untouched instead of
    /// finalizing them to Unchanged.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A completed save has already finalized every row it operated on (<c>EntityGraphSaver.AcceptChanges</c> leaves the
    /// skipped ones alone), so a row that still carries changes is exactly a row the hook skipped - no separate bookkeeping
    /// has to travel from the repository to here. Deleted rows are left out because the client leaves a removed entity
    /// untouched in either case.
    /// </para>
    /// <para>
    /// The traversal and the identity of a row are shared with the row version table, so the same constraint applies: when a
    /// graph contains the same (type, key) twice, the entries collapse onto one entity on the client side.
    /// </para>
    /// </remarks>
    private static List<RemoteEntityRef> CollectSkipped<TEntity>(
        IEnumerable<TEntity> entities,
        bool cascade
    )
        where TEntity : EntityBase
    {
        var skipped = new List<RemoteEntityRef>();

        foreach (var entity in entities)
        {
            // A null element is filtered out by the save itself, so it is passed over here as well
            if (entity is not null)
            {
                RemoteEntityGraph.CollectSkipped(entity, cascade, skipped);
            }
        }

        return skipped;
    }

    /// <summary>Maps the remote-surface endpoints for CustomerEntity.</summary>
    private static void MapCustomerEndpoints(RouteGroupBuilder group)
    {
        MapCrud<CustomerEntity, CustomerIdValue, ICustomerRemoteRepository>(
            group,
            "Customer"
        );

        group.MapPost(
            "Customer/CheckUniqueness",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<CustomerCheckUniquenessRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<ICustomerRemoteRepository>();
                        return (object?)await repository.CheckUniquenessAsync(request.Entity, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );
    }

    /// <summary>Request body for CheckUniqueness (Customer).</summary>
    private sealed record CustomerCheckUniquenessRequest(CustomerEntity Entity);

    /// <summary>Maps the remote-surface endpoints for OrderEntity.</summary>
    private static void MapOrderEndpoints(RouteGroupBuilder group)
    {
        MapCrud<OrderEntity, OrderIdValue, IOrderRemoteRepository>(
            group,
            "Order"
        );

        group.MapPost(
            "Order/GetByCustomer",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetByCustomerRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetByCustomerAsync(request.CustomerId, request.Take, request.Skip, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/FindTop",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.FindTopAsync(context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/CountByCustomer",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderCountByCustomerRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.CountByCustomerAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/SearchMemo",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderSearchMemoRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.SearchMemoAsync(request.Keyword, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/GetByIds",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetByIdsRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetByIdsAsync(request.Ids, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/GetSummaries",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetSummariesRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetSummariesAsync(request.CustomerId, request.Take, request.Skip, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/SumAmounts",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderSumAmountsRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.SumAmountsAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/GetByIdsRaw",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetByIdsRawRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetByIdsRawAsync(request.Ids, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/FindTopRaw",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.FindTopRawAsync(context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/CountByCustomerRaw",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderCountByCustomerRawRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.CountByCustomerRawAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/GetMemoRowsRaw",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetMemoRowsRawRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetMemoRowsRawAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/GetByCustomerTyped",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderGetByCustomerTypedRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.GetByCustomerTypedAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/SpecialLookup",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderSpecialLookupRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.SpecialLookupAsync(request.CustomerId, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );

        group.MapPost(
            "Order/CheckUniqueness",
            (HttpContext context) =>
                ExecuteAsync(
                    context,
                    async () =>
                    {
                        var request = await ReadRequestAsync<OrderCheckUniquenessRequest>(context).ConfigureAwait(false);
                        var repository = context.RequestServices.GetRequiredService<IOrderRemoteRepository>();
                        return (object?)await repository.CheckUniquenessAsync(request.Entity, context.RequestAborted).ConfigureAwait(false);
                    }
                )
        );
    }

    /// <summary>Request body for GetByCustomer (Order).</summary>
    private sealed record OrderGetByCustomerRequest(int CustomerId, int Take, int Skip);

    /// <summary>Request body for CountByCustomer (Order).</summary>
    private sealed record OrderCountByCustomerRequest(int CustomerId);

    /// <summary>Request body for SearchMemo (Order).</summary>
    private sealed record OrderSearchMemoRequest(string Keyword);

    /// <summary>Request body for GetByIds (Order).</summary>
    private sealed record OrderGetByIdsRequest(IReadOnlyList<int> Ids);

    /// <summary>Request body for GetSummaries (Order).</summary>
    private sealed record OrderGetSummariesRequest(int CustomerId, int Take, int Skip);

    /// <summary>Request body for SumAmounts (Order).</summary>
    private sealed record OrderSumAmountsRequest(int CustomerId);

    /// <summary>Request body for GetByIdsRaw (Order).</summary>
    private sealed record OrderGetByIdsRawRequest(IReadOnlyList<int> Ids);

    /// <summary>Request body for CountByCustomerRaw (Order).</summary>
    private sealed record OrderCountByCustomerRawRequest(int CustomerId);

    /// <summary>Request body for GetMemoRowsRaw (Order).</summary>
    private sealed record OrderGetMemoRowsRawRequest(int CustomerId);

    /// <summary>Request body for GetByCustomerTyped (Order).</summary>
    private sealed record OrderGetByCustomerTypedRequest(CustomerIdValue CustomerId);

    /// <summary>Request body for SpecialLookup (Order).</summary>
    private sealed record OrderSpecialLookupRequest(int CustomerId);

    /// <summary>Request body for CheckUniqueness (Order).</summary>
    private sealed record OrderCheckUniquenessRequest(OrderEntity Entity);
}
