// <auto-generated />
// このファイルは QuickER の Scriban テンプレート（Templates/CSharpRuntime.scriban）から生成される
// ランタイムパッケージ用ソースです。手で編集しないでください（再生成で上書きされます）。
#nullable enable

using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Common;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using QuickER.Runtime;

namespace QuickER.Runtime.SqlServer;

/// <summary>SQL Server 接続を生成するファクトリ</summary>
public interface ISqlConnectionFactory
{
    /// <summary>新しい SQL 接続を生成する</summary>
    SqlConnection CreateConnection();
}

/// <summary>接続文字列から SQL 接続を生成する既定実装</summary>
public sealed class SqlConnectionFactory(string connectionString) : ISqlConnectionFactory
{
    /// <summary>新しい SQL 接続を生成する</summary>
    public SqlConnection CreateConnection() => new(connectionString);
}

/// <summary>エンティティに縛られない生 SQL 実行器の既定実装（束縛・スカラー変換・射影マップの単一系統）</summary>
/// <remarks>ステートレス（接続ファクトリのみ保持）のため DI では Singleton 登録できる。Repository の生 SQL メソッドはこの実装へ委譲する。</remarks>
public sealed partial class SqlExecutor(ISqlConnectionFactory connectionFactory) : ISqlExecutor
{
    /// <summary>SQL 接続の生成元</summary>
    private readonly ISqlConnectionFactory _connectionFactory = connectionFactory;

    /// <summary>生 SQL の SELECT を実行し、結果行を {TEntity} へ厳密（全列必須）にマップして返す</summary>
    public async Task<IReadOnlyList<TEntity>> QueryBySqlAsync<TEntity>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
        where TEntity : EntityBase, new()
    {
        ArgumentNullException.ThrowIfNull(sql);

        var metadata = EntitySaveMetadata.For(typeof(TEntity));
        var items = new List<TEntity>();

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(sql, connection);
        BindParameters(command, parameters);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(metadata.MapEntityFromRawSql<TEntity>(reader));
        }

        return items;
    }

    /// <summary>生 SQL の SELECT を実行し、結果行を任意の <typeparamref name="TResult"/> へ寛容に射影して返す</summary>
    public async Task<IReadOnlyList<TResult>> QueryProjectionBySqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(sql, connection);
        BindParameters(command, parameters);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        // 射影マッピング（単一値モード・DTO モード）は共有ヘルパーの 1 系統を使う
        return await RawSqlMapper.ReadProjectionRowsAsync<TResult>(reader, cancellationToken);
    }

    /// <summary>生 SQL（UPDATE/DELETE/任意 DML）を実行し、影響行数を返す</summary>
    public async Task<int> ExecuteSqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(sql, connection);
        BindParameters(command, parameters);

        return await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>生 SQL を実行し、単一のスカラー値を返す（該当なし・DBNull は <c>default</c>）</summary>
    public async Task<TResult?> ExecuteScalarSqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(sql, connection);
        BindParameters(command, parameters);

        var scalar = await command.ExecuteScalarAsync(cancellationToken);
        return RawSqlMapper.ConvertSingleValue<TResult>(scalar is DBNull ? null : scalar);
    }

    /// <summary>
    /// 匿名オブジェクト等の public インスタンスプロパティを列挙し、プロパティ名 <c>Foo</c> を SQL パラメータ
    /// <c>@Foo</c> として <c>AddWithValue</c> で束縛する（生 SQL には列文脈が無いため型は明示しない）。null のときは何もしない。
    /// 束縛対象プロパティの解決は共有ヘルパー <see cref="RawSqlMapper.GetBindableProperties"/> と 1 系統を共有する。
    /// </summary>
    internal static void BindParameters(SqlCommand command, object? parameters)
    {
        if (parameters is null)
        {
            return;
        }

        foreach (var property in RawSqlMapper.GetBindableProperties(parameters.GetType()))
        {
            var value =
                SqlParameterValue.Unwrap(property.GetValue(parameters));

            // コレクション値（IN 用）は共有ヘルパーで @名0, @名1, ... へ展開する（SQL 側の @名 も書き換え）
            if (RawSqlMapper.IsCollectionParameter(value))
            {
                RawSqlMapper.BindCollectionParameter(
                    command,
                    property.Name,
                    (System.Collections.IEnumerable)value!
                );
                continue;
            }

            command.Parameters.AddWithValue($"@{property.Name}", value ?? DBNull.Value);
        }
    }
}

/// <summary>メタデータを用いて CRUD を実装する SQL Server 向けリポジトリ基底クラス</summary>
public abstract partial class SqlServerRepository<TEntity, TKey>(
    ISqlConnectionFactory connectionFactory
) : IRepository<TEntity, TKey>
    where TEntity : EntityBase, new()
{
    /// <summary>エンティティ型ごとに 1 度だけ構築されるメタデータ（静的フィールドで再利用）</summary>
    private static readonly EntitySaveMetadata _metadata = EntitySaveMetadata.For(typeof(TEntity));

    /// <summary>SQL 接続の生成元</summary>
    private readonly ISqlConnectionFactory _connectionFactory = connectionFactory;

    /// <summary>生 SQL メソッドの委譲先（束縛・マッピングを 1 系統に集約）</summary>
    private readonly ISqlExecutor _sqlExecutor = new SqlExecutor(connectionFactory);

    /// <summary>主キーによる単一エンティティ取得（該当なしは null）</summary>
    public async Task<TEntity?> GetByIdAsync(TKey id, CancellationToken cancellationToken = default)
    {
        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(_metadata.SelectByIdSql, connection);
        _metadata.BindKeyParameter(command, id);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        if (!await reader.ReadAsync(cancellationToken))
        {
            return null;
        }

        return _metadata.MapEntity<TEntity>(reader);
    }

    /// <summary>全エンティティ取得</summary>
    public async Task<IReadOnlyList<TEntity>> GetAllAsync(
        CancellationToken cancellationToken = default
    )
    {
        var items = new List<TEntity>();

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(_metadata.SelectAllSql, connection);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(_metadata.MapEntity<TEntity>(reader));
        }

        return items;
    }

    /// <summary>エンティティ追加</summary>
    public async Task InsertAsync(TEntity entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(_metadata.InsertSql, connection);
        _metadata.BindInsertParameters(command, entity);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>エンティティのコレクションを SqlBulkCopy で一括追加する</summary>
    public async Task<int> BulkInsertAsync(
        IEnumerable<TEntity> entities,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entities);

        // 件数が確定しているコレクションが空なら接続を張らずに終了する
        if (entities is ICollection<TEntity> { Count: 0 })
        {
            return 0;
        }

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        using var bulkCopy = new SqlBulkCopy(connection)
        {
            DestinationTableName = _metadata.TableName,
        };
        using var reader = _metadata.CreateDataReader(entities);

        // 列名（DB カラム名）で明示マッピングし、列順への依存を避ける
        for (var i = 0; i < reader.FieldCount; i++)
        {
            var columnName = reader.GetName(i);
            bulkCopy.ColumnMappings.Add(columnName, columnName);
        }

        await bulkCopy.WriteToServerAsync(reader, cancellationToken);
        return bulkCopy.RowsCopied;
    }

    /// <summary>エンティティ更新（更新対象ありで true）</summary>
    public async Task<bool> UpdateAsync(
        TEntity entity,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entity);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(_metadata.UpdateSql, connection);
        _metadata.BindUpdateParameters(command, entity);

        var affected = await command.ExecuteNonQueryAsync(cancellationToken);
        return affected > 0;
    }

    /// <summary>主キーによるエンティティ削除（削除対象ありで true）</summary>
    public async Task<bool> DeleteAsync(TKey id, CancellationToken cancellationToken = default)
    {
        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(_metadata.DeleteSql, connection);
        _metadata.BindKeyParameter(command, id);

        var affected = await command.ExecuteNonQueryAsync(cancellationToken);
        return affected > 0;
    }

    /// <summary>検索条件・並び順・Include をチェーン指定して取得するクエリを開始する</summary>
    public SqlQuery<TEntity> Query() => new(new SqlServerSqlQueryExecutor<TEntity>(_connectionFactory));

    /// <summary>
    /// 無制限バイナリ列（除外列）を主キー指定で宛先ストリームへ読み出す（O(チャンク) のストリーミング＝blob 全量を
    /// メモリに載せない）。<paramref name="propertyName"/> は対象列の C# プロパティ名。行なし・列 NULL は
    /// <c>false</c>（宛先へ何も書かない）、データを書いた場合は <c>true</c>（空 blob も true）を返す。
    /// 楽観排他（rowversion）はスコープ外＝生 SQL と同格の直接列操作。
    /// </summary>
    protected async Task<bool> ReadUnboundedBinaryColumnAsync(
        string propertyName,
        TKey id,
        Stream destination,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(destination);

        var column = _metadata.ColumnByPropertyName(propertyName);
        var quotedColumn = _metadata.QuotedColumnName(column);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = new SqlCommand(
            $"SELECT {quotedColumn} FROM {_metadata.TableName} WHERE [{_metadata.KeyColumnName}] = @id;",
            connection
        );
        _metadata.BindKeyParameter(command, id);

        // SequentialAccess で列をストリームとして順次読む（巨大 blob を一括バッファしない）
        await using var reader = await command.ExecuteReaderAsync(
            CommandBehavior.SequentialAccess,
            cancellationToken
        );

        if (!await reader.ReadAsync(cancellationToken))
        {
            return false;
        }

        if (await reader.IsDBNullAsync(0, cancellationToken))
        {
            return false;
        }

        await using var source = reader.GetStream(0);
        await source.CopyToAsync(
            destination,
            UnboundedBinaryColumns.StreamCopyBufferSize,
            cancellationToken
        );
        return true;
    }

    /// <summary>
    /// 無制限バイナリ列（除外列）を主キー指定でストリームから書き込む（O(チャンク) のストリーミング）。
    /// <paramref name="source"/> が <c>null</c> のとき列を NULL に設定する。<c>CanSeek</c> でない Stream は
    /// <paramref name="length"/> の指定が必須（欠落は <see cref="ArgumentException"/>）。更新した場合は <c>true</c>、
    /// 該当行なしは <c>false</c> を返す。楽観排他（rowversion）はスコープ外＝生 SQL と同格の直接列操作。
    /// </summary>
    protected async Task<bool> WriteUnboundedBinaryColumnAsync(
        string propertyName,
        TKey id,
        Stream? source,
        long? length = null,
        CancellationToken cancellationToken = default
    )
    {
        var column = _metadata.ColumnByPropertyName(propertyName);
        var quotedColumn = _metadata.QuotedColumnName(column);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        // source=null は列を NULL に設定する（除外列を「未設定」に戻す手段）
        if (source is null)
        {
            await using var nullCommand = new SqlCommand(
                $"UPDATE {_metadata.TableName} SET {quotedColumn} = NULL WHERE [{_metadata.KeyColumnName}] = @id;",
                connection
            );
            _metadata.BindKeyParameter(nullCommand, id);
            return await nullCommand.ExecuteNonQueryAsync(cancellationToken) > 0;
        }

        // CanSeek/length の契約検証は方言に依らず統一する（SQLite の zeroblob は長さ確定が必須）
        var payloadLength = UnboundedBinaryColumns.ResolveWriteLength(source, length);
        // SqlClient は SqlDbType.VarBinary・Size=-1（max）で Value に Stream を渡すとストリーミング送信する
        _ = payloadLength;

        await using var command = new SqlCommand(
            $"UPDATE {_metadata.TableName} SET {quotedColumn} = @data WHERE [{_metadata.KeyColumnName}] = @id;",
            connection
        );
        var parameter = new SqlParameter("@data", SqlDbType.VarBinary, -1)
        {
            Value = source,
        };
        command.Parameters.Add(parameter);
        _metadata.BindKeyParameter(command, id);
        return await command.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    /// <summary>RowState に従って 1 トランザクションで追加・更新・削除を保存する（既定で子をカスケード）</summary>
    public async Task<int> SaveAsync(
        TEntity entity,
        bool cascadeSave = true,
        bool cascadeDelete = true,
        bool insertWhenUpdateMissing = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entity);

        // グラフ全体に変更が無ければ接続も張らずに終了する
        if (!EntityGraphSaver.HasChanges(entity, cascadeSave))
        {
            return 0;
        }

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        // カスケードを含むグラフ全体を 1 接続・1 トランザクションで保存（MSDTC 昇格を避ける）
        await using var transaction = (SqlTransaction)
            await connection.BeginTransactionAsync(cancellationToken);

        try
        {
            var rows = await EntityGraphSaver.SaveAsync(
                entity,
                connection,
                transaction,
                cascadeSave,
                cascadeDelete,
                insertWhenUpdateMissing,
                cancellationToken
            );
            await transaction.CommitAsync(cancellationToken);

            // コミット成功後に状態を確定（Added/Updated → Unchanged）し、再保存での二重処理を防ぐ
            EntityGraphSaver.AcceptChanges(entity, cascadeSave);
            return rows;
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    /// <summary>複数の集約ルートを 1 トランザクションでまとめて保存する（全件成功か全件ロールバックの原子的処理）</summary>
    public async Task<int> SaveAsync(
        IEnumerable<TEntity> entities,
        bool cascadeSave = true,
        bool cascadeDelete = true,
        bool insertWhenUpdateMissing = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entities);

        // 変更のあるグラフだけを対象にする（接続・トランザクションを張る前に絞り込む）
        var targets = entities
            .Where(entity => entity is not null && EntityGraphSaver.HasChanges(entity, cascadeSave))
            .ToList();
        if (targets.Count == 0)
        {
            return 0;
        }

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        // 全エンティティのグラフを 1 接続・1 トランザクションで保存（途中失敗時は全体ロールバック）
        await using var transaction = (SqlTransaction)
            await connection.BeginTransactionAsync(cancellationToken);

        try
        {
            var rows = 0;
            foreach (var entity in targets)
            {
                rows += await EntityGraphSaver.SaveAsync(
                    entity,
                    connection,
                    transaction,
                    cascadeSave,
                    cascadeDelete,
                    insertWhenUpdateMissing,
                    cancellationToken
                );
            }

            await transaction.CommitAsync(cancellationToken);

            // コミット成功後に全グラフの状態を確定（Added/Updated → Unchanged）し、再保存での二重処理を防ぐ
            foreach (var entity in targets)
            {
                EntityGraphSaver.AcceptChanges(entity, cascadeSave);
            }

            return rows;
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    /// <summary>生 SQL の SELECT を実行し、結果行を {TEntity} へマップして返す</summary>
    /// <remarks>
    /// SELECT には {TEntity} の全列が必要（<c>SELECT *</c> または全列指定）。部分 SELECT（列不足）は不可。
    /// パラメータは匿名オブジェクトの public プロパティ名を <c>@名</c> として型明示なしで束縛する
    /// （<b>値は必ずパラメータで渡すこと。文字列連結はインジェクションの危険がある</b>）。
    /// 実装は <see cref="ISqlExecutor"/> へ委譲する（束縛・マッピングの 1 系統化）。
    /// </remarks>
    public Task<IReadOnlyList<TEntity>> QueryBySqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.QueryBySqlAsync<TEntity>(sql, parameters, cancellationToken);

    /// <summary>生 SQL（UPDATE/DELETE/任意 DML）を実行し、影響行数を返す</summary>
    /// <remarks>
    /// 呼び出しごとに接続を開閉する（トランザクション引数なし）。複数文をアトミックに実行したい場合は、
    /// 1 回の呼び出し内で <c>BEGIN TRAN ... COMMIT</c> を SQL に記述すること。
    /// パラメータ束縛は <see cref="QueryBySqlAsync"/> と同じ
    /// （<b>値は必ずパラメータで渡すこと。文字列連結はインジェクションの危険がある</b>）。
    /// 実装は <see cref="ISqlExecutor"/> へ委譲する。
    /// </remarks>
    public Task<int> ExecuteSqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.ExecuteSqlAsync(sql, parameters, cancellationToken);

    /// <summary>生 SQL を実行し、単一のスカラー値を返す（該当なし・DBNull は <c>default</c>）</summary>
    /// <remarks>
    /// 結果が <c>null</c> / <see cref="DBNull"/> なら <c>default(TResult)</c>。型が合わない場合は
    /// <see cref="Convert.ChangeType(object, Type, IFormatProvider)"/>（InvariantCulture）でベストエフォート変換し、
    /// 変換できない場合は分かる例外を投げる。パラメータ束縛は <see cref="QueryBySqlAsync"/> と同じ
    /// （<b>値は必ずパラメータで渡すこと。文字列連結はインジェクションの危険がある</b>）。
    /// 実装は <see cref="ISqlExecutor"/> へ委譲する。
    /// </remarks>
    public Task<TResult?> ExecuteScalarSqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.ExecuteScalarSqlAsync<TResult>(sql, parameters, cancellationToken);

    /// <summary>生 SQL の SELECT を実行し、結果行を任意の <typeparamref name="TResult"/> へ寛容に射影して返す（名前付きクエリの自由 SQL 射影用）</summary>
    /// <remarks>
    /// パラメータ束縛は <see cref="QueryBySqlAsync"/> と同じ
    /// （<b>値は必ずパラメータで渡すこと。文字列連結はインジェクションの危険がある</b>）。
    /// 実装は <see cref="ISqlExecutor"/> へ委譲する。
    /// </remarks>
    protected Task<IReadOnlyList<TResult>> QueryProjectionBySqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.QueryProjectionBySqlAsync<TResult>(sql, parameters, cancellationToken);
}

/// <summary>クエリ WHERE 句パラメータ（名前・値・対象カラム名）。カラム名は判明時のみ設定し、型明示化に使う</summary>
/// <param name="Name">パラメータ名（例: @p0）</param>
/// <param name="Value">束縛する値（値オブジェクトを含み得る。素値化は束縛側で行う）</param>
/// <param name="ColumnName">角括弧なしの対象カラム名。列を特定できない場合は null</param>
public readonly record struct SqlQueryParameter(string Name, object? Value, string? ColumnName);

/// <summary>
/// <see cref="SqlQuery{TEntity}"/> の SQL Server 向け ADO 実行器。
/// プランの述語・並び順を <see cref="SqlExpressionTranslator"/> で SQL へ翻訳し、
/// FOR JSON でグラフを入れ子 JSON として 1 クエリ取得し、System.Text.Json で復元する。
/// </summary>
/// <remarks>
/// 方言 SQL（識別子クォート・SELECT 構文・ページング句）はこの実行器に閉じる。
/// SqlQuery は方言中立の <see cref="SqlQueryPlan{TEntity}"/> を渡すだけで、方言差はここでのみ吸収する。
/// </remarks>
public sealed class SqlServerSqlQueryExecutor<TEntity>(ISqlConnectionFactory connectionFactory)
    : ISqlQueryExecutor<TEntity>
    where TEntity : EntityBase
{
    /// <summary>SQL 接続の生成元</summary>
    private readonly ISqlConnectionFactory _connectionFactory = connectionFactory;

    private static string TableName => EntitySaveMetadata.For(typeof(TEntity)).TableName;

    // ナビゲーションは [JsonIgnore]（親参照の循環対策）が付くことがあるが、Include でのロードでは
    // それらも復元する必要があるため、解決子修飾でナビゲーションプロパティを読み取り対象に含める。
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        TypeInfoResolver = new DefaultJsonTypeInfoResolver
        {
            Modifiers = { IncludeNavigationProperties },
        },
        Converters = { new ValueObjectJsonConverterFactory() },
    };

    /// <summary>[JsonIgnore] 等で契約から外れたナビゲーションプロパティを、デシリアライズ対象として再登録する</summary>
    private static void IncludeNavigationProperties(JsonTypeInfo typeInfo)
    {
        if (typeInfo.Kind != JsonTypeInfoKind.Object)
        {
            return;
        }

        foreach (
            var property in typeInfo.Type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
        )
        {
            if (
                !property.CanRead
                || !property.CanWrite
                || property.GetCustomAttribute<NavigationReferenceAttribute>() is null
            )
            {
                continue;
            }

            var existing = typeInfo.Properties.FirstOrDefault(item =>
                string.Equals(item.Name, property.Name, StringComparison.OrdinalIgnoreCase)
            );
            if (existing is not null)
            {
                // [JsonIgnore] で無効化（Get/Set が null）されている場合は復活させ、Include で読み込めるようにする
                existing.Get ??= property.GetValue;
                existing.Set ??= property.SetValue;
            }
            else
            {
                var jsonProperty = typeInfo.CreateJsonPropertyInfo(
                    property.PropertyType,
                    property.Name
                );
                jsonProperty.Get = property.GetValue;
                jsonProperty.Set = property.SetValue;
                typeInfo.Properties.Add(jsonProperty);
            }
        }
    }

    /// <summary>条件に一致するエンティティを（Include 指定分とともに）一覧取得する</summary>
    public async Task<IReadOnlyList<TEntity>> ToListAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);

        if (plan.WithUnboundedBinary)
        {
            // 無制限バイナリ列を含める指定: 方言に依らず全列プレーン SELECT で実体化する（Include なしは終端でガード済み）
            return await MaterializeWithUnboundedBinaryAsync(
                plan,
                whereClause,
                parameters,
                plan.Take,
                plan.Skip,
                cancellationToken
            );
        }
        var json = await ReadJsonAsync(
            BuildJsonSelect(plan, whereClause, plan.Take, plan.Skip),
            parameters,
            cancellationToken
        );
        if (string.IsNullOrWhiteSpace(json))
        {
            return new List<TEntity>();
        }

        return JsonSerializer.Deserialize<List<TEntity>>(json, JsonOptions) ?? new List<TEntity>();
    }

    /// <summary>条件に一致するエンティティを射影して取得する（列参照のみ・Include なしのときは参照列だけをプレーン SELECT する）</summary>
    /// <remarks>
    /// Include があるか、セレクタから列参照のみを安全に抽出できない場合は、従来経路
    /// （全列取得 → メモリ内で射影）へフォールバックする。刈り込み可能時は参照列だけを
    /// プレーン SELECT（JSON 化しない）で発行し、部分実体化してから射影する。
    /// </remarks>
    public async Task<IReadOnlyList<TResult>> ToProjectionListAsync<TResult>(
        SqlQueryPlan<TEntity> plan,
        Expression<Func<TEntity, TResult>> selector,
        CancellationToken cancellationToken
    )
    {
        var metadata = EntitySaveMetadata.For(typeof(TEntity));

        // Include なし、かつセレクタが列参照のみ（すべて列プロパティ）のときだけサーバー側で列を刈り込む
        var projectionColumns =
            plan.Includes.Count == 0
            && ProjectionColumnCollector.TryCollect(selector, out var referenced)
                ? metadata.ResolveProjectionColumns(referenced)
                : null;

        var project = selector.Compile();

        if (projectionColumns is null)
        {
            // フォールバック: 全列を実体化してからメモリ内で射影する
            var entities = await ToListAsync(plan, cancellationToken);
            return entities.Select(project).ToList();
        }

        // サーバー側列刈り込み: 参照列のみをプレーン SELECT し、部分実体化してから射影する
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);
        var sql =
            $"SELECT {metadata.BuildColumnList(projectionColumns)} FROM {TableName}{whereClause}{BuildOrderAndPaging(plan, plan.Take, plan.Skip)};";

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = CreateCommand(connection, sql, parameters);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        var results = new List<TResult>();

        while (await reader.ReadAsync(cancellationToken))
        {
            // 参照列のみを埋めた部分エンティティに射影を適用する（RowState は無関係＝射影後に捨てる）
            var entity = metadata.MapEntityColumns<TEntity>(reader, projectionColumns);
            results.Add(project(entity));
        }

        return results;
    }

    /// <summary>条件に一致する先頭の 1 件を（Include 指定分とともに）取得する（該当なしは null）</summary>
    public async Task<TEntity?> FirstOrDefaultAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);

        if (plan.WithUnboundedBinary)
        {
            // 無制限バイナリ列を含める指定: 先頭 1 件を全列プレーン SELECT で実体化する（Include なしは終端でガード済み）
            var withBinary = await MaterializeWithUnboundedBinaryAsync(
                plan,
                whereClause,
                parameters,
                take: 1,
                plan.Skip,
                cancellationToken
            );
            return withBinary.Count > 0 ? withBinary[0] : null;
        }
        var json = await ReadJsonAsync(
            BuildJsonSelect(plan, whereClause, 1, plan.Skip),
            parameters,
            cancellationToken
        );
        if (string.IsNullOrWhiteSpace(json))
        {
            return null;
        }

        var list = JsonSerializer.Deserialize<List<TEntity>>(json, JsonOptions);
        return list is { Count: > 0 } ? list[0] : null;
    }

    /// <summary>条件に一致する件数を取得する（並び順・ページング・Include は関与しない）</summary>
    public async Task<int> CountAsync(SqlQueryPlan<TEntity> plan, CancellationToken cancellationToken)
    {
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = CreateCommand(
            connection,
            $"SELECT COUNT(*) FROM {TableName}{whereClause};",
            parameters
        );
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return Convert.ToInt32(result);
    }

    /// <summary>条件に一致するレコードが存在するかを取得する（並び順・ページング・Include は関与しない）</summary>
    public async Task<bool> AnyAsync(SqlQueryPlan<TEntity> plan, CancellationToken cancellationToken)
    {
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = CreateCommand(
            connection,
            $"SELECT CASE WHEN EXISTS (SELECT 1 FROM {TableName}{whereClause}) THEN 1 ELSE 0 END;",
            parameters
        );
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return Convert.ToInt32(result) != 0;
    }

    /// <summary>条件に一致する行を一括削除する。cascadeDelete=true で子孫も FK 連鎖で削除する</summary>
    public async Task<int> ExecuteDeleteAsync(
        SqlQueryPlan<TEntity> plan,
        bool cascadeDelete,
        CancellationToken cancellationToken
    )
    {
        var parameters = new List<SqlQueryParameter>();
        var whereClause = BuildWhereClause(plan, parameters);

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        if (!cascadeDelete)
        {
            await using var command = CreateCommand(
                connection,
                $"DELETE FROM {TableName}{whereClause};",
                parameters
            );
            return await command.ExecuteNonQueryAsync(cancellationToken);
        }

        // カスケード: 子孫→本体の順に並んだ DELETE 文群を 1 トランザクションで実行する
        await using var transaction = (SqlTransaction)
            await connection.BeginTransactionAsync(cancellationToken);

        try
        {
            var rows = 0;

            foreach (
                var sql in CascadeDeletePlanner.BuildDeleteStatements(
                    typeof(TEntity),
                    TableName,
                    whereClause
                )
            )
            {
                await using var command = new SqlCommand(sql, connection, transaction);
                AddParameters(command, parameters);
                rows += await command.ExecuteNonQueryAsync(cancellationToken);
            }

            await transaction.CommitAsync(cancellationToken);
            return rows;
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    /// <summary>
    /// WithUnboundedBinary 指定時の実体化。Include を使わず全列（無制限バイナリ列を含む）を
    /// プレーン SELECT し、RowState=Unchanged の正当なエンティティとして実体化する（方言共通）。
    /// SQL Server では既定の JSON 経由（Base64）を避けメモリ膨張を防ぐ。Include なし限定（終端でガード済み）。
    /// </summary>
    private async Task<IReadOnlyList<TEntity>> MaterializeWithUnboundedBinaryAsync(
        SqlQueryPlan<TEntity> plan,
        string whereClause,
        IReadOnlyList<SqlQueryParameter> parameters,
        int? take,
        int? skip,
        CancellationToken cancellationToken
    )
    {
        var metadata = EntitySaveMetadata.For(typeof(TEntity));
        // 全列（除外列＝無制限バイナリ列を含む）をプレーン SELECT する
        var sql =
            $"SELECT {metadata.BuildColumnList(metadata.AllProperties)} FROM {TableName}{whereClause}{BuildOrderAndPaging(plan, take, skip)};";

        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = CreateCommand(connection, sql, parameters);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        var results = new List<TEntity>();

        while (await reader.ReadAsync(cancellationToken))
        {
            // 全列を束縛した正当なエンティティ（RowState=Unchanged）として実体化する
            results.Add(
                metadata.MapEntityColumns<TEntity>(
                    reader,
                    metadata.AllProperties,
                    markUnchanged: true
                )
            );
        }

        return results;
    }

    /// <summary>FOR JSON の結果（約 2KB ごとに複数行で返る）を全行連結して 1 つの JSON 文字列にする</summary>
    private async Task<string> ReadJsonAsync(
        string sql,
        IReadOnlyList<SqlQueryParameter> parameters,
        CancellationToken cancellationToken
    )
    {
        await using var connection = _connectionFactory.CreateConnection();
        await connection.OpenAsync(cancellationToken);

        await using var command = CreateCommand(connection, sql, parameters);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        var chunks = new List<string>();
        while (await reader.ReadAsync(cancellationToken))
        {
            chunks.Add(reader.GetString(0));
        }

        return string.Concat(chunks);
    }

    /// <summary>ルートの WHERE・並び順・ページングと Include ツリーから FOR JSON の SELECT 文を組み立てる</summary>
    private static string BuildJsonSelect(
        SqlQueryPlan<TEntity> plan,
        string whereClause,
        int? take,
        int? skip
    ) =>
        JsonQueryPlanner.BuildSelect(
            typeof(TEntity),
            whereClause,
            BuildOrderAndPaging(plan, take, skip),
            plan.Includes
        );

    /// <summary>ORDER BY / OFFSET・FETCH 句を組み立てる（take/skip 指定時は ORDER BY 必須のためダミー順序を補う）</summary>
    private static string BuildOrderAndPaging(SqlQueryPlan<TEntity> plan, int? take, int? skip)
    {
        var orderings = BuildOrderings(plan);

        if (take.HasValue || skip.HasValue)
        {
            var ordering =
                orderings.Count == 0
                    ? " ORDER BY (SELECT NULL)"
                    : " ORDER BY " + string.Join(", ", orderings);
            return take.HasValue
                ? $"{ordering} OFFSET {skip ?? 0} ROWS FETCH NEXT {take.Value} ROWS ONLY"
                : $"{ordering} OFFSET {skip ?? 0} ROWS";
        }

        return orderings.Count == 0 ? string.Empty : " ORDER BY " + string.Join(", ", orderings);
    }

    /// <summary>プランの並び順（式木）を SQL の ORDER BY 要素（"[col] ASC" 等）へ翻訳する</summary>
    private static List<string> BuildOrderings(SqlQueryPlan<TEntity> plan)
    {
        var orderings = new List<string>(plan.Orderings.Count);
        foreach (var ordering in plan.Orderings)
        {
            orderings.Add(
                SqlExpressionTranslator.ToColumn(ordering.KeySelector)
                    + (ordering.Descending ? " DESC" : " ASC")
            );
        }

        return orderings;
    }

    /// <summary>プランの述語（式木）を WHERE 句へ翻訳し、値パラメータを parameters へ蓄積する（条件なしは空文字）</summary>
    private static string BuildWhereClause(
        SqlQueryPlan<TEntity> plan,
        List<SqlQueryParameter> parameters
    )
    {
        if (plan.Predicates.Count == 0)
        {
            return string.Empty;
        }

        var conditions = new List<string>(plan.Predicates.Count);
        foreach (var predicate in plan.Predicates)
        {
            conditions.Add(SqlExpressionTranslator.ToCondition(predicate.Body, parameters));
        }

        return " WHERE " + string.Join(" AND ", conditions);
    }

    /// <summary>蓄積したパラメータを設定したコマンドを生成する</summary>
    private SqlCommand CreateCommand(
        SqlConnection connection,
        string sql,
        IReadOnlyList<SqlQueryParameter> parameters
    )
    {
        var command = new SqlCommand(sql, connection);
        AddParameters(command, parameters);
        return command;
    }

    /// <summary>翻訳済みの条件パラメータをコマンドへ設定する</summary>
    /// <remarks>
    /// 列名が判明しているパラメータは、その列の [SqlColumnType] を用いて明示 SqlParameter を構築する
    /// （LOWER 越し比較など関数越しでも同型どうしのため無害）。列が特定できない場合は従来どおり AddWithValue。
    /// </remarks>
    private static void AddParameters(
        SqlCommand command,
        IReadOnlyList<SqlQueryParameter> parameters
    )
    {
        var metadata = EntitySaveMetadata.For(typeof(TEntity));
        foreach (var parameter in parameters)
        {
            var value =
                SqlParameterValue.Unwrap(parameter.Value);
            metadata.AddQueryParameter(command, parameter.Name, parameter.ColumnName, value);
        }
    }
}

/// <summary>Include ツリーと FK メタデータから FOR JSON の SELECT 文を組み立てるプランナー（DB 非依存・純粋）</summary>
public static class JsonQueryPlanner
{
    /// <summary>ルート型・WHERE 句・並び順ページング句・Include ツリーから、入れ子 JSON を返す SELECT 文を組み立てる</summary>
    public static string BuildSelect(
        Type rootType,
        string whereClause,
        string orderAndPaging,
        IReadOnlyList<IncludeNode> includes
    )
    {
        var aliasCounter = new int[1];
        var rootAlias = NextAlias(aliasCounter);
        var projection = BuildProjection(rootType, rootAlias, includes, aliasCounter);
        var tableName = EntitySaveMetadata.For(rootType).TableName;
        return $"SELECT {projection} FROM {tableName} AS {rootAlias}{whereClause}{orderAndPaging} FOR JSON PATH;";
    }

    private static string BuildProjection(
        Type type,
        string alias,
        IReadOnlyList<IncludeNode> includes,
        int[] aliasCounter
    )
    {
        var metadata = EntitySaveMetadata.For(type);
        var parts = new List<string>();

        // 列はプロパティ名へ別名付け（[col] AS Prop）して、System.Text.Json でそのまま復元できるようにする
        foreach (var (propertyName, columnName) in metadata.Columns)
        {
            parts.Add($"{alias}.[{columnName}] AS {propertyName}");
        }

        // Include した子は相関サブクエリ（FOR JSON）を埋め込む
        foreach (var node in includes)
        {
            parts.Add(BuildIncludeProjection(node, alias, aliasCounter));
        }

        return string.Join(", ", parts);
    }

    private static string BuildIncludeProjection(
        IncludeNode node,
        string parentAlias,
        int[] aliasCounter
    )
    {
        var attribute =
            node.Property.GetCustomAttribute<NavigationReferenceAttribute>()
            ?? throw new InvalidOperationException(
                $"{node.Property.Name} は [NavigationReference] を持つナビゲーションではありません。"
            );
        var childType = attribute.IsCollection
            ? node.Property.PropertyType.GetGenericArguments()[0]
            : node.Property.PropertyType;
        var childAlias = NextAlias(aliasCounter);
        var childTable = EntitySaveMetadata.For(childType).TableName;

        // 相関条件: 子方向は 子.[Dependent] = 親.[Principal]、親参照は 親.[Principal] = 自.[Dependent]
        var correlation = attribute.IsParentReference
            ? $"{childAlias}.[{attribute.PrincipalColumn}] = {parentAlias}.[{attribute.DependentColumn}]"
            : $"{childAlias}.[{attribute.DependentColumn}] = {parentAlias}.[{attribute.PrincipalColumn}]";

        var childProjection = BuildProjection(childType, childAlias, node.Children, aliasCounter);

        // コレクションは配列、単一参照は WITHOUT_ARRAY_WRAPPER でオブジェクトとして出力する。
        // ネストした FOR JSON の結果は外側で文字列にエスケープされるため、JSON_QUERY で包んで JSON のまま埋め込む。
        var arrayMode = attribute.IsCollection ? string.Empty : ", WITHOUT_ARRAY_WRAPPER";
        return $"JSON_QUERY((SELECT {childProjection} FROM {childTable} AS {childAlias} WHERE {correlation} FOR JSON PATH{arrayMode})) AS {node.Property.Name}";
    }

    private static string NextAlias(int[] aliasCounter) => "a" + aliasCounter[0]++;
}

/// <summary>ラムダ式（式木）を SQL の条件・列参照へ変換する</summary>
/// <remarks>対応構文は比較（== != &lt; &lt;= &gt; &gt;=）・論理結合（&amp;&amp; ||）・否定・null 判定・bool 列・文字列の Contains/StartsWith/EndsWith に限定し、範囲外は例外とする</remarks>
public static class SqlExpressionTranslator
{
    /// <summary>述語ラムダの本体を SQL 条件へ変換し、値はパラメータ化して parameters へ追加する</summary>
    public static string ToCondition(
        Expression expression,
        List<SqlQueryParameter> parameters
    ) => Visit(expression, parameters);

    /// <summary>キー選択ラムダから角括弧付きの列名を取り出す</summary>
    public static string ToColumn(LambdaExpression keySelector)
    {
        var member = Unwrap(keySelector.Body) as MemberExpression;

        if (member is null || !IsColumn(member))
        {
            throw new NotSupportedException(
                $"並び順にはエンティティのプロパティのみ指定できます: {keySelector}"
            );
        }

        return ColumnName(member.Member);
    }

    private static string Visit(
        Expression expression,
        List<SqlQueryParameter> parameters
    )
    {
        switch (expression)
        {
            case BinaryExpression { NodeType: ExpressionType.AndAlso } binary:
                return $"({Visit(binary.Left, parameters)} AND {Visit(binary.Right, parameters)})";

            case BinaryExpression { NodeType: ExpressionType.OrElse } binary:
                return $"({Visit(binary.Left, parameters)} OR {Visit(binary.Right, parameters)})";

            case BinaryExpression binary:
                return VisitComparison(binary, parameters);

            case UnaryExpression { NodeType: ExpressionType.Not } unary:
                return Unwrap(unary.Operand) is MemberExpression boolMember && IsColumn(boolMember)
                    ? $"{ColumnName(boolMember.Member)} = 0"
                    : $"NOT ({Visit(unary.Operand, parameters)})";

            case MethodCallExpression call
                when TryGetLike(call, out var likeColumn, out var likeKind):
                // 引数は string でも値オブジェクト（TSelf オーバーロード）でもよい。VO なら素値（string）へ開く
                var raw =
                    SqlParameterValue.Unwrap(Evaluate(call.Arguments[0])) as string ?? string.Empty;
                var pattern = likeKind switch
                {
                    LikeKind.Contains => "%" + EscapeLike(raw) + "%",
                    LikeKind.StartsWith => EscapeLike(raw) + "%",
                    _ => "%" + EscapeLike(raw),
                };
                return $"{likeColumn} LIKE {AddParameter(pattern, parameters, RawColumnName(likeColumn))} ESCAPE '\\'";

            case MethodCallExpression call
                when TryGetIn(call, out var inColumn, out var inCollection):
                return BuildInClause(inColumn, inCollection, parameters);

            case MethodCallExpression call
                when TryGetNullOrEmpty(call, out var neColumn, out var neWhitespace):
                // 空文字判定。IsNullOrWhiteSpace は前後空白も空扱いにする
                return neWhitespace
                    ? $"({neColumn} IS NULL OR LTRIM(RTRIM({neColumn})) = '')"
                    : $"({neColumn} IS NULL OR {neColumn} = '')";

            case MethodCallExpression call
                when TryGetEquals(call, out var eqColumn, out var eqArg, out var eqIgnoreCase):
                // 値は AddParameters 側で素値へ開かれる（VO 対応）
                var eqParameter = AddParameter(Evaluate(eqArg), parameters, RawColumnName(eqColumn));
                // 大文字小文字を無視する比較は両辺を LOWER で畳む
                return eqIgnoreCase
                    ? $"LOWER({eqColumn}) = LOWER({eqParameter})"
                    : $"{eqColumn} = {eqParameter}";

            case MemberExpression member when member.Type == typeof(bool) && IsColumn(member):
                return $"{ColumnName(member.Member)} = 1";

            default:
                throw new NotSupportedException($"この式は SQL へ変換できません: {expression}");
        }
    }

    private static string VisitComparison(
        BinaryExpression binary,
        List<SqlQueryParameter> parameters
    )
    {
        var left = Unwrap(binary.Left);
        var right = Unwrap(binary.Right);

        if (binary.NodeType is ExpressionType.Equal or ExpressionType.NotEqual)
        {
            var suffix = binary.NodeType == ExpressionType.NotEqual ? "NOT " : string.Empty;

            if (IsNull(right) && left is MemberExpression leftColumn && IsColumn(leftColumn))
            {
                return $"{ColumnName(leftColumn.Member)} IS {suffix}NULL";
            }

            if (IsNull(left) && right is MemberExpression rightColumn && IsColumn(rightColumn))
            {
                return $"{ColumnName(rightColumn.Member)} IS {suffix}NULL";
            }
        }

        var op = binary.NodeType switch
        {
            ExpressionType.Equal => "=",
            ExpressionType.NotEqual => "<>",
            ExpressionType.GreaterThan => ">",
            ExpressionType.GreaterThanOrEqual => ">=",
            ExpressionType.LessThan => "<",
            ExpressionType.LessThanOrEqual => "<=",
            _ => throw new NotSupportedException($"未対応の演算子です: {binary.NodeType}"),
        };

        // 一方が列で他方が値の比較では、値パラメータに対面の列名を添えて型明示化に使う（両辺が列/値なら添えない）
        var leftColumnSql = TryColumnName(left);
        var rightColumnSql = TryColumnName(right);
        return $"{Operand(left, parameters, RawColumnName(rightColumnSql))} {op} {Operand(right, parameters, RawColumnName(leftColumnSql))}";
    }

    /// <param name="expression">オペランドの式（列参照か定数値のいずれか）</param>
    /// <param name="parameters">値オペランドをパラメータ化する際の追加先リスト</param>
    /// <param name="counterpartColumn">値としてパラメータ化する場合に添える対面の列名（角括弧なし）。無ければ null</param>
    private static string Operand(
        Expression expression,
        List<SqlQueryParameter> parameters,
        string? counterpartColumn
    ) =>
        TryColumnName(expression) is { } column ? column
        : TryGetDatePart(expression, out var datePart) ? datePart
        : AddParameter(Evaluate(expression), parameters, counterpartColumn);

    private enum LikeKind
    {
        Contains,
        StartsWith,
        EndsWith,
    }

    private static bool TryGetLike(MethodCallExpression call, out string column, out LikeKind kind)
    {
        column = string.Empty;
        kind = LikeKind.Contains;

        if (
            call.Object is null
            || call.Arguments.Count != 1
            || (
                call.Method.DeclaringType != typeof(string)
                && !IsValueObjectStringMethod(call.Method)
            )
        )
        {
            return false;
        }

        if (Unwrap(call.Object) is not MemberExpression member || !IsColumn(member))
        {
            return false;
        }

        switch (call.Method.Name)
        {
            case "Contains":
                kind = LikeKind.Contains;
                break;
            case "StartsWith":
                kind = LikeKind.StartsWith;
                break;
            case "EndsWith":
                kind = LikeKind.EndsWith;
                break;
            default:
                return false;
        }

        column = ColumnName(member.Member);
        return true;
    }

    /// <summary>コレクションの Contains（配列＝静的 Enumerable.Contains / List・HashSet＝インスタンス Contains）を IN 変換の対象として判定する</summary>
    /// <remarks>列が引数側にあるものだけを対象にする（列が呼び出し対象側の string.Contains は LIKE 側で処理済み）</remarks>
    private static bool TryGetIn(
        MethodCallExpression call,
        out string column,
        out Expression collection
    )
    {
        column = string.Empty;
        collection = null!;

        if (call.Method.Name != "Contains")
        {
            return false;
        }

        // 配列など: 静的 Enumerable.Contains / MemoryExtensions.Contains(collection, item)（引数 2 個、呼び出し対象なし）
        if (call.Object is null && call.Arguments.Count == 2)
        {
            if (Unwrap(call.Arguments[1]) is MemberExpression staticItem && IsColumn(staticItem))
            {
                column = ColumnName(staticItem.Member);
                collection = UnwrapCollection(call.Arguments[0]);
                return true;
            }

            return false;
        }

        // List<T> / HashSet<T> など: インスタンス Contains(item)（引数 1 個、呼び出し対象がコレクション）
        // 配列は .NET のスパン版 Contains に解決され、呼び出し対象が op_Implicit(array) になる（UnwrapCollection で素の配列へ戻す）
        if (call.Object is not null && call.Arguments.Count == 1)
        {
            if (Unwrap(call.Arguments[0]) is MemberExpression instanceItem && IsColumn(instanceItem))
            {
                column = ColumnName(instanceItem.Member);
                collection = UnwrapCollection(call.Object);
                return true;
            }
        }

        return false;
    }

    /// <summary>コレクション式に付いた暗黙変換（配列→ReadOnlySpan などの op_Implicit / Convert）を剥がし、列挙可能な素のコレクション式へ戻す</summary>
    private static Expression UnwrapCollection(Expression expression)
    {
        while (true)
        {
            expression = Unwrap(expression);
            if (
                expression
                is MethodCallExpression
                {
                    Method.Name: "op_Implicit",
                    Object: null,
                    Arguments.Count: 1
                } conversion
            )
            {
                expression = conversion.Arguments[0];
                continue;
            }

            return expression;
        }
    }

    /// <summary>コレクションの各要素をパラメータ化して IN 句を組み立てる。空・null コレクションは該当なし（恒偽条件）にする</summary>
    private static string BuildInClause(
        string column,
        Expression collection,
        List<SqlQueryParameter> parameters
    )
    {
        // 文字列自体も IEnumerable だが、列挙対象のコレクションとしては扱わない
        if (Evaluate(collection) is not IEnumerable enumerable || enumerable is string)
        {
            throw new NotSupportedException(
                $"IN 検索には列挙可能なコレクション（配列・List など）を指定してください: {collection}"
            );
        }

        var placeholders = new List<string>();
        var rawColumn = RawColumnName(column);
        foreach (var item in enumerable)
        {
            placeholders.Add(AddParameter(item, parameters, rawColumn));
        }

        // IN () は不正な SQL のため、空コレクションは「該当なし」を表す恒偽条件にする
        return placeholders.Count == 0
            ? "1 = 0"
            : $"{column} IN ({string.Join(", ", placeholders)})";
    }

    /// <summary>x.Col.Equals(value) を等値比較の対象として判定する。第2引数が *IgnoreCase の StringComparison なら大文字小文字を無視する</summary>
    /// <remarks>列は素の列でも値オブジェクトでもよい。文字列・数値など列の型を問わず等値へ変換できる</remarks>
    private static bool TryGetEquals(
        MethodCallExpression call,
        out string column,
        out Expression argument,
        out bool ignoreCase
    )
    {
        column = string.Empty;
        argument = null!;
        ignoreCase = false;

        if (
            call.Object is null
            || call.Method.Name != "Equals"
            || TryColumnName(call.Object) is not { } resolvedColumn
        )
        {
            return false;
        }

        // Equals(value) / Equals(value, StringComparison) の 2 形式のみ対応する
        if (call.Arguments.Count == 1)
        {
            column = resolvedColumn;
            argument = call.Arguments[0];
            return true;
        }

        if (call.Arguments.Count == 2 && call.Method.DeclaringType == typeof(string))
        {
            ignoreCase = Evaluate(call.Arguments[1]) is StringComparison.OrdinalIgnoreCase
                or StringComparison.InvariantCultureIgnoreCase
                or StringComparison.CurrentCultureIgnoreCase;
            column = resolvedColumn;
            argument = call.Arguments[0];
            return true;
        }

        return false;
    }

    /// <summary>string.IsNullOrEmpty(x.Col) / IsNullOrWhiteSpace(x.Col) を判定する（列は素の列でも値オブジェクトの .Value でもよい）</summary>
    private static bool TryGetNullOrEmpty(
        MethodCallExpression call,
        out string column,
        out bool whitespace
    )
    {
        column = string.Empty;
        whitespace = call.Method.Name == "IsNullOrWhiteSpace";

        if (
            call.Object is not null
            || call.Method.DeclaringType != typeof(string)
            || call.Arguments.Count != 1
            || !(call.Method.Name == "IsNullOrEmpty" || whitespace)
            || TryColumnName(call.Arguments[0]) is not { } resolvedColumn
        )
        {
            return false;
        }

        column = resolvedColumn;
        return true;
    }

    /// <summary>文字列値オブジェクト（ValueObjectStringBase 由来）の Contains/StartsWith/EndsWith かどうか</summary>
    private static bool IsValueObjectStringMethod(MethodInfo method) =>
        method.DeclaringType is { IsGenericType: true } declaring
        && declaring.GetGenericTypeDefinition() == typeof(ValueObjectStringBase<>);

    /// <summary>object へのボックス化などの Convert を取り除く</summary>
    private static Expression Unwrap(Expression expression)
    {
        while (
            expression
                is UnaryExpression
                {
                    NodeType: ExpressionType.Convert or ExpressionType.ConvertChecked
                } unary
        )
        {
            expression = unary.Operand;
        }

        return expression;
    }

    /// <summary>ラムダ引数のプロパティ参照（= 列）かどうか</summary>
    private static bool IsColumn(MemberExpression member) =>
        member is { Expression: ParameterExpression, Member: PropertyInfo };

    private static bool IsNull(Expression expression) =>
        expression is ConstantExpression { Value: null };

    private static string ColumnName(MemberInfo member) =>
        $"[{member.GetCustomAttribute<ColumnAttribute>()?.Name ?? member.Name}]";

    /// <summary>列参照（素の列 x.Col、または値オブジェクトの x.Col.Value）から角括弧付き列名を取り出す。列でなければ null</summary>
    private static string? TryColumnName(Expression expression)
    {
        if (Unwrap(expression) is not MemberExpression member)
        {
            return null;
        }

        if (IsColumn(member))
        {
            return ColumnName(member.Member);
        }

        // 値オブジェクトの .Value を剥がし、内側の列（[col]）へ解決する（x.Col.Value → [col]）
        if (
            member.Member.Name == "Value"
            && typeof(IValueObject).IsAssignableFrom(member.Member.DeclaringType)
            && member.Expression is { } inner
            && Unwrap(inner) is MemberExpression valueObjectColumn
            && IsColumn(valueObjectColumn)
        )
        {
            return ColumnName(valueObjectColumn.Member);
        }

        return null;
    }

    /// <summary>DateTime 列の日付コンポーネント参照（x.Col.Year / x.Col.Value.Month など）を SQL の日付関数へ変換する</summary>
    private static bool TryGetDatePart(Expression expression, out string sql)
    {
        sql = string.Empty;

        if (
            Unwrap(expression) is not MemberExpression member
            || member.Expression is not { } source
            || TryColumnName(source) is not { } column
        )
        {
            return false;
        }

        sql = member.Member.Name switch
        {
            "Year" => $"YEAR({column})",
            "Month" => $"MONTH({column})",
            "Day" => $"DAY({column})",
            "Hour" => $"DATEPART(HOUR, {column})",
            "Minute" => $"DATEPART(MINUTE, {column})",
            "Second" => $"DATEPART(SECOND, {column})",
            "DayOfYear" => $"DATEPART(DAYOFYEAR, {column})",
            "Date" => $"CAST({column} AS date)",
            _ => string.Empty,
        };

        return sql.Length != 0;
    }

    /// <summary>定数・クロージャ変数などを評価して実値を得る</summary>
    private static object? Evaluate(Expression expression) =>
        expression is ConstantExpression constant
            ? constant.Value
            : Expression.Lambda(expression).Compile().DynamicInvoke();

    /// <param name="value">パラメータ化する実値（null 可）</param>
    /// <param name="parameters">生成したパラメータの追加先リスト</param>
    /// <param name="columnName">対象カラム名（角括弧なし）。列を特定できる場合のみ渡し、型明示化に使う</param>
    private static string AddParameter(
        object? value,
        List<SqlQueryParameter> parameters,
        string? columnName = null
    )
    {
        var name = "@p" + parameters.Count;
        parameters.Add(new SqlQueryParameter(name, value, columnName));
        return name;
    }

    /// <summary>角括弧付き列名 "[col]" から素のカラム名を取り出す。null・関数越し等で単純列でなければ null</summary>
    private static string? RawColumnName(string? bracketedColumn) =>
        bracketedColumn is { Length: >= 2 } && bracketedColumn[0] == '[' && bracketedColumn[^1] == ']'
            ? bracketedColumn[1..^1]
            : null;

    /// <summary>LIKE のワイルドカード（% _ [ \）をエスケープする</summary>
    private static string EscapeLike(string value) =>
        value.Replace("\\", "\\\\").Replace("%", "\\%").Replace("_", "\\_").Replace("[", "\\[");
}

/// <summary>エンティティ型の属性からテーブル・カラム情報、CRUD 用 SQL、カスケード子ナビゲーションを構築・保持し、行マッピングとパラメータ束縛を提供するメタデータ</summary>
/// <remarks>型をキーに 1 度だけ構築しキャッシュする（リフレクションコスト削減）。Repository の CRUD・グラフ保存・JSON クエリプランナ・カスケード削除プランナが共用する</remarks>
public sealed class EntitySaveMetadata
{
    private static readonly ConcurrentDictionary<Type, EntitySaveMetadata> _cache = new();

    /// <summary>角括弧で囲んだテーブル名</summary>
    public required string TableName { get; init; }
    /// <summary>クォートなしの生テーブル名（無制限バイナリ列の Stream アクセサで SqliteBlob 等が要求する）</summary>
    public required string RawTableName { get; init; }

    /// <summary>主キーに対応するプロパティ</summary>
    public required PropertyInfo KeyProperty { get; init; }

    /// <summary>主キーのカラム名</summary>
    public required string KeyColumnName { get; init; }

    /// <summary>マッピング対象の全カラムプロパティ（ナビゲーション・基底プロパティ除く）。INSERT / BulkInsert は常にこれを使う</summary>
    public required IReadOnlyList<PropertyInfo> AllProperties { get; init; }

    /// <summary>SELECT / UPDATE 対象の列プロパティ（全列から無制限バイナリ列を除いたもの。除外列なしは全列と一致）。行マッピングで使う</summary>
    public required IReadOnlyList<PropertyInfo> SelectProperties { get; init; }

    /// <summary>SELECT / UPDATE から除外する無制限バイナリ列（<see cref="UnboundedBinaryColumnAttribute"/> 付き）。除外列なしは空</summary>
    public required IReadOnlyList<PropertyInfo> ExcludedProperties { get; init; }

    /// <summary>主キーを除くカラムプロパティ</summary>
    public required IReadOnlyList<PropertyInfo> NonKeyProperties { get; init; }

    /// <summary>カラムの (プロパティ名, カラム名) 対応。JSON 射影の別名付け（[col] AS Prop）に使う</summary>
    public required IReadOnlyList<(string PropertyName, string ColumnName)> Columns { get; init; }

    /// <summary>カラム名 → 列プロパティの対応（クエリ WHERE 句パラメータの型明示化で列型を引くのに使う）</summary>
    public required IReadOnlyDictionary<string, PropertyInfo> PropertyByColumn { get; init; }

    /// <summary>SELECT 用の角括弧付きカラム一覧（例: [id], [name]）</summary>
    public required string ColumnList { get; init; }

    /// <summary>全件取得 SELECT 文</summary>
    public required string SelectAllSql { get; init; }

    /// <summary>主キー指定取得 SELECT 文</summary>
    public required string SelectByIdSql { get; init; }

    /// <summary>INSERT 文</summary>
    public required string InsertSql { get; init; }

    /// <summary>UPDATE 文</summary>
    public required string UpdateSql { get; init; }

    /// <summary>DELETE 文</summary>
    public required string DeleteSql { get; init; }

    /// <summary>カスケード対象の子ナビゲーション</summary>
    public required IReadOnlyList<CascadeNavigation> CascadeNavigations { get; init; }

    /// <summary>指定型のメタデータを取得する（型ごとに 1 度だけ構築しキャッシュ）</summary>
    public static EntitySaveMetadata For(Type entityType) => _cache.GetOrAdd(entityType, Build);

    private static EntitySaveMetadata Build(Type entityType)
    {
        var tableAttribute =
            entityType.GetCustomAttribute<TableAttribute>()
            ?? throw new InvalidOperationException(
                $"{entityType.Name} に [Table] 属性が必要です。"
            );
        var allProperties = entityType
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToList();
        var columns = allProperties
            .Where(property =>
                property.CanRead
                && property.CanWrite
                && property.DeclaringType != typeof(EntityBase)
                && property.GetCustomAttribute<NavigationReferenceAttribute>() is null
            )
            .ToList();
        var keyProperties = columns
            .Where(property => property.GetCustomAttribute<KeyAttribute>() is not null)
            .ToList();
        var keyProperty = keyProperties.Count switch
        {
            0 => throw new InvalidOperationException(
                $"{entityType.Name} に [Key] 属性付きプロパティが必要です。"
            ),
            1 => keyProperties[0],
            _ => throw new InvalidOperationException(
                $"{entityType.Name} の [Key] 属性付きプロパティは 1 つのみ許可されます（複合キーは Repository 非対応。対象: {string.Join(", ", keyProperties.Select(property => property.Name))}）。"
            ),
        };
        // 無制限バイナリ列（UnboundedBinaryColumnAttribute）を SELECT / UPDATE から外す。全列（AllProperties）は
        // INSERT / BulkInsert のため保持し、SELECT 用列集合（selectProperties）だけを縮小する。除外列なしは全列と一致
        var excludedColumns = columns
            .Where(property =>
                property.GetCustomAttribute<UnboundedBinaryColumnAttribute>() is not null
            )
            .ToList();
        var selectProperties =
            excludedColumns.Count == 0
                ? columns
                : columns.Where(property => !excludedColumns.Contains(property)).ToList();
        var nonKeyProperties = selectProperties
            .Where(property => property != keyProperty)
            .ToList();
        var tableName = $"[{tableAttribute.Name}]";
        var keyColumnName = GetColumnName(keyProperty);
        var columnList = string.Join(", ", selectProperties.Select(property => $"[{GetColumnName(property)}]"));
        var updateAssignments = nonKeyProperties.Select(property =>
            $"[{GetColumnName(property)}] = @{property.Name}"
        );
        var cascades = allProperties
            .Select(property =>
                (property, attribute: property.GetCustomAttribute<NavigationReferenceAttribute>())
            )
            .Where(pair => pair.attribute is { Cascade: true })
            .Select(pair => new CascadeNavigation(
                pair.property,
                pair.attribute!.IsCollection,
                pair.attribute.IsCollection
                    ? pair.property.PropertyType.GetGenericArguments()[0]
                    : pair.property.PropertyType,
                pair.attribute.PrincipalColumn,
                pair.attribute.DependentColumn
            ))
            .ToList();

        return new EntitySaveMetadata
        {
            TableName = tableName,
            RawTableName = tableAttribute.Name,
            KeyProperty = keyProperty,
            KeyColumnName = keyColumnName,
            AllProperties = columns,
            SelectProperties = selectProperties,
            ExcludedProperties = excludedColumns,
            NonKeyProperties = nonKeyProperties,
            Columns = selectProperties.Select(property => (property.Name, GetColumnName(property))).ToList(),
            PropertyByColumn = columns.ToDictionary(
                GetColumnName,
                property => property,
                StringComparer.Ordinal
            ),
            ColumnList = columnList,
            SelectAllSql = $"SELECT {columnList} FROM {tableName};",
            SelectByIdSql = $"SELECT {columnList} FROM {tableName} WHERE [{keyColumnName}] = @id;",
            InsertSql =
                $"INSERT INTO {tableName} ({string.Join(", ", columns.Select(property => $"[{GetColumnName(property)}]"))}) VALUES ({string.Join(", ", columns.Select(property => $"@{property.Name}"))});",
            UpdateSql =
                $"UPDATE {tableName} SET {string.Join(", ", updateAssignments)} WHERE [{keyColumnName}] = @id;",
            DeleteSql = $"DELETE FROM {tableName} WHERE [{keyColumnName}] = @id;",
            CascadeNavigations = cascades,
        };
    }

    /// <summary>データリーダーの 1 行をエンティティへマッピングする</summary>
    public TEntity MapEntity<TEntity>(SqlDataReader reader)
        where TEntity : EntityBase, new()
    {
        var entity = new TEntity();

        // 無制限バイナリ列は既定で SELECT 除外のため SelectProperties のみをマップする（除外列なしは全列と一致）
        foreach (var property in SelectProperties)
        {
            var columnName = GetColumnName(property);
            var value = reader[columnName];

            if (value is DBNull)
            {
                property.SetValue(entity, null);
            }
            else
            {
                // 値オブジェクトは内包型へ変換して包み直す（Wrap 内で Convert.ChangeType 済み）
                property.SetValue(entity, SqlValueObjectActivator.Wrap(value, property.PropertyType));
            }
        }

        // DB から読み込んだ行は変更なし扱いにする（その後の編集で Updated に遷移）
        entity.RowState = RowState.Unchanged;
        return entity;
    }

    /// <summary>
    /// 生 SQL の結果行を {TEntity} へマップする。<see cref="MapEntity"/> と同じ厳密マッピング（SELECT 対象列は必須）だが、
    /// 列不足（部分 SELECT）で列が引けなかった場合は、必要な列を含む <see cref="InvalidOperationException"/> でラップして
    /// 分かりやすくする。未知の列参照で投げられる例外はデータリーダーの実装で異なる
    /// （<see cref="IndexOutOfRangeException"/> と <see cref="ArgumentOutOfRangeException"/>）ため両方を捕捉する。
    /// 無制限バイナリ列は既定では取得しないが、生 SQL の SELECT に明示的に含まれていれば追加でマップする（ユーザーが意図して選んだ場合に取得できる）。
    /// </summary>
    public TEntity MapEntityFromRawSql<TEntity>(SqlDataReader reader)
        where TEntity : EntityBase, new()
    {
        TEntity entity;

        try
        {
            entity = MapEntity<TEntity>(reader);
        }
        catch (Exception ex) when (ex is IndexOutOfRangeException or ArgumentOutOfRangeException)
        {
            throw new InvalidOperationException(
                $"生 SQL の SELECT には {typeof(TEntity).Name} の列（{ColumnList}）が必要です（SELECT * または全列指定）。"
                    + $"結果セットに不足している列があります: {ex.Message}",
                ex
            );
        }

        // 除外列（無制限バイナリ）が生 SQL の結果に含まれていれば opportunistic に取り込む
        if (ExcludedProperties.Count > 0)
        {
            var present = RawReaderColumnNames(reader);

            foreach (var property in ExcludedProperties)
            {
                var columnName = GetColumnName(property);

                if (!present.Contains(columnName))
                {
                    continue;
                }

                var value = reader[columnName];

                if (value is DBNull)
                {
                    property.SetValue(entity, null);
                }
                else
                {
                    property.SetValue(entity, SqlValueObjectActivator.Wrap(value, property.PropertyType));
                }
            }

            // opportunistic な代入で状態が動かないよう変更なしを再確定する（列プロパティは素の auto-property だが念のため）
            entity.RowState = RowState.Unchanged;
        }

        return entity;
    }

    /// <summary>データリーダーの列名集合を大文字小文字無視で 1 度だけ列挙する（生 SQL の除外列有無判定に使う）</summary>
    private static HashSet<string> RawReaderColumnNames(SqlDataReader reader)
    {
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        for (var i = 0; i < reader.FieldCount; i++)
        {
            names.Add(reader.GetName(i));
        }

        return names;
    }

    /// <summary>
    /// 射影セレクタが参照する列プロパティ名集合を、SELECT すべき列プロパティ（<see cref="PropertyInfo"/>）へ解決する。
    /// 参照がすべて列プロパティ（無制限バイナリ列を含む）なら順序どおりの一覧を返し、1 つでもナビゲーション等の
    /// 非列名が混じる、あるいは参照が 0 件なら <c>null</c>（＝サーバー側列刈り込み不可・従来経路へフォールバック）を返す。
    /// </summary>
    public IReadOnlyList<PropertyInfo>? ResolveProjectionColumns(
        IReadOnlyCollection<string> propertyNames
    )
    {
        // 参照列が 0 件だと SELECT する列が無くフォールバックが必要（例: 定数のみの射影）
        if (propertyNames.Count == 0)
        {
            return null;
        }

        var resolved = new List<PropertyInfo>(propertyNames.Count);

        foreach (var name in propertyNames)
        {
            // 全列（AllProperties）から名前一致で引く（除外＝無制限バイナリ列も射影が参照していれば取得対象にする）
            var property = AllProperties.FirstOrDefault(candidate => candidate.Name == name);

            if (property is null)
            {
                // 列でない（ナビゲーション等）が混じった＝安全に刈り込めない
                return null;
            }

            resolved.Add(property);
        }

        return resolved;
    }

    /// <summary>指定した列プロパティ群を、角括弧付きカラム名の "," 連結（例: [id], [name]）にした SELECT 列リストを返す（射影刈り込み用）</summary>
    public string BuildColumnList(IReadOnlyList<PropertyInfo> properties) =>
        string.Join(
            ", ",
            properties.Select(property => $"[{GetColumnName(property)}]")
        );

    /// <summary>
    /// データリーダーの 1 行を、指定した列プロパティのみマッピングした {TEntity} を返す（射影のサーバー側列刈り込み・WithUnboundedBinary の全列取得で共用）。
    /// SELECT に含めた列だけを束縛し、それ以外の列は既定値のまま。射影用途（<paramref name="markUnchanged"/> = false・既定）は
    /// セレクタ適用後に捨てるため RowState を設定しないが、WithUnboundedBinary の全列取得（<paramref name="markUnchanged"/> = true）は
    /// 通常取得と同等の正当なエンティティを返すため RowState=Unchanged を確定する。
    /// </summary>
    public TEntity MapEntityColumns<TEntity>(
        SqlDataReader reader,
        IReadOnlyList<PropertyInfo> properties,
        bool markUnchanged = false
    )
        where TEntity : EntityBase
    {
        // クエリ実行器の TEntity は new() 制約を持たないため Activator で生成する（エンティティは必ず引数なしコンストラクタを持つ）
        var entity = (TEntity)Activator.CreateInstance(typeof(TEntity))!;

        foreach (var property in properties)
        {
            var value = reader[GetColumnName(property)];

            if (value is DBNull)
            {
                property.SetValue(entity, null);
            }
            else
            {
                // 値オブジェクトは内包型へ変換して包み直す（Wrap 内で Convert.ChangeType 済み）
                property.SetValue(entity, SqlValueObjectActivator.Wrap(value, property.PropertyType));
            }
        }

        if (markUnchanged)
        {
            // 全列を束縛した「正当なエンティティ」として返す場合は、DB 読み込み行として変更なしを確定する
            entity.RowState = RowState.Unchanged;
        }

        return entity;
    }

    /// <summary>INSERT 用パラメータ（全カラム）を設定する（追加・グラフ挿入で共用）</summary>
    public void BindInsertParameters(SqlCommand command, EntityBase entity)
    {
        foreach (var property in AllProperties)
        {
            AddColumnParameter(
                command,
                $"@{property.Name}",
                property,
                SqlParameterValue.Unwrap(property.GetValue(entity))
            );
        }
    }

    /// <summary>UPDATE 用パラメータ（非キー列＋主キー）を設定する（更新・グラフ更新で共用）</summary>
    public void BindUpdateParameters(SqlCommand command, EntityBase entity)
    {
        // 無制限バイナリ列（UPDATE 対象外）に値が残ったままの更新はサイレントに失われるため事前に弾く。
        // 直接 UpdateAsync とグラフのカスケード更新はどちらもここを通るため 1 箇所で被覆できる
        UnboundedBinaryColumns.ThrowIfExcludedAssigned(entity);

        foreach (var property in NonKeyProperties)
        {
            AddColumnParameter(
                command,
                $"@{property.Name}",
                property,
                SqlParameterValue.Unwrap(property.GetValue(entity))
            );
        }

        AddColumnParameter(
            command,
            "@id",
            KeyProperty,
            SqlParameterValue.Unwrap(KeyProperty.GetValue(entity))
        );
    }

    /// <summary>エンティティの主キー値を @id パラメータへ設定する（グラフ削除で使用）</summary>
    public void BindEntityKeyParameter(SqlCommand command, EntityBase entity)
    {
        AddColumnParameter(
            command,
            "@id",
            KeyProperty,
            SqlParameterValue.Unwrap(KeyProperty.GetValue(entity))
        );
    }

    /// <summary>外部から渡された主キー値を @id パラメータへ設定する（GetById/Delete で使用）</summary>
    public void BindKeyParameter(SqlCommand command, object? id)
    {
        var value =
            SqlParameterValue.Unwrap(id)
            ?? throw new InvalidOperationException("id は null にできません。");
        AddColumnParameter(command, "@id", KeyProperty, value);
    }

    /// <summary>[SqlColumnType] 属性が生成されない場合の束縛。従来どおり AddWithValue で追加する</summary>
    /// <param name="command">パラメータを追加する対象コマンド</param>
    /// <param name="name">パラメータ名（@付き）</param>
    /// <param name="property">対象列に対応するプロパティ（この分岐では未使用）</param>
    /// <param name="rawValue">値オブジェクトは既に素値へ開いた後の値。null は DBNull.Value として束縛する</param>
    private static void AddColumnParameter(
        SqlCommand command,
        string name,
        PropertyInfo property,
        object? rawValue
    ) => command.Parameters.AddWithValue(name, rawValue ?? DBNull.Value);

    /// <summary>
    /// クエリ WHERE 句パラメータを束縛する。列名が判明していてその列プロパティが見つかれば列型で明示構築し、
    /// なければ AddWithValue にフォールバックする。
    /// </summary>
    /// <param name="command">パラメータを追加する対象コマンド</param>
    /// <param name="name">パラメータ名（@付き）</param>
    /// <param name="columnName">角括弧なしのカラム名。列が特定できない場合は null</param>
    /// <param name="rawValue">値オブジェクトは既に素値へ開いた後の値。null は DBNull.Value として束縛する</param>
    public void AddQueryParameter(
        SqlCommand command,
        string name,
        string? columnName,
        object? rawValue
    )
    {
        if (columnName is not null && PropertyByColumn.TryGetValue(columnName, out var property))
        {
            AddColumnParameter(command, name, property, rawValue);
            return;
        }

        command.Parameters.AddWithValue(name, rawValue ?? DBNull.Value);
    }

    /// <summary>エンティティのコレクションを 1 行ずつ読み出す SqlBulkCopy 用の IDataReader を生成する</summary>
    public IDataReader CreateDataReader(IEnumerable<EntityBase> entities) =>
        new EntityDataReader(AllProperties, entities);

    /// <summary>エンティティ列を 1 行ずつ読み出して SqlBulkCopy へ流す IDataReader（DataTable を介さずメモリ効率を高める）</summary>
    /// <remarks>SqlBulkCopy は Read・GetValue・FieldCount・GetName・GetOrdinal のみ使用するため、それ以外の型付き取得は未対応とする</remarks>
    private sealed class EntityDataReader : IDataReader
    {
        private readonly IReadOnlyList<PropertyInfo> _properties;
        private readonly string[] _columnNames;
        private readonly IEnumerator<EntityBase> _enumerator;

        public EntityDataReader(
            IReadOnlyList<PropertyInfo> properties,
            IEnumerable<EntityBase> entities
        )
        {
            _properties = properties;
            _columnNames = properties.Select(GetColumnName).ToArray();
            _enumerator = entities.GetEnumerator();
        }

        public int FieldCount => _properties.Count;

        public bool Read() => _enumerator.MoveNext();

        public object GetValue(int i) =>
            SqlParameterValue.Unwrap(_properties[i].GetValue(_enumerator.Current)) ?? DBNull.Value;

        public string GetName(int i) => _columnNames[i];

        public int GetOrdinal(string name)
        {
            var index = Array.IndexOf(_columnNames, name);
            return index >= 0
                ? index
                : throw new IndexOutOfRangeException($"列 {name} は存在しません。");
        }

        // Nullable<T> は基底型を返す（SqlBulkCopy の列型解決と整合させる）
        public Type GetFieldType(int i) =>
            Nullable.GetUnderlyingType(_properties[i].PropertyType) ?? _properties[i].PropertyType;

        public bool IsDBNull(int i) => GetValue(i) is DBNull;

        public object this[int i] => GetValue(i);

        public object this[string name] => GetValue(GetOrdinal(name));

        public int GetValues(object[] values)
        {
            var count = Math.Min(values.Length, FieldCount);
            for (var i = 0; i < count; i++)
            {
                values[i] = GetValue(i);
            }

            return count;
        }

        public void Dispose() => _enumerator.Dispose();

        public int Depth => 0;

        public bool IsClosed => false;

        public int RecordsAffected => -1;

        public void Close() { }

        public bool NextResult() => false;

        public DataTable? GetSchemaTable() => null;

        // 以降は SqlBulkCopy では呼ばれないため未対応とする
        public bool GetBoolean(int i) => throw new NotSupportedException();

        public byte GetByte(int i) => throw new NotSupportedException();

        public long GetBytes(
            int i,
            long fieldOffset,
            byte[]? buffer,
            int bufferOffset,
            int length
        ) => throw new NotSupportedException();

        public char GetChar(int i) => throw new NotSupportedException();

        public long GetChars(
            int i,
            long fieldOffset,
            char[]? buffer,
            int bufferOffset,
            int length
        ) => throw new NotSupportedException();

        public IDataReader GetData(int i) => throw new NotSupportedException();

        public string GetDataTypeName(int i) => throw new NotSupportedException();

        public DateTime GetDateTime(int i) => throw new NotSupportedException();

        public decimal GetDecimal(int i) => throw new NotSupportedException();

        public double GetDouble(int i) => throw new NotSupportedException();

        public float GetFloat(int i) => throw new NotSupportedException();

        public Guid GetGuid(int i) => throw new NotSupportedException();

        public short GetInt16(int i) => throw new NotSupportedException();

        public int GetInt32(int i) => throw new NotSupportedException();

        public long GetInt64(int i) => throw new NotSupportedException();

        public string GetString(int i) => throw new NotSupportedException();
    }

    private static string GetColumnName(PropertyInfo property) =>
        property.GetCustomAttribute<ColumnAttribute>()?.Name ?? property.Name;

    /// <summary>C# プロパティ名から対応する列プロパティを引く（無制限バイナリ列＝除外列を含む全列から探す）。Stream アクセサが Repository / インメモリ双方で使う</summary>
    public PropertyInfo ColumnByPropertyName(string propertyName) =>
        AllProperties.FirstOrDefault(property => property.Name == propertyName)
        ?? throw new InvalidOperationException(
            $"プロパティ {propertyName} は列として見つかりませんでした。"
        );

    /// <summary>指定した列プロパティのクォート付きカラム名（例: [payload]）を返す（Stream アクセサの SQL 組み立て用）</summary>
    public string QuotedColumnName(PropertyInfo property) =>
        $"[{GetColumnName(property)}]";

    /// <summary>指定した列プロパティのクォートなし生カラム名を返す（SqliteBlob 等が要求する）</summary>
    public string RawColumnName(PropertyInfo property) => GetColumnName(property);
}

/// <summary>カスケード削除の DELETE 文群を FK メタデータから組み立てるプランナー（DB 非依存・純粋）</summary>
public static class CascadeDeletePlanner
{
    /// <summary>条件に一致する rootType の行と、その子孫を削除する DELETE 文を「子→親」の実行順で返す</summary>
    /// <param name="rootType">削除の起点となるエンティティ型</param>
    /// <param name="rootTable">角括弧付きのルートテーブル名</param>
    /// <param name="whereClause">ルートの WHERE 句（" WHERE …" または空文字）</param>
    public static IReadOnlyList<string> BuildDeleteStatements(
        Type rootType,
        string rootTable,
        string whereClause
    )
    {
        var statements = new List<string>();
        AppendDescendantDeletes(
            rootType,
            rootTable,
            whereClause,
            new HashSet<Type> { rootType },
            statements
        );
        statements.Add($"DELETE FROM {rootTable}{whereClause};");
        return statements;
    }

    private static void AppendDescendantDeletes(
        Type parentType,
        string parentTable,
        string parentScopeWhere,
        HashSet<Type> visited,
        List<string> statements
    )
    {
        foreach (var navigation in EntitySaveMetadata.For(parentType).CascadeNavigations)
        {
            // 循環するカスケード（自己参照等）は固定ネストでは表現できないため未対応とする
            if (!visited.Add(navigation.ChildType))
            {
                throw new NotSupportedException(
                    $"循環するカスケード（{navigation.ChildType.Name}）は ExecuteDeleteAsync では未対応です。グラフをロードして SaveAsync を使うか、DB の ON DELETE CASCADE を利用してください。"
                );
            }

            var childTable = EntitySaveMetadata.For(navigation.ChildType).TableName;
            var childScopeWhere =
                $" WHERE [{navigation.DependentColumn}] IN (SELECT [{navigation.PrincipalColumn}] FROM {parentTable}{parentScopeWhere})";

            // 先に孫以下を削除してから子を削除する（FK 整合）
            AppendDescendantDeletes(
                navigation.ChildType,
                childTable,
                childScopeWhere,
                visited,
                statements
            );
            statements.Add($"DELETE FROM {childTable}{childScopeWhere};");

            visited.Remove(navigation.ChildType);
        }
    }
}

/// <summary>RowState に従ってエンティティのグラフを 1 トランザクションで保存する内部エンジン</summary>
public static class EntityGraphSaver
{
    /// <summary>自身、または（cascade 時）子に変更があるか</summary>
    public static bool HasChanges(EntityBase entity, bool cascade) =>
        entity.HasChanges
        || (cascade && EnumerateCascadeChildren(entity).Any(child => HasChanges(child, true)));

    /// <summary>グラフを保存し、保存したレコード数を返す</summary>
    public static async Task<int> SaveAsync(
        EntityBase entity,
        SqlConnection connection,
        SqlTransaction transaction,
        bool cascadeSave,
        bool cascadeDelete,
        bool insertWhenUpdateMissing,
        CancellationToken cancellationToken
    )
    {
        if (!HasChanges(entity, cascadeSave))
        {
            return 0;
        }

        var rows = 0;

        if (entity.IsRemoved)
        {
            // 削除は子（サブツリー）を先に削除してから自身を削除する（FK 整合）
            if (cascadeDelete)
            {
                foreach (var child in EnumerateCascadeChildren(entity))
                {
                    rows += await DeleteGraphAsync(
                        child,
                        connection,
                        transaction,
                        cancellationToken
                    );
                }
            }

            rows += await ExecuteAsync(
                entity,
                meta => meta.DeleteSql,
                static (meta, command, e) => meta.BindEntityKeyParameter(command, e),
                connection,
                transaction,
                cancellationToken
            );
            return rows;
        }

        // 追加・更新は自身を先に保存してから子へ進む（子 FK が親 PK を参照するため）
        if (entity.IsAdded)
        {
            rows += await ExecuteAsync(
                entity,
                meta => meta.InsertSql,
                static (meta, command, e) => meta.BindInsertParameters(command, e),
                connection,
                transaction,
                cancellationToken
            );
        }
        else if (entity.IsUpdated)
        {
            rows += await UpdateAsync(
                entity,
                connection,
                transaction,
                insertWhenUpdateMissing,
                cancellationToken
            );
        }

        if (cascadeSave)
        {
            foreach (var child in EnumerateCascadeChildren(entity))
            {
                rows += await SaveAsync(
                    child,
                    connection,
                    transaction,
                    cascadeSave,
                    cascadeDelete,
                    insertWhenUpdateMissing,
                    cancellationToken
                );
            }
        }

        return rows;
    }

    /// <summary>コミット後に保存済みエンティティを Unchanged に確定する</summary>
    public static void AcceptChanges(EntityBase entity, bool cascade)
    {
        if (entity.IsRemoved)
        {
            return;
        }

        entity.MarkUnchanged();

        if (cascade)
        {
            foreach (var child in EnumerateCascadeChildren(entity))
            {
                AcceptChanges(child, true);
            }
        }
    }

    /// <summary>サブツリーを子から順に削除する（状態に関わらず削除）</summary>
    private static async Task<int> DeleteGraphAsync(
        EntityBase entity,
        SqlConnection connection,
        SqlTransaction transaction,
        CancellationToken cancellationToken
    )
    {
        var rows = 0;

        foreach (var child in EnumerateCascadeChildren(entity))
        {
            rows += await DeleteGraphAsync(child, connection, transaction, cancellationToken);
        }

        rows += await ExecuteAsync(
            entity,
            meta => meta.DeleteSql,
            static (meta, command, e) => meta.BindEntityKeyParameter(command, e),
            connection,
            transaction,
            cancellationToken
        );
        return rows;
    }

    private static async Task<int> UpdateAsync(
        EntityBase entity,
        SqlConnection connection,
        SqlTransaction transaction,
        bool insertWhenUpdateMissing,
        CancellationToken cancellationToken
    )
    {
        var affected = await ExecuteAsync(
            entity,
            meta => meta.UpdateSql,
            static (meta, command, e) => meta.BindUpdateParameters(command, e),
            connection,
            transaction,
            cancellationToken
        );

        if (affected != 0)
        {
            return affected;
        }

        // 更新対象が存在しない（他ユーザーの削除等）。方針に応じて INSERT へ切替、または競合として通知する
        if (insertWhenUpdateMissing)
        {
            return await ExecuteAsync(
                entity,
                meta => meta.InsertSql,
                static (meta, command, e) => meta.BindInsertParameters(command, e),
                connection,
                transaction,
                cancellationToken
            );
        }

        var metadata = EntitySaveMetadata.For(entity.GetType());
        throw new SaveConflictException(
            $"更新対象のレコードが見つかりませんでした（{entity.GetType().Name}、キー {metadata.KeyProperty.GetValue(entity)}）。他のユーザーに削除された可能性があります。"
        );
    }

    private static async Task<int> ExecuteAsync(
        EntityBase entity,
        Func<EntitySaveMetadata, string> sqlSelector,
        Action<EntitySaveMetadata, SqlCommand, EntityBase> bind,
        SqlConnection connection,
        SqlTransaction transaction,
        CancellationToken cancellationToken
    )
    {
        var metadata = EntitySaveMetadata.For(entity.GetType());

        await using var command = new SqlCommand(sqlSelector(metadata), connection, transaction);
        bind(metadata, command, entity);
        return await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>カスケード対象の子エンティティを列挙する（null は除外）</summary>
    private static IEnumerable<EntityBase> EnumerateCascadeChildren(EntityBase entity)
    {
        foreach (var navigation in EntitySaveMetadata.For(entity.GetType()).CascadeNavigations)
        {
            var value = navigation.Property.GetValue(entity);

            if (value is null)
            {
                continue;
            }

            if (navigation.IsCollection)
            {
                if (value is IEnumerable<EntityBase> children)
                {
                    foreach (var child in children)
                    {
                        if (child is not null)
                        {
                            yield return child;
                        }
                    }
                }
            }
            else if (value is EntityBase child)
            {
                yield return child;
            }
        }
    }
}
