using System.IO;
using System.Linq;
using System.Text.Json;
using AwesomeAssertions;
using QuickER.Cli;
using QuickER.CodeGen.CSharp;
using QuickER.Documents;
using QuickER.Model;
using CodeGenStrings = QuickER.CodeGen.CSharp.Resources.Strings;

namespace QuickER.Tests.Cli;

/// <summary>
/// <see cref="CodeGenToolSet"/>（MCP のコード生成ツール <c>generate_csharp</c> / <c>generate_ddl</c>）の
/// 実行デリゲートを直接叩いて挙動を検証するテストクラス。
/// </summary>
public class CodeGenToolSetTests
{
    /// <summary>ツールセットの実行デリゲート（ツール名・引数 JSON → 結果テキストと成否）</summary>
    private static readonly System.Func<string, string, (string Result, bool Success)> Execute =
        CodeGenToolSet.Create().Execute;

    /// <summary>一時フォルダに保存形式の ER 図 JSON を作成する（指定方言）</summary>
    private static (string file, string root) CreateDiagram(string targetDbms = "sqlite")
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "QuickERCodeGenTool",
            Guid.NewGuid().ToString("N")
        );
        Directory.CreateDirectory(root);
        var file = Path.Combine(root, "diagram.json");

        var document = new DiagramDocument { Schema = { TargetDbms = targetDbms } };
        var entity = new Entity { TableName = "Customer" };
        entity.Columns.Add(
            new Column
            {
                Name = "Id",
                DataType = "int",
                IsPrimaryKey = true,
                IsNullable = false,
            }
        );
        entity.Columns.Add(new Column { Name = "Name", DataType = "nvarchar(100)" });
        document.Schema.Entities.Add(entity);
        JsonStorageService.Save(file, document);

        return (file, root);
    }

    /// <summary>引数 JSON を組み立てる（file を含む）ヘルパー</summary>
    private static string Args(object obj) => JsonSerializer.Serialize(obj);

    /// <summary>generate_ddl は SQL ファイルを生成し、DDL ヘッダを含むことを検証する</summary>
    [Fact(DisplayName = "generate_ddl は SQL ファイルを生成しヘッダ行を含む")]
    public void GenerateDdl_WritesSqlFile()
    {
        var (file, root) = CreateDiagram("sqlite");
        var outFile = Path.Combine(root, "schema.sql");

        try
        {
            var (result, success) = Execute("generate_ddl", Args(new { file, out_file = outFile }));

            success.Should().BeTrue(result);
            File.Exists(outFile).Should().BeTrue();
            var sql = File.ReadAllText(outFile);
            sql.Should().Contain("-- DDL auto-generated by QuickER");
            sql.Should().Contain("Customer");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>generate_ddl は provider 省略時に図の TargetDbms を採用することを検証する（sqlserver 図なら SQL Server 方言）</summary>
    [Fact(DisplayName = "generate_ddl は provider 省略時に図の TargetDbms を採用する")]
    public void GenerateDdl_UsesDiagramTargetDbms_WhenProviderOmitted()
    {
        var (file, root) = CreateDiagram("sqlserver");
        var outFile = Path.Combine(root, "schema.sql");

        try
        {
            var (result, success) = Execute("generate_ddl", Args(new { file, out_file = outFile }));

            success.Should().BeTrue(result);
            // SQL Server 方言の識別子引用（[Customer]）が出ることで TargetDbms 採用を確認する
            var sql = File.ReadAllText(outFile);
            sql.Should().Contain("[Customer]");
            result.Should().Contain("sqlserver");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>generate_csharp は既定オプションで出力ディレクトリに .g.cs を生成することを検証する</summary>
    [Fact(DisplayName = "generate_csharp は既定オプションで .g.cs を生成する")]
    public void GenerateCSharp_WritesCode_WithDefaults()
    {
        var (file, root) = CreateDiagram("sqlite");
        var outDir = Path.Combine(root, "out");

        try
        {
            var (result, success) = Execute(
                "generate_csharp",
                Args(new { file, out_dir = outDir })
            );

            success.Should().BeTrue(result);
            var files = Directory.GetFiles(outDir, "*.g.cs");
            files.Should().NotBeEmpty();
            var code = string.Join("\n", files.Select(File.ReadAllText));
            code.Should().Contain("class Customer");
            // WriteResult の診断（生成ファイル一覧）が結果テキストへ含まれる
            result.Should().Contain(".g.cs");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>generate_csharp は config JSON（GenerateRepositories=true）を反映することを検証する</summary>
    [Fact(DisplayName = "generate_csharp は config JSON を反映する")]
    public void GenerateCSharp_AppliesConfigJson()
    {
        var (file, root) = CreateDiagram("sqlite");
        var outDir = Path.Combine(root, "out");
        var configPath = Path.Combine(root, "quicker.json");
        File.WriteAllText(configPath, """{ "GenerateRepositories": true }""");

        try
        {
            var (result, success) = Execute(
                "generate_csharp",
                Args(
                    new
                    {
                        file,
                        out_dir = outDir,
                        config = configPath,
                    }
                )
            );

            success.Should().BeTrue(result);
            var code = string.Join(
                "\n",
                Directory.GetFiles(outDir, "*.g.cs").Select(File.ReadAllText)
            );
            // sqlite 図＋GenerateRepositories で QuickER 版 Repository（ADO=Microsoft.Data.Sqlite）が出る
            code.Should().Contain("Microsoft.Data.Sqlite");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>
    /// QuickER 版 Repository を持たない 3 方言（postgresql / mysql / oracle）の図でも、provider 引数を
    /// 省略した <c>generate_csharp</c> が成功することを検証する。
    /// </summary>
    /// <remarks>
    /// provider 省略時は <c>ResolveProviderArg</c> が図の <see cref="ErDiagram.TargetDbms"/> を採り、
    /// その方言名が Repository 方言として焼き込まれる。Repository 非生成なら未対応方言でも生成が
    /// 通ること（＝既定 sqlserver へのフォールバックが効いていること）を MCP 側入口で固定する。
    /// </remarks>
    [Theory(
        DisplayName = "generate_csharp は provider 省略でも 3 方言（Repository 未対応）で生成できる"
    )]
    [InlineData("postgresql")]
    [InlineData("mysql")]
    [InlineData("oracle")]
    public void GenerateCSharp_UnsupportedRepositoryDialect_SucceedsWithoutRepositories(
        string targetDbms
    )
    {
        var (file, root) = CreateDiagram(targetDbms);
        var outDir = Path.Combine(root, "out");

        try
        {
            var (result, success) = Execute(
                "generate_csharp",
                Args(new { file, out_dir = outDir })
            );

            success.Should().BeTrue(result);
            Directory.GetFiles(outDir, "*.g.cs").Should().NotBeEmpty();
            result.Should().Contain(targetDbms);
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>
    /// Repository 未対応方言の図で <c>GenerateRepositories=true</c> を指定すると、対応方言を列挙した
    /// 専用メッセージ付きで失敗することを検証する。
    /// </summary>
    /// <remarks>
    /// 設定検証エラー（生成前）は診断バッファへ乗らないため、<c>generate_csharp</c> は
    /// <c>RepositoryDialectUnsupportedException</c> 専用の catch で「C# code generation failed:」を前置する。
    /// この catch を外すと総括 catch（<c>Error: …</c>）に拾われて前置が消えるため、前置と本文の両方を固定する。
    /// </remarks>
    [Fact(
        DisplayName = "generate_csharp は Repository 未対応方言＋GenerateRepositories=true で失敗する"
    )]
    public void GenerateCSharp_UnsupportedRepositoryDialect_WithRepositories_ReturnsError()
    {
        var (file, root) = CreateDiagram("postgresql");
        var outDir = Path.Combine(root, "out");
        var configPath = Path.Combine(root, "quicker.json");
        File.WriteAllText(configPath, """{ "GenerateRepositories": true }""");

        try
        {
            var (result, success) = Execute(
                "generate_csharp",
                Args(
                    new
                    {
                        file,
                        out_dir = outDir,
                        config = configPath,
                    }
                )
            );

            success.Should().BeFalse(result);
            result.Should().Contain("C# code generation failed:");
            result
                .Should()
                .Contain(
                    string.Format(
                        CodeGenStrings.CodeGen_Error_UnsupportedRepositoryDialect,
                        "postgresql",
                        string.Join(", ", CodeGenerationOptions.SupportedRepositoryDialects)
                    )
                );
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>Repository 未対応方言（postgresql）でも generate_ddl が DDL を出力することを検証する</summary>
    [Fact(DisplayName = "generate_ddl は postgresql 図でも DDL を出力する")]
    public void GenerateDdl_PostgreSql_WritesSqlFile()
    {
        var (file, root) = CreateDiagram("postgresql");
        var outFile = Path.Combine(root, "schema.sql");

        try
        {
            var (result, success) = Execute("generate_ddl", Args(new { file, out_file = outFile }));

            success.Should().BeTrue(result);
            var sql = File.ReadAllText(outFile);
            sql.Should().Contain("-- DDL auto-generated by QuickER");
            // PostgreSQL 方言の識別子引用（"Customer"）が出ることで TargetDbms 採用を確認する
            sql.Should().Contain("\"Customer\"");
            result.Should().Contain("postgresql");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>存在しない図ファイルはエラー（成否 false）になることを検証する</summary>
    [Fact(DisplayName = "図ファイル不在はエラーになる")]
    public void MissingDiagramFile_ReturnsError()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "QuickERCodeGenTool",
            Guid.NewGuid().ToString("N")
        );
        Directory.CreateDirectory(root);
        var file = Path.Combine(root, "nope.json");

        try
        {
            var (result, success) = Execute(
                "generate_ddl",
                Args(new { file, out_file = Path.Combine(root, "x.sql") })
            );

            success.Should().BeFalse();
            result.Should().Contain("not found");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>DiagramDocument でない JSON（Version/Schema を持たない）はエラーになることを検証する</summary>
    [Fact(DisplayName = "非 DiagramDocument JSON はエラーになる")]
    public void NonDiagramJson_ReturnsError()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "QuickERCodeGenTool",
            Guid.NewGuid().ToString("N")
        );
        Directory.CreateDirectory(root);
        var file = Path.Combine(root, "unrelated.json");
        File.WriteAllText(file, """{ "hello": "world" }""");

        try
        {
            var (result, success) = Execute(
                "generate_csharp",
                Args(new { file, out_dir = Path.Combine(root, "out") })
            );

            success.Should().BeFalse();
            result.Should().Contain("not a DiagramDocument");
        }
        finally
        {
            Cleanup(root);
        }
    }

    /// <summary>未対応 provider 名を明示指定するとエラーになることを検証する</summary>
    [Fact(DisplayName = "未対応 provider 指定はエラーになる")]
    public void UnknownProvider_ReturnsError()
    {
        var (file, root) = CreateDiagram("sqlite");

        try
        {
            var (result, success) = Execute(
                "generate_ddl",
                Args(
                    new
                    {
                        file,
                        out_file = Path.Combine(root, "x.sql"),
                        provider = "no_such_provider",
                    }
                )
            );

            success.Should().BeFalse();
            result.Should().NotBeNullOrWhiteSpace();
        }
        finally
        {
            Cleanup(root);
        }
    }

    private static void Cleanup(string root)
    {
        if (Directory.Exists(root))
        {
            Directory.Delete(root, recursive: true);
        }
    }
}
