-- DDL auto-generated by QuickER
-- Generated at: 2026-07-21 00:31:59

-- customers: Customers. Master data of the purchasers who place orders
CREATE TABLE "customers" (
    "customer_id" int NOT NULL,
    -- customer_id: Customer ID (primary key; assigned by the application)
    "name" nvarchar(50) NOT NULL,
    -- name: Customer name
    "email" nvarchar(100) NULL,
    -- email: Contact email address (optional)
    CONSTRAINT "PK_customers" PRIMARY KEY ("customer_id")
);

-- products: Product master. Defines the products available for sale
CREATE TABLE "products" (
    "product_id" int NOT NULL,
    -- product_id: Product ID (primary key; assigned by the application)
    "name" nvarchar(50) NOT NULL,
    -- name: Product name
    "unit_price" decimal(10,2) NOT NULL,
    -- unit_price: Unit sales price in the product master
    CONSTRAINT "PK_products" PRIMARY KEY ("product_id")
);

-- orders: Order header. Represents a single order placed by one customer
CREATE TABLE "orders" (
    "order_id" int NOT NULL,
    -- order_id: Order ID (primary key; assigned by the application)
    "customer_id" int NOT NULL,
    -- customer_id: ID of the ordering customer (foreign key to customers)
    "ordered_at" datetime2 NOT NULL,
    -- ordered_at: Date and time the order was placed
    "memo" nvarchar(100) NULL,
    -- memo: Memo attached to the order (optional)
    CONSTRAINT "PK_orders" PRIMARY KEY ("order_id"),
    CONSTRAINT "FK_orders_customers" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON DELETE CASCADE
);

-- order_lines: Order lines. Detail rows linking orders and products many-to-many
CREATE TABLE "order_lines" (
    "order_line_id" int NOT NULL,
    -- order_line_id: Order line ID (primary key; assigned by the application)
    "order_id" int NOT NULL,
    -- order_id: ID of the parent order (foreign key to orders)
    "product_id" int NOT NULL,
    -- product_id: ID of the target product (foreign key to products)
    "quantity" int NOT NULL,
    -- quantity: Order quantity
    "unit_price" decimal(10,2) NOT NULL,
    -- unit_price: Unit price at order time (kept on the order line so product-master price revisions do not affect it)
    CONSTRAINT "PK_order_lines" PRIMARY KEY ("order_line_id"),
    CONSTRAINT "FK_order_lines_orders" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE,
    CONSTRAINT "FK_order_lines_products" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id")
);

