//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.CodeGen.UI.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.CodeGen.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string CodeGen_WindowTitle {
            get {
                return ResourceManager.GetString("CodeGen_WindowTitle", resourceCulture);
            }
        }

        public static string CodeGen_OutputMode {
            get {
                return ResourceManager.GetString("CodeGen_OutputMode", resourceCulture);
            }
        }

        public static string CodeGen_MergeSingleFile {
            get {
                return ResourceManager.GetString("CodeGen_MergeSingleFile", resourceCulture);
            }
        }

        public static string CodeGen_SplitByLayer {
            get {
                return ResourceManager.GetString("CodeGen_SplitByLayer", resourceCulture);
            }
        }

        public static string CodeGen_GenerationContent {
            get {
                return ResourceManager.GetString("CodeGen_GenerationContent", resourceCulture);
            }
        }

        public static string CodeGen_GenerationTarget {
            get {
                return ResourceManager.GetString("CodeGen_GenerationTarget", resourceCulture);
            }
        }

        public static string CodeGen_GenerateInMemory {
            get {
                return ResourceManager.GetString("CodeGen_GenerateInMemory", resourceCulture);
            }
        }

        public static string CodeGen_GenerateInMemoryToolTip {
            get {
                return ResourceManager.GetString("CodeGen_GenerateInMemoryToolTip", resourceCulture);
            }
        }

        public static string CodeGen_ValueObject {
            get {
                return ResourceManager.GetString("CodeGen_ValueObject", resourceCulture);
            }
        }

        public static string CodeGen_AllColumnsValueObject {
            get {
                return ResourceManager.GetString("CodeGen_AllColumnsValueObject", resourceCulture);
            }
        }

        public static string CodeGen_StringPkGuidKey {
            get {
                return ResourceManager.GetString("CodeGen_StringPkGuidKey", resourceCulture);
            }
        }

        public static string CodeGen_DbAccess {
            get {
                return ResourceManager.GetString("CodeGen_DbAccess", resourceCulture);
            }
        }

        public static string CodeGen_DbAccessNone {
            get {
                return ResourceManager.GetString("CodeGen_DbAccessNone", resourceCulture);
            }
        }

        public static string CodeGen_DbAccessEfCoreTooltip {
            get {
                return ResourceManager.GetString("CodeGen_DbAccessEfCoreTooltip", resourceCulture);
            }
        }

        public static string CodeGen_TargetDb {
            get {
                return ResourceManager.GetString("CodeGen_TargetDb", resourceCulture);
            }
        }

        public static string CodeGen_Runtime {
            get {
                return ResourceManager.GetString("CodeGen_Runtime", resourceCulture);
            }
        }

        public static string CodeGen_UseRuntimePackages {
            get {
                return ResourceManager.GetString("CodeGen_UseRuntimePackages", resourceCulture);
            }
        }

        public static string CodeGen_Documentation {
            get {
                return ResourceManager.GetString("CodeGen_Documentation", resourceCulture);
            }
        }

        public static string CodeGen_GenerateApiDocs {
            get {
                return ResourceManager.GetString("CodeGen_GenerateApiDocs", resourceCulture);
            }
        }

        public static string CodeGen_ApiDocsTooltip {
            get {
                return ResourceManager.GetString("CodeGen_ApiDocsTooltip", resourceCulture);
            }
        }

        public static string CodeGen_ExcludeUnboundedBinary {
            get {
                return ResourceManager.GetString("CodeGen_ExcludeUnboundedBinary", resourceCulture);
            }
        }

        public static string CodeGen_ExcludeUnboundedBinaryToolTip {
            get {
                return ResourceManager.GetString("CodeGen_ExcludeUnboundedBinaryToolTip", resourceCulture);
            }
        }

        public static string CodeGen_RemoteAccess {
            get {
                return ResourceManager.GetString("CodeGen_RemoteAccess", resourceCulture);
            }
        }

        public static string CodeGen_GenerateRemoteContracts {
            get {
                return ResourceManager.GetString("CodeGen_GenerateRemoteContracts", resourceCulture);
            }
        }

        public static string CodeGen_RemoteContractsToolTip {
            get {
                return ResourceManager.GetString("CodeGen_RemoteContractsToolTip", resourceCulture);
            }
        }

        public static string CodeGen_GenerateRemoteServices {
            get {
                return ResourceManager.GetString("CodeGen_GenerateRemoteServices", resourceCulture);
            }
        }

        public static string CodeGen_RemoteServicesToolTip {
            get {
                return ResourceManager.GetString("CodeGen_RemoteServicesToolTip", resourceCulture);
            }
        }

        public static string CodeGen_OutputDestination {
            get {
                return ResourceManager.GetString("CodeGen_OutputDestination", resourceCulture);
            }
        }

        public static string CodeGen_File {
            get {
                return ResourceManager.GetString("CodeGen_File", resourceCulture);
            }
        }

        public static string CodeGen_Browse {
            get {
                return ResourceManager.GetString("CodeGen_Browse", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceSection {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceSection", resourceCulture);
            }
        }

        public static string CodeGen_Folder {
            get {
                return ResourceManager.GetString("CodeGen_Folder", resourceCulture);
            }
        }

        public static string CodeGen_CategoryNamespace {
            get {
                return ResourceManager.GetString("CodeGen_CategoryNamespace", resourceCulture);
            }
        }

        public static string CodeGen_RootLabel {
            get {
                return ResourceManager.GetString("CodeGen_RootLabel", resourceCulture);
            }
        }

        public static string CodeGen_RuntimeBaseNote {
            get {
                return ResourceManager.GetString("CodeGen_RuntimeBaseNote", resourceCulture);
            }
        }

        public static string CodeGen_RuntimeTooltip {
            get {
                return ResourceManager.GetString("CodeGen_RuntimeTooltip", resourceCulture);
            }
        }

        public static string CodeGen_GeneratedFiles {
            get {
                return ResourceManager.GetString("CodeGen_GeneratedFiles", resourceCulture);
            }
        }

        public static string CodeGen_RestoreDefaults {
            get {
                return ResourceManager.GetString("CodeGen_RestoreDefaults", resourceCulture);
            }
        }

        public static string CodeGen_Generate {
            get {
                return ResourceManager.GetString("CodeGen_Generate", resourceCulture);
            }
        }

        public static string CodeGen_Cancel {
            get {
                return ResourceManager.GetString("CodeGen_Cancel", resourceCulture);
            }
        }

        public static string CodeGen_UseRuntimePackagesToolTip {
            get {
                return ResourceManager.GetString("CodeGen_UseRuntimePackagesToolTip", resourceCulture);
            }
        }

        public static string CodeGen_QuickErRepositoryToolTip {
            get {
                return ResourceManager.GetString("CodeGen_QuickErRepositoryToolTip", resourceCulture);
            }
        }

        public static string CodeGen_PickFolderTitle {
            get {
                return ResourceManager.GetString("CodeGen_PickFolderTitle", resourceCulture);
            }
        }

        public static string CodeGen_Status_NamespaceRequired {
            get {
                return ResourceManager.GetString("CodeGen_Status_NamespaceRequired", resourceCulture);
            }
        }

        public static string CodeGen_Status_NamespaceInvalid {
            get {
                return ResourceManager.GetString("CodeGen_Status_NamespaceInvalid", resourceCulture);
            }
        }

        public static string CodeGen_Status_TargetDbRequired {
            get {
                return ResourceManager.GetString("CodeGen_Status_TargetDbRequired", resourceCulture);
            }
        }

        public static string CodeGen_Status_InMemoryRuntimePackagesConflict {
            get {
                return ResourceManager.GetString("CodeGen_Status_InMemoryRuntimePackagesConflict", resourceCulture);
            }
        }

        public static string CodeGen_Status_NamespaceInvalidFormat {
            get {
                return ResourceManager.GetString("CodeGen_Status_NamespaceInvalidFormat", resourceCulture);
            }
        }

        public static string CodeGen_Status_OutputFolderRequired {
            get {
                return ResourceManager.GetString("CodeGen_Status_OutputFolderRequired", resourceCulture);
            }
        }

        public static string CodeGen_Status_OutputFileRequired {
            get {
                return ResourceManager.GetString("CodeGen_Status_OutputFileRequired", resourceCulture);
            }
        }

        public static string CodeGen_LoadSettings {
            get {
                return ResourceManager.GetString("CodeGen_LoadSettings", resourceCulture);
            }
        }

        public static string CodeGen_SaveSettings {
            get {
                return ResourceManager.GetString("CodeGen_SaveSettings", resourceCulture);
            }
        }

        public static string CodeGen_LoadSettingsToolTip {
            get {
                return ResourceManager.GetString("CodeGen_LoadSettingsToolTip", resourceCulture);
            }
        }

        public static string CodeGen_SaveSettingsToolTip {
            get {
                return ResourceManager.GetString("CodeGen_SaveSettingsToolTip", resourceCulture);
            }
        }

        public static string CodeGen_SettingsDialogTitle {
            get {
                return ResourceManager.GetString("CodeGen_SettingsDialogTitle", resourceCulture);
            }
        }

        public static string CodeGen_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("CodeGen_SettingsSavedMessage", resourceCulture);
            }
        }

        public static string CodeGen_SettingsSaveFailedMessage {
            get {
                return ResourceManager.GetString("CodeGen_SettingsSaveFailedMessage", resourceCulture);
            }
        }

        public static string CodeGen_SettingsLoadFailedMessage {
            get {
                return ResourceManager.GetString("CodeGen_SettingsLoadFailedMessage", resourceCulture);
            }
        }

        public static string CodeGen_ConfirmNamespaceFromFolder {
            get {
                return ResourceManager.GetString("CodeGen_ConfirmNamespaceFromFolder", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_Runtime {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_Runtime", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_Entity {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_Entity", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_EditModel {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_EditModel", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_Mapper {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_Mapper", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_Repository {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_Repository", resourceCulture);
            }
        }

        public static string CodeGen_NamespaceLabel_ValueObject {
            get {
                return ResourceManager.GetString("CodeGen_NamespaceLabel_ValueObject", resourceCulture);
            }
        }

        public static string QueryDialog_WindowTitle {
            get {
                return ResourceManager.GetString("QueryDialog_WindowTitle", resourceCulture);
            }
        }

        public static string QueryDialog_QueriesHeader {
            get {
                return ResourceManager.GetString("QueryDialog_QueriesHeader", resourceCulture);
            }
        }

        public static string QueryDialog_Add {
            get {
                return ResourceManager.GetString("QueryDialog_Add", resourceCulture);
            }
        }

        public static string QueryDialog_Remove {
            get {
                return ResourceManager.GetString("QueryDialog_Remove", resourceCulture);
            }
        }

        public static string QueryDialog_NoSelection {
            get {
                return ResourceManager.GetString("QueryDialog_NoSelection", resourceCulture);
            }
        }

        public static string QueryDialog_Entity {
            get {
                return ResourceManager.GetString("QueryDialog_Entity", resourceCulture);
            }
        }

        public static string QueryDialog_MethodName {
            get {
                return ResourceManager.GetString("QueryDialog_MethodName", resourceCulture);
            }
        }

        public static string QueryDialog_GeneratedNameLabel {
            get {
                return ResourceManager.GetString("QueryDialog_GeneratedNameLabel", resourceCulture);
            }
        }

        public static string QueryDialog_Description {
            get {
                return ResourceManager.GetString("QueryDialog_Description", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnShape {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnShape", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnList {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnList", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnSingle {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnSingle", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnCount {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnCount", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnScalar {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnScalar", resourceCulture);
            }
        }

        public static string QueryDialog_ReturnProjection {
            get {
                return ResourceManager.GetString("QueryDialog_ReturnProjection", resourceCulture);
            }
        }

        public static string QueryDialog_ScalarType {
            get {
                return ResourceManager.GetString("QueryDialog_ScalarType", resourceCulture);
            }
        }

        public static string QueryDialog_ScalarRequiresSqlOrManual {
            get {
                return ResourceManager.GetString("QueryDialog_ScalarRequiresSqlOrManual", resourceCulture);
            }
        }

        public static string QueryDialog_Parameters {
            get {
                return ResourceManager.GetString("QueryDialog_Parameters", resourceCulture);
            }
        }

        public static string QueryDialog_ParamIsList {
            get {
                return ResourceManager.GetString("QueryDialog_ParamIsList", resourceCulture);
            }
        }

        public static string QueryDialog_Condition {
            get {
                return ResourceManager.GetString("QueryDialog_Condition", resourceCulture);
            }
        }

        public static string QueryDialog_ConditionValid {
            get {
                return ResourceManager.GetString("QueryDialog_ConditionValid", resourceCulture);
            }
        }

        public static string QueryDialog_OrderBy {
            get {
                return ResourceManager.GetString("QueryDialog_OrderBy", resourceCulture);
            }
        }

        public static string QueryDialog_Descending {
            get {
                return ResourceManager.GetString("QueryDialog_Descending", resourceCulture);
            }
        }

        public static string QueryDialog_Paging {
            get {
                return ResourceManager.GetString("QueryDialog_Paging", resourceCulture);
            }
        }

        public static string QueryDialog_Implementation {
            get {
                return ResourceManager.GetString("QueryDialog_Implementation", resourceCulture);
            }
        }

        public static string QueryDialog_ImplDsl {
            get {
                return ResourceManager.GetString("QueryDialog_ImplDsl", resourceCulture);
            }
        }

        public static string QueryDialog_ImplSql {
            get {
                return ResourceManager.GetString("QueryDialog_ImplSql", resourceCulture);
            }
        }

        public static string QueryDialog_ImplManual {
            get {
                return ResourceManager.GetString("QueryDialog_ImplManual", resourceCulture);
            }
        }

        public static string QueryDialog_SqlServerSql {
            get {
                return ResourceManager.GetString("QueryDialog_SqlServerSql", resourceCulture);
            }
        }

        public static string QueryDialog_SqliteSql {
            get {
                return ResourceManager.GetString("QueryDialog_SqliteSql", resourceCulture);
            }
        }

        public static string QueryDialog_Projection {
            get {
                return ResourceManager.GetString("QueryDialog_Projection", resourceCulture);
            }
        }

        public static string QueryDialog_ResultTypeName {
            get {
                return ResourceManager.GetString("QueryDialog_ResultTypeName", resourceCulture);
            }
        }

        public static string QueryDialog_FieldSourceNone {
            get {
                return ResourceManager.GetString("QueryDialog_FieldSourceNone", resourceCulture);
            }
        }

        public static string QueryDialog_SignaturePreview {
            get {
                return ResourceManager.GetString("QueryDialog_SignaturePreview", resourceCulture);
            }
        }

        public static string QueryDialog_Ok {
            get {
                return ResourceManager.GetString("QueryDialog_Ok", resourceCulture);
            }
        }

        public static string QueryDialog_Cancel {
            get {
                return ResourceManager.GetString("QueryDialog_Cancel", resourceCulture);
            }
        }

        public static string QueryDialog_Status_NameRequired {
            get {
                return ResourceManager.GetString("QueryDialog_Status_NameRequired", resourceCulture);
            }
        }

        public static string QueryDialog_Status_EntityRequired {
            get {
                return ResourceManager.GetString("QueryDialog_Status_EntityRequired", resourceCulture);
            }
        }

        public static string QueryDialog_Status_ProjectionRequired {
            get {
                return ResourceManager.GetString("QueryDialog_Status_ProjectionRequired", resourceCulture);
            }
        }

        public static string QueryDialog_Status_ConditionInvalid {
            get {
                return ResourceManager.GetString("QueryDialog_Status_ConditionInvalid", resourceCulture);
            }
        }

        public static string QueryDialog_Status_DuplicateName {
            get {
                return ResourceManager.GetString("QueryDialog_Status_DuplicateName", resourceCulture);
            }
        }

        public static string QueryDialog_Status_RawSqlInvalid {
            get {
                return ResourceManager.GetString("QueryDialog_Status_RawSqlInvalid", resourceCulture);
            }
        }
    }
}
