namespace QuickER.AI.Mock;

/// <summary>Blazor Web App (.NET) ターゲットのプロファイル。csproj／README とプロンプトの Blazor 固有文面を提供する。</summary>
/// <remarks>
/// 技術構成は「Blazor Web App（.NET の統合テンプレート）・グローバル InteractiveServer レンダーモード・単一プロジェクト・
/// net10.0・追加パッケージ不要」（DI・ASP.NET Core ランタイムは共有フレームワークに同梱されるため、方言 ADO 以外の
/// PackageReference は要らない）。WPF 版（<see cref="WpfMockProjectTargetProfile"/>）と対称構造で、各フラグメントは
/// WPF 版の対応する一文と 1:1 に対応する。README とプロンプトの本文はすべて英語固定
/// （ヘッドレス実行の機械向け指示・生成物に同梱する規約ドキュメントは UI 言語に追従させない方針）。
/// </remarks>
internal sealed class BlazorMockProjectTargetProfile : MockProjectTargetProfile
{
    /// <inheritdoc />
    internal override MockProjectTarget Target => MockProjectTarget.Blazor;

    /// <inheritdoc />
    internal override string UiFileSearchPattern => "*.razor";

    // ── スキャフォールド差分 ──

    /// <inheritdoc />
    /// <remarks>Blazor Web App・net10.0（Microsoft.NET.Sdk.Web）。PackageReference は方言 ADO のみ（無ければ ItemGroup ごと省略）。</remarks>
    internal override string BuildCsproj(string rootNamespace, string? repositoryDialect)
    {
        var adoPackage = repositoryDialect switch
        {
            "sqlserver" =>
                "    <PackageReference Include=\"Microsoft.Data.SqlClient\" Version=\"7.0.1\" />\n",
            "sqlite" =>
                "    <PackageReference Include=\"Microsoft.Data.Sqlite\" Version=\"10.0.0\" />\n",
            _ => string.Empty,
        };

        // 方言 ADO パッケージが無ければ ItemGroup ごと省略する（空要素を出さない）。
        // DI・ASP.NET Core ランタイムは Microsoft.NET.Sdk.Web の共有フレームワークに含まれるため追加参照は不要。
        var packageItemGroup =
            adoPackage.Length == 0
                ? string.Empty
                : $"\n  <ItemGroup>\n{adoPackage}  </ItemGroup>\n";

        return $@"<Project Sdk=""Microsoft.NET.Sdk.Web"">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>{rootNamespace}</RootNamespace>
  </PropertyGroup>
{packageItemGroup}</Project>
";
    }

    /// <inheritdoc />
    /// <remarks>AI・人間の双方向けの規約ドキュメント（Blazor 実装規約・起動時 DI・実 DB 切り替え手順）。</remarks>
    internal override string BuildReadme(
        string projectName,
        string rootNamespace,
        string? repositoryDialect
    )
    {
        // DI 登録はエンジン別（AddGenerated{方言}Repositories）で統一されているため、方言別名で案内する
        var dialectSwitchGuide = repositoryDialect switch
        {
            "sqlserver" =>
                "3. To switch to a real database (SQL Server), replace `AddGeneratedInMemoryRepositories()` with "
                    + "`AddGeneratedSqlServerRepositories(connectionString)`.",
            "sqlite" =>
                "3. To switch to a real database (SQLite), replace `AddGeneratedInMemoryRepositories()` with "
                    + "`AddGeneratedSqliteRepositories(connectionString)`.",
            _ =>
                "3. To switch to a real database, regenerate the QuickER repositories for a supported dialect "
                    + "(SQL Server / SQLite) with QuickER, then replace `AddGeneratedInMemoryRepositories()` with "
                    + "the matching DI registration.",
        };

        return $@"# {projectName}

This is a Blazor Web App mock project that QuickER generated from a mock folder.
The data layer (under `Generated/`) is generated deterministically by QuickER, and the UI layer (Program.cs and
everything under Components) is implemented to match the design specification (several screens) under `design/mock/`.

## Project layout

This folder uses the standard Visual Studio layout. `{projectName}.sln` (the solution) sits at the root of the output
folder, and the project itself lives under the `{projectName}/` folder.

- `{projectName}.sln`: the solution file (at the root of the output folder). Running `dotnet build` here picks up the solution.
- `{projectName}/{projectName}.csproj`: the Blazor Web App (net10.0, Microsoft.NET.Sdk.Web) project file.
- `{projectName}/Generated/`: the data layer generated by QuickER (Entity / EditModel / Mapper / repository contracts and implementations / the in-memory implementation).
  **This folder holds auto-generated code, so never edit or delete it by hand (it is overwritten on regeneration).**
- `{projectName}/design/mock/`: the design specification of the screens to reproduce (the mock folder).
  - `design/mock/mock.json`: the manifest of screens, screen transitions and revisions. Read it first to get the whole picture.
  - `design/mock/*.html`: the design specification of one screen per file (screen structure and fields).
  - `design/mock/style.css`: the design system shared by every screen (shared CSS).
- Add the UI layer (Program.cs and everything under Components, such as App.razor / Routes.razor / layouts / screen pages) under the `{projectName}/` folder.

## Implementation rules

- Implement every screen as a Razor component with an `@page` route (under `Components/Pages/`).
- Run the UI in the **global InteractiveServer render mode** (declare `<Routes @rendermode=""InteractiveServer"" />` in `App.razor`
  so that interactive screens with buttons and forms work through server-side rendering).
- Receive the **`I{{Entity}}Repository`** contracts from `Generated/` through dependency injection
  (never `new` up a concrete repository directly).
- First read `design/mock/mock.json` for the screen list and the screen transitions, then reproduce the structure and
  fields of every `*.html` faithfully with Razor components (port the HTML structure and the class names of the design
  specification as literally as you can, and copy `design/mock/style.css` to `wwwroot/style.css` to reuse the shared
  design). Implement the transitions as page navigation with `NavLink` / `NavigationManager`.

## Dependency injection at startup

In `Program.cs`, register the Blazor Web App services and **`AddGeneratedInMemoryRepositories()`** from
`{rootNamespace}.Generated`, then map the components with the InteractiveServer render mode (this registers the
in-memory implementation seeded with sample data, so the app runs without a real database).

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents().AddInteractiveServerComponents();
builder.Services.AddGeneratedInMemoryRepositories(seedSampleData: true);

var app = builder.Build();
app.UseAntiforgery();
app.MapRazorComponents<App>().AddInteractiveServerRenderMode();
app.Run();
```

Start the app with `dotnet run` (open the localhost URL it prints in a browser).

## Switching to a real database

1. Generate the schema (DDL) of the target database with QuickER's DDL generation and apply it to the database.
2. Prepare a connection string.
{dialectSwitchGuide}
";
    }

    // ── エージェント型 system プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string SystemScaffoldNoun =>
        "the Blazor Web App project skeleton and the data-layer code";

    /// <inheritdoc />
    internal override string SystemScreenReproductionRule =>
        "Reproduce the structure and fields of every screen faithfully with Blazor Razor components, and implement the transitions from the manifest as page navigation (routing) (port the HTML structure and the class names of the design specification as literally as you can, and copy style.css to wwwroot/style.css to reuse the shared design).";

    /// <inheritdoc />
    internal override string SystemUiFrameworkRules =>
        "- Implement the UI as a Blazor Web App in the global InteractiveServer render mode. Declare `<Routes @rendermode=\"InteractiveServer\" />` in App.razor so that interactive screens (buttons and forms) work through server-side rendering.\r\n"
        + "- Every screen must be defined as a Razor component (.razor) with an `@page` route. Hand-building a RenderTreeBuilder / RenderFragment from C# code alone is forbidden.";

    /// <inheritdoc />
    internal override string SystemWorkflowSteps(string projectName) =>
        $"- Add the UI-layer sources (Program.cs, Components/, wwwroot/) under the {projectName}/ folder (the same place as the csproj).\r\n"
        + "- Configure dependency injection in Program.cs (AddRazorComponents().AddInteractiveServerComponents() and AddGeneratedInMemoryRepositories), then implement Components/App.razor, Routes.razor and the layout. App.razor is the root document, so it must contain `<!DOCTYPE html>`, the reference to wwwroot/style.css and the script tag for `_framework/blazor.web.js` (do not forget `app.UseAntiforgery()` either).\r\n"
        + $"- Reproduce every screen in {projectName}/{MockProjectScaffoldService.DesignFolderRelativePath}/mock.json (list, insert/edit and so on) as a Razor component with an `@page` route (under Components/Pages/), and implement the screen transitions declared in transitions as NavLink / NavigationManager page navigation.";

    // ── エージェント型 初回プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string UiLayerName => "Blazor UI layer";

    /// <inheritdoc />
    internal override string PromptImplementStep =>
        "Implement Program.cs, Components/App.razor, Routes.razor, the layout and the Razor component of every screen. Reproduce every screen as a page with an `@page` route (under Components/Pages/), and implement the transitions from mock.json as page navigation. Port the HTML structure of the design specification and style.css (copied into wwwroot) as literally as you can. ";

    /// <inheritdoc />
    internal override string PromptViewCriterion =>
        "Every screen exists as a Razor component (.razor) with an `@page` route and behaves interactively in the global InteractiveServer render mode.";

    // ── API キー型プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string ApiKeyUiFrameworkRules =>
        "- Implement the UI as a Blazor Web App in the global InteractiveServer render mode. Declare `<Routes @rendermode=\"InteractiveServer\" />` in App.razor so that interactive screens (buttons and forms) work through server-side rendering.\r\n"
        + "- Every screen must be defined as a Razor component (.razor) with an `@page` route. Hand-building a RenderTreeBuilder / RenderFragment from C# code alone is forbidden.";

    /// <inheritdoc />
    internal override string ApiKeyScreenReproductionRule =>
        "Port the structure and the class names of the design specification (HTML) of every screen into a Razor component as literally as you can, and implement the declared screen transitions as page navigation (routing) (the shared style.css is referenced as wwwroot/style.css).";

    /// <inheritdoc />
    internal override string ApiKeyCommonEmitInstructions(string projectName) =>
        $"- {projectName}/Program.cs (register AddRazorComponents().AddInteractiveServerComponents() and AddGeneratedInMemoryRepositories(seedSampleData: true), then call MapRazorComponents<App>().AddInteractiveServerRenderMode() after app.UseAntiforgery())\r\n"
        + $"- {projectName}/Components/App.razor (the root document containing `<!DOCTYPE html>`; it references wwwroot/style.css and contains `<Routes @rendermode=\"InteractiveServer\" />` and the script tag for `_framework/blazor.web.js`)\r\n"
        + $"- {projectName}/Components/Routes.razor, the layout ({projectName}/Components/Layout/MainLayout.razor) and {projectName}/Components/_Imports.razor\r\n"
        + $"- {projectName}/wwwroot/style.css (carrying the shared design system over as-is)\r\n"
        + "\r\n"
        + "The page of each individual screen comes in the following turns, one screen per turn. For now, build the foundation that starts up and can switch screens.";

    /// <inheritdoc />
    internal override string ApiKeyScreenInstruction(string projectName) =>
        $"Port the structure and the class names of the design specification (HTML) of this screen into a Razor component as literally as you can, and submit it as a page with an `@page` route using emit_file (under {projectName}/Components/Pages/). Implement the declared transitions as page navigation.";

    /// <inheritdoc />
    internal override string ApiKeyEmitPathExamples(string projectName) =>
        $"{projectName}/Components/Pages/OrderList.razor and {projectName}/wwwroot/style.css";
}
