namespace QuickER.AI.Mock;

/// <summary>WPF (.NET) ターゲットのプロファイル。csproj／README とプロンプトの WPF 固有文面を提供する。</summary>
/// <remarks>
/// ここで返すフラグメントは <see cref="MockProjectScaffoldService"/> と
/// <see cref="MockProjectPromptBuilder"/> が組み立てに使う WPF 固有文面の正本。
/// README とプロンプトの本文はすべて英語固定（ヘッドレス実行の機械向け指示・生成物に同梱する規約ドキュメントは
/// UI 言語に追従させない方針。CJK 混入は英語ガードテストが検知する）。
/// </remarks>
internal sealed class WpfMockProjectTargetProfile : MockProjectTargetProfile
{
    /// <inheritdoc />
    internal override MockProjectTarget Target => MockProjectTarget.Wpf;

    /// <inheritdoc />
    internal override string UiFileSearchPattern => "*.xaml";

    // ── スキャフォールド差分 ──

    /// <inheritdoc />
    /// <remarks>WPF・net10.0-windows・必要な PackageReference。</remarks>
    internal override string BuildCsproj(string rootNamespace, string? repositoryDialect)
    {
        var adoPackage = repositoryDialect switch
        {
            "sqlserver" =>
                "    <PackageReference Include=\"Microsoft.Data.SqlClient\" Version=\"7.0.1\" />\n",
            "sqlite" =>
                "    <PackageReference Include=\"Microsoft.Data.Sqlite\" Version=\"10.0.0\" />\n",
            _ => string.Empty,
        };

        return $@"<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>{rootNamespace}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=""CommunityToolkit.Mvvm"" Version=""8.4.2"" />
    <PackageReference Include=""Microsoft.Extensions.DependencyInjection"" Version=""10.0.0"" />
{adoPackage}  </ItemGroup>

</Project>
";
    }

    /// <inheritdoc />
    /// <remarks>AI・人間の双方向けの規約ドキュメント（WPF 実装規約・起動時 DI・実 DB 切り替え手順）。</remarks>
    internal override string BuildReadme(
        string projectName,
        string rootNamespace,
        string? repositoryDialect
    )
    {
        // DI 登録はエンジン別（AddGenerated{方言}Repositories）で統一されているため、方言別名で案内する
        var dialectSwitchGuide = repositoryDialect switch
        {
            "sqlserver" =>
                "3. To switch to a real database (SQL Server), replace `AddGeneratedInMemoryRepositories()` with "
                    + "`AddGeneratedSqlServerRepositories(connectionString)`.",
            "sqlite" =>
                "3. To switch to a real database (SQLite), replace `AddGeneratedInMemoryRepositories()` with "
                    + "`AddGeneratedSqliteRepositories(connectionString)`.",
            _ =>
                "3. To switch to a real database, regenerate the QuickER repositories for a supported dialect "
                    + "(SQL Server / SQLite) with QuickER, then replace `AddGeneratedInMemoryRepositories()` with "
                    + "the matching DI registration.",
        };

        return $@"# {projectName}

This is a WPF mock project that QuickER generated from a mock folder.
The data layer (under `Generated/`) is generated deterministically by QuickER, and the UI layer (App / MainWindow /
views and view models) is implemented to match the design specification (several screens) under `design/mock/`.

## Project layout

This folder uses the standard Visual Studio layout. `{projectName}.sln` (the solution) sits at the root of the output
folder, and the project itself lives under the `{projectName}/` folder.

- `{projectName}.sln`: the solution file (at the root of the output folder). Running `dotnet build` here picks up the solution.
- `{projectName}/{projectName}.csproj`: the WPF (net10.0-windows) project file.
- `{projectName}/Generated/`: the data layer generated by QuickER (Entity / EditModel / Mapper / repository contracts and implementations / the in-memory implementation).
  **This folder holds auto-generated code, so never edit or delete it by hand (it is overwritten on regeneration).**
- `{projectName}/design/mock/`: the design specification of the screens to reproduce (the mock folder).
  - `design/mock/mock.json`: the manifest of screens, screen transitions and revisions. Read it first to get the whole picture.
  - `design/mock/*.html`: the design specification of one screen per file (screen structure and fields).
  - `design/mock/style.css`: the design system shared by every screen (shared CSS).
- Add the UI layer (App / MainWindow / views and view models and so on) under the `{projectName}/` folder.

## Implementation rules

- Implement the UI with MVVM based on **CommunityToolkit.Mvvm** (`ObservableObject` / `RelayCommand` / `[ObservableProperty]`).
- Receive the **`I{{Entity}}Repository`** contracts from `Generated/` through dependency injection
  (never `new` up a concrete repository directly).
- First read `design/mock/mock.json` for the screen list and the screen transitions, then reproduce the structure and
  fields of every `*.html` faithfully with native WPF UI (rather than embedding the HTML as-is, rebuild it as WPF
  windows / pages / user controls, and implement the transitions from the manifest as navigation).

## Dependency injection at startup

In the startup of `App`, configure a `Microsoft.Extensions.DependencyInjection` container and call
**`AddGeneratedInMemoryRepositories()`** from `{rootNamespace}.Generated` (this registers the in-memory implementation
seeded with sample data, so the app runs without a real database).

```csharp
var services = new ServiceCollection();
services.AddGeneratedInMemoryRepositories(seedSampleData: true);
// Register the views and view models
var provider = services.BuildServiceProvider();
```

## Switching to a real database

1. Generate the schema (DDL) of the target database with QuickER's DDL generation and apply it to the database.
2. Prepare a connection string.
{dialectSwitchGuide}
";
    }

    // ── エージェント型 system プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string SystemScaffoldNoun =>
        "the WPF project skeleton and the data-layer code";

    /// <inheritdoc />
    internal override string SystemScreenReproductionRule =>
        "Reproduce the structure and fields of every screen faithfully in WPF, and implement the transitions from the manifest as navigation (rather than embedding the HTML as-is, rebuild it with native WPF UI).";

    /// <inheritdoc />
    internal override string SystemUiFrameworkRules =>
        "- Implement the UI with MVVM based on CommunityToolkit.Mvvm (ObservableObject / RelayCommand / ObservableProperty).\r\n"
        + "- Every screen must be defined as a XAML view (a .xaml Window / Page / UserControl plus its code-behind). Building the control tree from C# code alone (newing up controls and arranging them in code) is forbidden.";

    /// <inheritdoc />
    internal override string SystemWorkflowSteps(string projectName) =>
        $"- Add the UI-layer sources such as App.xaml / App.xaml.cs under the {projectName}/ folder (the same place as the csproj).\r\n"
        + "- Configure dependency injection in App.xaml / App.xaml.cs, then implement MainWindow together with the views and view models.\r\n"
        + $"- Reproduce every screen in {projectName}/{MockProjectScaffoldService.DesignFolderRelativePath}/mock.json (list, insert/edit and so on) as a WPF window / page / user control, and implement the screen transitions declared in transitions as navigation.";

    // ── エージェント型 初回プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string UiLayerName => "WPF UI layer";

    /// <inheritdoc />
    internal override string PromptImplementStep =>
        "Implement App.xaml(.cs), MainWindow and every view / view model with MVVM based on CommunityToolkit.Mvvm. Reproduce every screen as a WPF window / page / user control, and implement the transitions from mock.json as navigation. ";

    /// <inheritdoc />
    internal override string PromptViewCriterion =>
        "Every screen exists as a XAML view (.xaml) and is paired with a matching ViewModel (CommunityToolkit.Mvvm).";

    // ── API キー型プロンプトのターゲット差分 ──

    /// <inheritdoc />
    internal override string ApiKeyUiFrameworkRules =>
        "- Implement the UI with MVVM based on CommunityToolkit.Mvvm (ObservableObject / RelayCommand / [ObservableProperty]).\r\n"
        + "- Every screen must be defined as a XAML view (a .xaml Window / Page / UserControl plus its code-behind). Building the control tree from C# code alone (newing up controls and arranging them in code) is forbidden.";

    /// <inheritdoc />
    internal override string ApiKeyScreenReproductionRule =>
        "Reproduce the design specification (HTML) of every screen faithfully with native WPF UI, and implement the declared screen transitions as navigation (never embed the HTML as-is).";

    /// <inheritdoc />
    internal override string ApiKeyCommonEmitInstructions(string projectName) =>
        $"- {projectName}/App.xaml and {projectName}/App.xaml.cs (configure dependency injection with Microsoft.Extensions.DependencyInjection, register AddGeneratedInMemoryRepositories(seedSampleData: true) and show the startup window)\r\n"
        + $"- {projectName}/MainWindow.xaml and {projectName}/MainWindow.xaml.cs (the shell that switches screens) together with the navigation skeleton\r\n"
        + "- Any infrastructure shared by the screens (a navigation service, a ViewModelBase and so on, if you need them)\r\n"
        + "\r\n"
        + "The view and view model of each individual screen come in the following turns, one screen per turn. For now, build the foundation that starts up and can switch screens.";

    /// <inheritdoc />
    internal override string ApiKeyScreenInstruction(string projectName) =>
        $"Reproduce the design specification (HTML) of this screen faithfully with native WPF UI, and submit the view and the view model with emit_file (under the {projectName}/ folder). Implement the declared transitions as navigation.";

    /// <inheritdoc />
    internal override string ApiKeyEmitPathExamples(string projectName) =>
        $"{projectName}/App.xaml and {projectName}/Views/OrderListView.xaml";
}
