using System.Security.Cryptography;
using System.Text;

namespace QuickER.CodeGen.CSharp;

/// <summary>
/// 生成コード（<c>.g.cs</c>）のヘッダーへ刻む版の行・内容ハッシュの行を扱う単一の正本。
/// </summary>
/// <remarks>
/// <para>
/// 内容ハッシュは「生成後に手で編集されたか」を再生成の上書き前に検出するためのもので、改ざん防止ではない
/// （誰でも計算し直せる）。ハッシュは本文をそのまま計算せず、次の正規化を通した結果の SHA-256 を採る。
/// 整形ツールや改行コードの自動変換で内容が変わったと誤判定しないための規則で、生成側（<see cref="Stamp"/>）と
/// 照合側（<see cref="Verify"/>）は必ずこのクラスの同じ実装を通る。
/// </para>
/// <list type="number">
/// <item>先頭のコメント行の塊（コメント行と空白だけの行が続く範囲）にある版の行・内容ハッシュの行を除く（ハッシュが自分自身を含まない・版を上げただけでは変わらない）</item>
/// <item>BOM と空白文字（<see cref="char.IsWhiteSpace(char)"/>）をすべて除く（改行コード・インデント・改行位置の差を吸収する）</item>
/// <item><c>}</c> / <c>)</c> / <c>]</c> の直前の <c>,</c> を除く（整形ツールが複数行の初期化子へ付ける末尾カンマを吸収する）</item>
/// </list>
/// <para>
/// 帰結として、空白だけを変える編集（文字列リテラル内の空白を含む）と、<c>[,]</c> のような
/// 閉じ括弧直前のカンマだけを変える編集は検出できない。
/// </para>
/// </remarks>
public static class GeneratedContentHash
{
    /// <summary>生成ファイルの先頭行（ヘッダーの位置を決める目印）</summary>
    public const string AutoGeneratedLine = "// <auto-generated />";

    /// <summary>版の行の接頭辞（直後に版の文字列が続く）</summary>
    public const string VersionLinePrefix = "// Generated by QuickER ";

    /// <summary>内容ハッシュの行の接頭辞（直後に小文字 16 進 64 桁が続く）</summary>
    public const string HashLinePrefix = "// Content hash: sha256:";

    /// <summary>
    /// 生成コードの先頭行（<see cref="AutoGeneratedLine"/>）の直後へ、版の行と内容ハッシュの行を挿入する。
    /// </summary>
    /// <param name="content">メタ行を持たない生成コード</param>
    /// <param name="version">版の文字列（例: <c>0.2.0</c>）</param>
    /// <returns>メタ行を挿入した生成コード。改行コードは先頭行の改行に合わせる</returns>
    /// <exception cref="ArgumentException">先頭行が <see cref="AutoGeneratedLine"/> でない場合</exception>
    public static string Stamp(string content, string version)
    {
        ArgumentNullException.ThrowIfNull(content);
        ArgumentException.ThrowIfNullOrWhiteSpace(version);

        if (!content.StartsWith(AutoGeneratedLine, StringComparison.Ordinal))
        {
            throw new ArgumentException(
                $"Generated content must start with '{AutoGeneratedLine}'.",
                nameof(content)
            );
        }

        // 先頭行の改行コードをそのまま使う（テンプレートの改行を崩さない）
        var afterFirstLine = AutoGeneratedLine.Length;
        var newLine = content.AsSpan(afterFirstLine).StartsWith("\r\n") ? "\r\n" : "\n";

        // メタ行はハッシュの対象外なので、挿入前の本文から計算した値が挿入後の照合でもそのまま一致する
        var hash = Compute(content);

        return content[..afterFirstLine]
            + newLine
            + VersionLinePrefix
            + version
            + newLine
            + HashLinePrefix
            + hash
            + content[afterFirstLine..];
    }

    /// <summary>
    /// 既存の生成ファイルの内容が、刻まれた内容ハッシュと一致するかを照合する。
    /// </summary>
    /// <param name="content">ファイルの内容</param>
    /// <returns>照合結果</returns>
    public static GeneratedContentHashStatus Verify(string content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var recorded = FindRecordedHash(content);

        if (recorded is null)
        {
            return GeneratedContentHashStatus.NotStamped;
        }

        // 行が壊れていて 16 進 64 桁として読めない場合も「一致しない」＝安全側（上書き前に確認させる）
        return string.Equals(recorded, Compute(content), StringComparison.OrdinalIgnoreCase)
            ? GeneratedContentHashStatus.Unchanged
            : GeneratedContentHashStatus.Modified;
    }

    /// <summary>正規化した本文の SHA-256 を小文字 16 進 64 桁で返す</summary>
    /// <param name="content">生成コード（メタ行の有無は問わない）</param>
    public static string Compute(string content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var bytes = Encoding.UTF8.GetBytes(Normalize(content));
        return Convert.ToHexStringLower(SHA256.HashData(bytes));
    }

    /// <summary>
    /// ハッシュの入力となる正規化本文を返す（規則はクラスの remarks を参照）。
    /// </summary>
    /// <param name="content">生成コード</param>
    public static string Normalize(string content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var stripped = new StringBuilder(content.Length);
        var inLeadingComments = true;

        foreach (var line in EnumerateLines(content))
        {
            // 先頭のコメント行の塊にあるメタ行だけを除く。
            // 本文中に同じ文字列の行があっても除かない（手編集の検出範囲を狭めない）
            if (inLeadingComments)
            {
                var trimmed = TrimLine(line);

                if (!IsLeadingBlockLine(trimmed))
                {
                    inLeadingComments = false;
                }
                else if (IsMetaLine(trimmed))
                {
                    continue;
                }
            }

            foreach (var c in line)
            {
                if (!char.IsWhiteSpace(c) && c != '\uFEFF')
                {
                    stripped.Append(c);
                }
            }
        }

        // 閉じ括弧直前のカンマ（整形ツールが付け外しする末尾カンマ）を除く
        var normalized = new StringBuilder(stripped.Length);

        for (var i = 0; i < stripped.Length; i++)
        {
            if (
                stripped[i] == ','
                && i + 1 < stripped.Length
                && stripped[i + 1] is '}' or ')' or ']'
            )
            {
                continue;
            }

            normalized.Append(stripped[i]);
        }

        return normalized.ToString();
    }

    /// <summary>先頭のコメント行の塊から、刻まれた内容ハッシュ（接頭辞の後ろ）を探す。無ければ null</summary>
    private static string? FindRecordedHash(string content)
    {
        foreach (var line in EnumerateLines(content))
        {
            var trimmed = TrimLine(line);

            if (!IsLeadingBlockLine(trimmed))
            {
                return null;
            }

            if (trimmed.StartsWith(HashLinePrefix, StringComparison.Ordinal))
            {
                return trimmed[HashLinePrefix.Length..].Trim();
            }
        }

        return null;
    }

    /// <summary>行の前後の空白と BOM を除く（先頭のコメント塊の判定用）</summary>
    private static string TrimLine(string line) => line.Trim().TrimStart('\uFEFF');

    /// <summary>
    /// 先頭のコメント塊に含まれる行か（<see cref="TrimLine"/> 済みの行で判定）。コメント行と空白だけの行が該当する。
    /// </summary>
    /// <remarks>
    /// <see cref="Normalize"/>（メタ行を除く範囲）と <see cref="FindRecordedHash"/>（ハッシュ行を探す範囲）が
    /// この 1 つの判定を共有する。空白だけの行で塊を打ち切ると、ヘッダーに空行を挟んだだけでハッシュ行を見失い
    /// （判定不能＝確認なしの上書きへ倒れる）、空白の変更を編集とみなさない規則とも食い違う。
    /// </remarks>
    private static bool IsLeadingBlockLine(string trimmed) =>
        trimmed.Length == 0 || trimmed.StartsWith("//", StringComparison.Ordinal);

    /// <summary>版の行・内容ハッシュの行か（前後の空白を除いた行で判定）</summary>
    private static bool IsMetaLine(ReadOnlySpan<char> trimmed) =>
        trimmed.StartsWith(VersionLinePrefix.TrimEnd(), StringComparison.Ordinal)
        || trimmed.StartsWith(HashLinePrefix, StringComparison.Ordinal);

    /// <summary>CRLF / CR / LF のいずれでも行に分ける（改行文字自体は返さない）</summary>
    private static IEnumerable<string> EnumerateLines(string content)
    {
        using var reader = new StringReader(content);

        while (reader.ReadLine() is { } line)
        {
            yield return line;
        }
    }
}

/// <summary><see cref="GeneratedContentHash.Verify"/> の照合結果</summary>
public enum GeneratedContentHashStatus
{
    /// <summary>内容ハッシュの行が無い（この機能より前の生成物・ヘッダーを消されたファイル）。判定しない</summary>
    NotStamped,

    /// <summary>刻まれたハッシュと一致する（生成後に内容が変わっていない）</summary>
    Unchanged,

    /// <summary>刻まれたハッシュと一致しない（生成後に手で編集された）</summary>
    Modified,
}
