using Scriban;

namespace ERDesigner.Generator;

/// <summary>生成モデルを Scriban テンプレートで C# ソースコードへレンダリングするレンダラー</summary>
internal sealed class ScribanCSharpRenderer
{
    /// <summary>Entity / EditModel / Mapper / Repository を一括出力する Scriban テンプレート本文</summary>
    /// <remarks>インデントは半角スペース 4 つで統一する（タブは使用しない）</remarks>
    private const string TemplateText = """
        // <auto-generated />
        #nullable enable

        {{ for u in usings }}using {{ u }};
        {{ end }}
        namespace {{ namespace_name }};

        {{~ if emit_nav_ref_attr ~}}
        /// <summary>Entity ナビゲーションへ参照テーブル・カラム情報を付加する独自属性</summary>
        [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
        public sealed class NavigationReferenceAttribute : Attribute
        {
            /// <summary>参照される側（principal）のテーブル名</summary>
            public string PrincipalTable { get; }

            /// <summary>参照される側（principal）のカラム名</summary>
            public string PrincipalColumn { get; }

            /// <summary>外部キーを持つ側（dependent）のテーブル名</summary>
            public string DependentTable { get; }

            /// <summary>外部キーを持つ側（dependent）のカラム名</summary>
            public string DependentColumn { get; }

            /// <summary>コレクション（1 対多）ナビゲーションかどうか</summary>
            public bool IsCollection { get; }

            /// <summary>参照テーブル・カラム情報を受け取り初期化する</summary>
            public NavigationReferenceAttribute(string principalTable, string principalColumn, string dependentTable, string dependentColumn, bool isCollection)
            {
                PrincipalTable = principalTable;
                PrincipalColumn = principalColumn;
                DependentTable = dependentTable;
                DependentColumn = dependentColumn;
                IsCollection = isCollection;
            }
        }
        {{ end }}
        {{~ for item in entity_classes ~}}
        {{ if !for.first }}

        {{ end }}/// <summary>{{ item.table_name }} テーブルに対応するエンティティ</summary>
        {{ if include_data_annotations }}[Table("{{ item.table_name }}")]
        {{ end }}public partial class {{ item.class_name }}
        {
        {{ for property in item.properties }}    /// <summary>{{ property.column_name }} 列に対応するプロパティ</summary>
        {{ if include_data_annotations && property.is_primary_key }}    [Key]
        {{ end }}{{ if include_data_annotations }}    [Column("{{ property.column_name }}")]
        {{ end }}{{ if include_data_annotations && !property.is_nullable && property.is_reference_type }}    [Required]
        {{ end }}{{ if include_data_annotations && property.max_length }}    [MaxLength({{ property.max_length }})]
        {{ end }}    public {{ property.type_name }} {{ property.property_name }} { get; set; }{{ property.initializer }}

        {{ end }}{{ for navigation in item.navigations }}    /// <summary>{{ navigation.property_name }} ナビゲーションプロパティ</summary>
        {{ if include_json_ignore_on_parent_navigation && navigation.is_parent_reference }}    [JsonIgnore]
        {{ end }}    [NavigationReference("{{ navigation.principal_table_name }}", "{{ navigation.principal_column_name }}", "{{ navigation.dependent_table_name }}", "{{ navigation.dependent_column_name }}", {{ navigation.is_collection }})]
            public {{ navigation.display_type_name }} {{ navigation.property_name }} { get; set; }{{ navigation.initializer }}

        {{ end }}}
        {{~ end ~}}

        {{~ if edit_model_classes.size > 0 ~}}
        /// <summary>EditModel 共通の変更通知・エラー管理・補助処理を提供する基底クラス</summary>
        public abstract partial class EditModelBase : INotifyPropertyChanged, INotifyDataErrorInfo
        {
            /// <summary>プロパティ名ごとのエラーメッセージ一覧</summary>
            private readonly Dictionary<string, List<string>> _errors = new();

            /// <summary>プロパティ値の変更通知</summary>
            public event PropertyChangedEventHandler? PropertyChanged;

            /// <summary>入力エラーの変更通知</summary>
            public event EventHandler<DataErrorsChangedEventArgs>? ErrorsChanged;

            /// <summary>入力エラーを保持しているかどうか</summary>
            public bool HasErrors => _errors.Count > 0;

            /// <summary>リバート処理中かどうか</summary>
            protected bool IsReverting { get; private set; }

            /// <summary>指定プロパティの変更通知を発行する</summary>
            protected void OnPropertyChanged(string propertyName) =>
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

            /// <summary>値が変化した場合のみ代入し変更通知を発行する共通ヘルパー</summary>
            protected bool SetProperty<T>(ref T field, T value, string propertyName)
            {
                if (EqualityComparer<T>.Default.Equals(field, value))
                {
                    return false;
                }

                field = value;
                OnPropertyChanged(propertyName);
                return true;
            }

            /// <summary>指定プロパティ（null で全件）のエラー一覧を取得する</summary>
            public System.Collections.IEnumerable GetErrors(string? propertyName)
            {
                if (string.IsNullOrEmpty(propertyName))
                {
                    return _errors.Values.SelectMany(e => e);
                }

                return _errors.TryGetValue(propertyName, out var list) ? list : Enumerable.Empty<string>();
            }

            /// <summary>指定プロパティのエラーを設定する（null 指定でクリア）</summary>
            protected void SetError(string propertyName, string? error)
            {
                if (error is null)
                {
                    ClearErrors(propertyName);
                    return;
                }

                _errors[propertyName] = [error];
                OnErrorsChanged(propertyName);
            }

            /// <summary>指定プロパティのエラーをクリアする</summary>
            protected void ClearErrors(string propertyName)
            {
                if (_errors.Remove(propertyName))
                {
                    OnErrorsChanged(propertyName);
                }
            }

            /// <summary>入力エラーの変更通知を発行する</summary>
            protected void OnErrorsChanged(string propertyName) =>
                ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));

            /// <summary>リバート中フラグを立てたうえで処理を実行する</summary>
            protected void ExecuteRevert(Action action)
            {
                IsReverting = true;

                try
                {
                    action();
                }
                finally
                {
                    IsReverting = false;
                }
            }

            /// <summary>バインディング値の変換エラーメッセージを構築する（派生クラスで override し方針を差し替え可能）</summary>
            protected virtual string BuildParseErrorMessage(string propertyName, string inputValue, string typeName) =>
                $"'{inputValue}' は {typeName} に変換できません。";

            /// <summary>変換エラーメッセージを解決する（BuildParseErrorMessage の後に CustomizeParseErrorMessage で微調整）</summary>
            protected string ResolveParseErrorMessage(string propertyName, string inputValue, string typeName)
            {
                var message = BuildParseErrorMessage(propertyName, inputValue, typeName);
                CustomizeParseErrorMessage(propertyName, inputValue, typeName, ref message);
                return message;
            }

            /// <summary>プロパティ単位のエラーメッセージ微調整用 partial メソッド（別ファイルの partial 実装で差し替え）</summary>
            partial void CustomizeParseErrorMessage(
                string propertyName,
                string inputValue,
                string typeName,
                ref string message);
        }
        {{ end }}
        {{~ for item in edit_model_classes ~}}
        {{ if !for.first }}

        {{ end }}/// <summary>{{ item.table_name }} テーブルの画面編集用モデル</summary>
        public partial class {{ item.class_name }} : EditModelBase
        {
            // 各列につき「確定値」「画面入力文字列」「変換エラー」の 3 種を保持する
        {{ for p in item.properties }}{{ if p.field_initializer != "" }}    /// <summary>{{ p.property_name }} の確定値</summary>
            private {{ p.type_name }} {{ p.field_name }} = {{ p.field_initializer }};
        {{ else }}    /// <summary>{{ p.property_name }} の確定値</summary>
            private {{ p.type_name }} {{ p.field_name }};
        {{ end }}    /// <summary>{{ p.property_name }} の画面入力文字列</summary>
            private string {{ p.binding_field_name }} = {{ p.binding_field_initializer }};
        {{ if p.needs_parse }}    /// <summary>{{ p.property_name }} の変換エラー</summary>
            private string? {{ p.error_field_name }};
        {{ end }}
            /// <summary>{{ p.property_name }} の確定値（外部からは読み取り専用）</summary>
            public {{ p.type_name }} {{ p.property_name }}
            {
                get => {{ p.field_name }};
                private set
                {
                    if (EqualityComparer<{{ p.type_name }}>.Default.Equals({{ p.field_name }}, value))
                    {
                        return;
                    }

                    var oldValue = {{ p.field_name }};
                    On{{ p.property_name }}Changing(value);
                    On{{ p.property_name }}Changing(oldValue, value);
                    {{ p.field_name }} = value;
                    On{{ p.property_name }}Changed(value);
                    On{{ p.property_name }}Changed(oldValue, value);
                    OnPropertyChanged(nameof({{ p.property_name }}));
                }
            }

            /// <summary>{{ p.property_name }} の確定値が変更される直前に呼ばれる（新値のみ。partial 実装で処理を追加）</summary>
            partial void On{{ p.property_name }}Changing({{ p.type_name }} value);

            /// <summary>{{ p.property_name }} の確定値が変更される直前に呼ばれる（旧値・新値。partial 実装で処理を追加）</summary>
            partial void On{{ p.property_name }}Changing({{ p.type_name }} oldValue, {{ p.type_name }} newValue);

            /// <summary>{{ p.property_name }} の確定値が変更された直後に呼ばれる（新値のみ。partial 実装で処理を追加）</summary>
            partial void On{{ p.property_name }}Changed({{ p.type_name }} value);

            /// <summary>{{ p.property_name }} の確定値が変更された直後に呼ばれる（旧値・新値。partial 実装で処理を追加）</summary>
            partial void On{{ p.property_name }}Changed({{ p.type_name }} oldValue, {{ p.type_name }} newValue);

            /// <summary>{{ p.property_name }} の画面入力用バインディング文字列（設定時に確定値へ変換）</summary>
            public string {{ p.binding_property_name }}
            {
                get => {{ p.binding_field_name }};
                set
                {
                    if (!SetProperty(ref {{ p.binding_field_name }}, value, nameof({{ p.binding_property_name }})))
                    {
                        return;
                    }

                    if (!IsReverting)
                    {
        {{ if p.needs_parse }}                if ({{ p.parse_type_name }}.TryParse(value, out var parsed))
                        {
                            {{ p.property_name }} = parsed;
                            {{ p.error_field_name }} = null;
                            SetError(nameof({{ p.binding_property_name }}), null);
                        }
                        else
                        {
                            {{ p.error_field_name }} = ResolveParseErrorMessage(nameof({{ p.binding_property_name }}), value, "{{ p.parse_type_name }}");
                            SetError(nameof({{ p.binding_property_name }}), {{ p.error_field_name }});
                        }
        {{ else if p.is_binary }}                if (string.IsNullOrEmpty(value))
                        {
                            {{ p.property_name }} = Array.Empty<byte>();
                            SetError(nameof({{ p.binding_property_name }}), null);
                        }
                        else
                        {
                            try
                            {
                                {{ p.property_name }} = Convert.FromBase64String(value);
                                SetError(nameof({{ p.binding_property_name }}), null);
                            }
                            catch (FormatException)
                            {
                                SetError(nameof({{ p.binding_property_name }}), ResolveParseErrorMessage(nameof({{ p.binding_property_name }}), value, "byte[]"));
                            }
                        }
        {{ else if p.is_nullable }}                if (string.IsNullOrEmpty(value))
                        {
                            {{ p.property_name }} = null;
                            SetError(nameof({{ p.binding_property_name }}), null);
                        }
                        else
                        {
                            {{ p.property_name }} = value;
                            SetError(nameof({{ p.binding_property_name }}), null);
                        }
        {{ else }}                {{ p.property_name }} = value;
                        SetError(nameof({{ p.binding_property_name }}), null);
        {{ end }}            }
                }
            }

        {{ end }}    // ---- navigation ----
        {{ for navigation in item.navigations }}    /// <summary>{{ navigation.property_name }} ナビゲーションプロパティ</summary>
            public {{ navigation.display_type_name }} {{ navigation.property_name }} { get; set; }{{ navigation.initializer }}

        {{ end }}    /// <summary>確定値をバインディング用プロパティへ書き戻しエラーをクリアする</summary>
            public void RevertInput()
            {
                ExecuteRevert(() =>
                {
        {{ for p in item.properties }}            {{ p.binding_property_name }} = {{ p.revert_binding_expression }};
        {{ if p.needs_parse }}            {{ p.error_field_name }} = null;
        {{ end }}            SetError(nameof({{ p.binding_property_name }}), null);
        {{ end }}        });
            }
        }
        {{~ end ~}}

        {{~ for mapper in mapper_classes ~}}
        {{ if !for.first }}

        {{ end }}/// <summary>{{ mapper.entity_class_name }} と {{ mapper.edit_model_class_name }} の相互変換</summary>
        public sealed class {{ mapper.class_name }}
        {
            /// <summary>{{ mapper.entity_class_name }} から {{ mapper.edit_model_class_name }} を生成する</summary>
            public {{ mapper.edit_model_class_name }} CommitToEditModel({{ mapper.entity_class_name }} entity)
            {
                var editModel = new {{ mapper.edit_model_class_name }}();
                LoadFrom(entity, editModel);
                return editModel;
            }

            /// <summary>{{ mapper.edit_model_class_name }} の確定値を {{ mapper.entity_class_name }} へ反映する</summary>
            public void CommitToEntity({{ mapper.edit_model_class_name }} editModel, {{ mapper.entity_class_name }} entity)
            {
        {{ for prop in mapper.scalar_properties }}{{ if prop.edit_model_is_nullable && prop.entity_type_name != prop.edit_model_type_name }}        entity.{{ prop.property_name }} = editModel.{{ prop.property_name }} ?? throw new InvalidOperationException("{{ prop.property_name }} が未入力です。");
        {{ else }}        entity.{{ prop.property_name }} = editModel.{{ prop.property_name }};
        {{ end }}{{ end }}    }

            /// <summary>{{ mapper.entity_class_name }} の値をバインディング経由で {{ mapper.edit_model_class_name }} へ読み込む</summary>
            private static void LoadFrom({{ mapper.entity_class_name }} entity, {{ mapper.edit_model_class_name }} editModel)
            {
                editModel.RevertInput();
        {{ for prop in mapper.scalar_properties }}        editModel.{{ prop.binding_property_name }} = {{ prop.load_binding_expression }};
        {{ end }}    }
        }
        {{~ end ~}}

        {{~ if repository_classes.size > 0 ~}}
        /// <summary>エンティティの CRUD 操作を提供するリポジトリ共通インターフェース</summary>
        public interface IRepository<TEntity, TKey>
            where TEntity : class, new()
        {
            /// <summary>主キーによる単一エンティティ取得（該当なしは null）</summary>
            Task<TEntity?> GetByIdAsync(TKey id, CancellationToken cancellationToken = default);

            /// <summary>全エンティティ取得</summary>
            Task<IReadOnlyList<TEntity>> GetAllAsync(CancellationToken cancellationToken = default);

            /// <summary>エンティティ追加</summary>
            Task InsertAsync(TEntity entity, CancellationToken cancellationToken = default);

            /// <summary>エンティティ更新（更新対象ありで true）</summary>
            Task<bool> UpdateAsync(TEntity entity, CancellationToken cancellationToken = default);

            /// <summary>主キーによるエンティティ削除（削除対象ありで true）</summary>
            Task<bool> DeleteAsync(TKey id, CancellationToken cancellationToken = default);
        }

        /// <summary>SQL Server 接続を生成するファクトリ</summary>
        public interface ISqlConnectionFactory
        {
            /// <summary>新しい SQL 接続を生成する</summary>
            SqlConnection CreateConnection();
        }

        /// <summary>接続文字列から SQL 接続を生成する既定実装</summary>
        public sealed class SqlConnectionFactory(string connectionString) : ISqlConnectionFactory
        {
            /// <summary>新しい SQL 接続を生成する</summary>
            public SqlConnection CreateConnection() => new(connectionString);
        }

        /// <summary>エンティティ型の属性からテーブル・カラム情報と CRUD 用 SQL を構築・保持するメタデータ</summary>
        /// <remarks>型ごとに 1 度だけ構築し静的フィールドで再利用する（リフレクションコスト削減）</remarks>
        internal sealed class SqlEntityMetadata<TEntity, TKey>
            where TEntity : class, new()
        {
            /// <summary>角括弧で囲んだテーブル名</summary>
            public required string TableName { get; init; }

            /// <summary>主キーに対応するプロパティ</summary>
            public required PropertyInfo KeyProperty { get; init; }

            /// <summary>主キーのカラム名</summary>
            public required string KeyColumnName { get; init; }

            /// <summary>マッピング対象の全プロパティ（ナビゲーション除く）</summary>
            public required IReadOnlyList<PropertyInfo> AllProperties { get; init; }

            /// <summary>主キーを除くプロパティ</summary>
            public required IReadOnlyList<PropertyInfo> NonKeyProperties { get; init; }

            /// <summary>全件取得 SELECT 文</summary>
            public required string SelectAllSql { get; init; }

            /// <summary>主キー指定取得 SELECT 文</summary>
            public required string SelectByIdSql { get; init; }

            /// <summary>INSERT 文</summary>
            public required string InsertSql { get; init; }

            /// <summary>UPDATE 文</summary>
            public required string UpdateSql { get; init; }

            /// <summary>DELETE 文</summary>
            public required string DeleteSql { get; init; }

            /// <summary>エンティティ型の属性を解析しメタデータを構築する</summary>
            public static SqlEntityMetadata<TEntity, TKey> Create()
            {
                var entityType = typeof(TEntity);
                var tableAttribute = entityType.GetCustomAttribute<TableAttribute>()
                    ?? throw new InvalidOperationException($"{entityType.Name} に [Table] 属性が必要です。");
                var properties = entityType
                    .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                    .Where(property =>
                        property.CanRead
                        && property.CanWrite
                        && property.GetCustomAttribute<NavigationReferenceAttribute>() is null
                    )
                    .ToList();
                var keyProperty = properties.SingleOrDefault(property => property.GetCustomAttribute<KeyAttribute>() is not null)
                    ?? throw new InvalidOperationException($"{entityType.Name} に [Key] 属性付きプロパティが必要です。");
                var nonKeyProperties = properties.Where(property => property != keyProperty).ToList();
                var allColumns = properties.Select(GetColumnName).ToArray();
                var insertColumns = properties.Select(GetColumnName).ToArray();
                var updateAssignments = nonKeyProperties.Select(property => $"[{GetColumnName(property)}] = @{property.Name}").ToArray();
                var tableName = $"[{tableAttribute.Name}]";
                var keyColumnName = GetColumnName(keyProperty);

                return new SqlEntityMetadata<TEntity, TKey>
                {
                    TableName = tableName,
                    KeyProperty = keyProperty,
                    KeyColumnName = keyColumnName,
                    AllProperties = properties,
                    NonKeyProperties = nonKeyProperties,
                    SelectAllSql = $"SELECT {string.Join(", ", allColumns.Select(column => $"[{column}]"))} FROM {tableName};",
                    SelectByIdSql = $"SELECT {string.Join(", ", allColumns.Select(column => $"[{column}]"))} FROM {tableName} WHERE [{keyColumnName}] = @id;",
                    InsertSql = $"INSERT INTO {tableName} ({string.Join(", ", insertColumns.Select(column => $"[{column}]"))}) VALUES ({string.Join(", ", properties.Select(property => $"@{property.Name}"))});",
                    UpdateSql = $"UPDATE {tableName} SET {string.Join(", ", updateAssignments)} WHERE [{keyColumnName}] = @id;",
                    DeleteSql = $"DELETE FROM {tableName} WHERE [{keyColumnName}] = @id;",
                };
            }

            /// <summary>データリーダーの 1 行をエンティティへマッピングする</summary>
            public TEntity MapEntity(SqlDataReader reader)
            {
                var entity = new TEntity();

                foreach (var property in AllProperties)
                {
                    var columnName = GetColumnName(property);
                    var value = reader[columnName];

                    if (value is DBNull)
                    {
                        property.SetValue(entity, null);
                    }
                    else
                    {
                        property.SetValue(entity, value);
                    }
                }

                return entity;
            }

            /// <summary>INSERT 用パラメータを設定する</summary>
            public void BindInsertParameters(SqlCommand command, TEntity entity)
            {
                foreach (var property in AllProperties)
                {
                    command.Parameters.AddWithValue($"@{property.Name}", property.GetValue(entity) ?? DBNull.Value);
                }
            }

            /// <summary>UPDATE 用パラメータ（非キー列＋主キー）を設定する</summary>
            public void BindUpdateParameters(SqlCommand command, TEntity entity)
            {
                foreach (var property in NonKeyProperties)
                {
                    command.Parameters.AddWithValue($"@{property.Name}", property.GetValue(entity) ?? DBNull.Value);
                }

                command.Parameters.AddWithValue("@id", KeyProperty.GetValue(entity) ?? DBNull.Value);
            }

            /// <summary>主キーパラメータを設定する</summary>
            public void BindKeyParameter(SqlCommand command, TKey id)
            {
                command.Parameters.AddWithValue("@id", id ?? throw new InvalidOperationException("id は null にできません。"));
            }

            /// <summary>[Column] 属性を優先してカラム名を解決する</summary>
            private static string GetColumnName(PropertyInfo property) =>
                property.GetCustomAttribute<ColumnAttribute>()?.Name ?? property.Name;
        }

        /// <summary>メタデータを用いて CRUD を実装する SQL Server 向けリポジトリ基底クラス</summary>
        public abstract class SqlServerRepository<TEntity, TKey>(ISqlConnectionFactory connectionFactory)
            : IRepository<TEntity, TKey>
            where TEntity : class, new()
        {
            /// <summary>エンティティ型ごとに 1 度だけ構築されるメタデータ（静的キャッシュ）</summary>
            private static readonly SqlEntityMetadata<TEntity, TKey> _metadata = SqlEntityMetadata<TEntity, TKey>.Create();

            /// <summary>SQL 接続の生成元</summary>
            private readonly ISqlConnectionFactory _connectionFactory = connectionFactory;

            /// <summary>主キーによる単一エンティティ取得（該当なしは null）</summary>
            public async Task<TEntity?> GetByIdAsync(TKey id, CancellationToken cancellationToken = default)
            {
                await using var connection = _connectionFactory.CreateConnection();
                await connection.OpenAsync(cancellationToken);

                await using var command = new SqlCommand(_metadata.SelectByIdSql, connection);
                _metadata.BindKeyParameter(command, id);

                await using var reader = await command.ExecuteReaderAsync(cancellationToken);

                if (!await reader.ReadAsync(cancellationToken))
                {
                    return null;
                }

                return _metadata.MapEntity(reader);
            }

            /// <summary>全エンティティ取得</summary>
            public async Task<IReadOnlyList<TEntity>> GetAllAsync(CancellationToken cancellationToken = default)
            {
                var items = new List<TEntity>();

                await using var connection = _connectionFactory.CreateConnection();
                await connection.OpenAsync(cancellationToken);

                await using var command = new SqlCommand(_metadata.SelectAllSql, connection);
                await using var reader = await command.ExecuteReaderAsync(cancellationToken);

                while (await reader.ReadAsync(cancellationToken))
                {
                    items.Add(_metadata.MapEntity(reader));
                }

                return items;
            }

            /// <summary>エンティティ追加</summary>
            public async Task InsertAsync(TEntity entity, CancellationToken cancellationToken = default)
            {
                ArgumentNullException.ThrowIfNull(entity);

                await using var connection = _connectionFactory.CreateConnection();
                await connection.OpenAsync(cancellationToken);

                await using var command = new SqlCommand(_metadata.InsertSql, connection);
                _metadata.BindInsertParameters(command, entity);
                await command.ExecuteNonQueryAsync(cancellationToken);
            }

            /// <summary>エンティティ更新（更新対象ありで true）</summary>
            public async Task<bool> UpdateAsync(TEntity entity, CancellationToken cancellationToken = default)
            {
                ArgumentNullException.ThrowIfNull(entity);

                await using var connection = _connectionFactory.CreateConnection();
                await connection.OpenAsync(cancellationToken);

                await using var command = new SqlCommand(_metadata.UpdateSql, connection);
                _metadata.BindUpdateParameters(command, entity);

                var affected = await command.ExecuteNonQueryAsync(cancellationToken);
                return affected > 0;
            }

            /// <summary>主キーによるエンティティ削除（削除対象ありで true）</summary>
            public async Task<bool> DeleteAsync(TKey id, CancellationToken cancellationToken = default)
            {
                await using var connection = _connectionFactory.CreateConnection();
                await connection.OpenAsync(cancellationToken);

                await using var command = new SqlCommand(_metadata.DeleteSql, connection);
                _metadata.BindKeyParameter(command, id);

                var affected = await command.ExecuteNonQueryAsync(cancellationToken);
                return affected > 0;
            }
        }

        /// <summary>生成されたリポジトリ群を DI コンテナへ登録する拡張</summary>
        public static class GeneratedRepositoryServiceCollectionExtensions
        {
            /// <summary>接続文字列とともに生成された全リポジトリを DI コンテナへ登録する</summary>
            public static IServiceCollection AddGeneratedRepositories(this IServiceCollection services, string connectionString)
            {
                ArgumentNullException.ThrowIfNull(services);
                ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);

                services.AddSingleton<ISqlConnectionFactory>(_ => new SqlConnectionFactory(connectionString));
        {{ for repository in repository_classes }}        services.AddScoped<{{ repository.interface_name }}, {{ repository.class_name }}>();
        {{ end }}
                return services;
            }
        }

        {{~ for repository in repository_classes ~}}
        {{ if !for.first }}

        {{ end }}/// <summary>{{ repository.entity_class_name }} 用リポジトリインターフェース</summary>
        public interface {{ repository.interface_name }} : IRepository<{{ repository.entity_class_name }}, {{ repository.key_type_name }}>;

        /// <summary>{{ repository.entity_class_name }} 用リポジトリ実装</summary>
        public sealed class {{ repository.class_name }}(ISqlConnectionFactory connectionFactory)
            : SqlServerRepository<{{ repository.entity_class_name }}, {{ repository.key_type_name }}>(connectionFactory), {{ repository.interface_name }};
        {{~ end ~}}
        {{~ end ~}}
        """;

    /// <summary>生成モデルとオプションをテンプレートへ流し込み、C# ソースコード文字列を生成する</summary>
    public string Render(CSharpGenerationModel model, CodeGenerationOptions options)
    {
        var template = Template.Parse(TemplateText);
        if (template.HasErrors)
        {
            var message = string.Join(Environment.NewLine, template.Messages.Select(m => m.ToString()));
            throw new InvalidOperationException($"C# 生成テンプレートの解析に失敗しました。{Environment.NewLine}{message}");
        }

        // 独自属性 NavigationReference は (1) Entity のナビゲーションプロパティへの付与、
        // (2) Repository の SqlEntityMetadata によるナビゲーション除外（リフレクション走査）のいずれかで参照される。
        // リレーションが無くても Repository を生成する場合は属性定義が必要なため、その条件も含める。
        var emitNavRefAttr =
            (options.GenerateEntityClasses && model.EntityClasses.Any(c => c.Navigations.Count > 0))
            || options.GenerateRepositories;

        var scriptObject = new Scriban.Runtime.ScriptObject
        {
            ["namespace_name"] = model.NamespaceName,
            ["usings"] = model.Usings,
            ["entity_classes"] = model.EntityClasses,
            ["edit_model_classes"] = model.EditModelClasses,
            ["mapper_classes"] = model.MapperClasses,
            ["repository_classes"] = model.RepositoryClasses,
            ["include_data_annotations"] = options.IncludeDataAnnotations,
            ["include_json_ignore_on_parent_navigation"] = options.IncludeJsonIgnoreOnParentNavigation,
            ["emit_nav_ref_attr"] = emitNavRefAttr,
        };

        // テンプレートは本ライブラリ内に固定で持つ信頼済みのものであり、ループ回数・出力量は ER 図の規模に
        // 応じて正当に増減する。Scriban 既定の上限のままだと大規模スキーマで出力が無言で打ち切られるため、
        // 関連する上限をすべて無効化（0 = 無制限）して全件を確実に出力する。
        //   - LoopLimit: ループ反復回数の上限（既定 1000）
        //   - LimitToString: レンダリング出力長の上限（既定 1MB = 1048576 文字。超過分は "..." で切り捨て）
        var context = new TemplateContext { LoopLimit = 0, LimitToString = 0 };

        context.PushGlobal(scriptObject);
        return template.Render(context).ReplaceLineEndings(Environment.NewLine).TrimEnd() + Environment.NewLine;
    }
}
