//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.CodeGen.CSharp.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.CodeGen.CSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string CodeGen_Error_MultiTargetEfCoreExclusive {
            get {
                return ResourceManager.GetString("CodeGen_Error_MultiTargetEfCoreExclusive", resourceCulture);
            }
        }

        public static string CodeGen_Error_InMemoryRuntimePackagesExclusive {
            get {
                return ResourceManager.GetString("CodeGen_Error_InMemoryRuntimePackagesExclusive", resourceCulture);
            }
        }

        public static string CodeGen_Error_TypeMismatch {
            get {
                return ResourceManager.GetString("CodeGen_Error_TypeMismatch", resourceCulture);
            }
        }

        public static string CodeGen_Error_MapperRequiresEntityAndEditModel {
            get {
                return ResourceManager.GetString("CodeGen_Error_MapperRequiresEntityAndEditModel", resourceCulture);
            }
        }

        public static string CodeGen_Error_RepositoryRequiresDataAnnotations {
            get {
                return ResourceManager.GetString("CodeGen_Error_RepositoryRequiresDataAnnotations", resourceCulture);
            }
        }

        public static string CodeGen_Error_NoEntities {
            get {
                return ResourceManager.GetString("CodeGen_Error_NoEntities", resourceCulture);
            }
        }

        public static string CodeGen_Error_EmptyTableName {
            get {
                return ResourceManager.GetString("CodeGen_Error_EmptyTableName", resourceCulture);
            }
        }

        public static string CodeGen_Error_EntityClassNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Error_EntityClassNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Error_ColumnPropertyNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Error_ColumnPropertyNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Error_GeneratedMemberNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Error_GeneratedMemberNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Origin_Column {
            get {
                return ResourceManager.GetString("CodeGen_Origin_Column", resourceCulture);
            }
        }

        public static string CodeGen_Origin_Navigation {
            get {
                return ResourceManager.GetString("CodeGen_Origin_Navigation", resourceCulture);
            }
        }

        public static string CodeGen_Origin_FixedMember {
            get {
                return ResourceManager.GetString("CodeGen_Origin_FixedMember", resourceCulture);
            }
        }

        public static string CodeGen_Error_InvalidNamespace {
            get {
                return ResourceManager.GetString("CodeGen_Error_InvalidNamespace", resourceCulture);
            }
        }

        public static string CodeGen_Warning_CompositeKey {
            get {
                return ResourceManager.GetString("CodeGen_Warning_CompositeKey", resourceCulture);
            }
        }

        public static string CodeGen_Error_UnsupportedRepositoryDialect {
            get {
                return ResourceManager.GetString("CodeGen_Error_UnsupportedRepositoryDialect", resourceCulture);
            }
        }

        public static string CodeGen_Error_NonGeneratedFileOverwrite {
            get {
                return ResourceManager.GetString("CodeGen_Error_NonGeneratedFileOverwrite", resourceCulture);
            }
        }

        public static string CodeGen_Warning_EntityDisplayNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Warning_EntityDisplayNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Warning_EditModelDisplayNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Warning_EditModelDisplayNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RepositorySingleKeyOnly {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RepositorySingleKeyOnly", resourceCulture);
            }
        }

        public static string CodeGen_Info_ExcludedUnboundedBinaryColumns {
            get {
                return ResourceManager.GetString("CodeGen_Info_ExcludedUnboundedBinaryColumns", resourceCulture);
            }
        }

        public static string CodeGen_Warning_ManyToManySkipped {
            get {
                return ResourceManager.GetString("CodeGen_Warning_ManyToManySkipped", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RelationshipTargetNotFound {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RelationshipTargetNotFound", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RelationshipKeyUnknown {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RelationshipKeyUnknown", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RelationshipCompositeSkipped {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RelationshipCompositeSkipped", resourceCulture);
            }
        }

        public static string CodeGen_Warning_ValueObjectDefinitionMismatch {
            get {
                return ResourceManager.GetString("CodeGen_Warning_ValueObjectDefinitionMismatch", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnexpectedCharacter", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnexpectedToken {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnexpectedToken", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnexpectedEnd {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnexpectedEnd", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnterminatedString {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnterminatedString", resourceCulture);
            }
        }

        public static string CodeGen_Query_ExpectedColumnOrParen {
            get {
                return ResourceManager.GetString("CodeGen_Query_ExpectedColumnOrParen", resourceCulture);
            }
        }

        public static string CodeGen_Query_EndOfInput {
            get {
                return ResourceManager.GetString("CodeGen_Query_EndOfInput", resourceCulture);
            }
        }

        public static string CodeGen_Query_ExpectedComparison {
            get {
                return ResourceManager.GetString("CodeGen_Query_ExpectedComparison", resourceCulture);
            }
        }

        public static string CodeGen_Query_ExpectedNullAfterIs {
            get {
                return ResourceManager.GetString("CodeGen_Query_ExpectedNullAfterIs", resourceCulture);
            }
        }

        public static string CodeGen_Query_ExpectedOperand {
            get {
                return ResourceManager.GetString("CodeGen_Query_ExpectedOperand", resourceCulture);
            }
        }

        public static string CodeGen_Query_ExpectedInParameter {
            get {
                return ResourceManager.GetString("CodeGen_Query_ExpectedInParameter", resourceCulture);
            }
        }

        public static string CodeGen_Query_StringMatchRequiresText {
            get {
                return ResourceManager.GetString("CodeGen_Query_StringMatchRequiresText", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnsupportedLikePattern {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnsupportedLikePattern", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnknownColumn {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnknownColumn", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnknownParameter {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnknownParameter", resourceCulture);
            }
        }

        public static string CodeGen_Query_InRequiresListParameter {
            get {
                return ResourceManager.GetString("CodeGen_Query_InRequiresListParameter", resourceCulture);
            }
        }

        public static string CodeGen_Query_ListParameterOnlyWithIn {
            get {
                return ResourceManager.GetString("CodeGen_Query_ListParameterOnlyWithIn", resourceCulture);
            }
        }

        public static string CodeGen_Query_NullCheckOnNonNullableColumn {
            get {
                return ResourceManager.GetString("CodeGen_Query_NullCheckOnNonNullableColumn", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnknownEntity {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnknownEntity", resourceCulture);
            }
        }

        public static string CodeGen_Query_DanglingParameterColumn {
            get {
                return ResourceManager.GetString("CodeGen_Query_DanglingParameterColumn", resourceCulture);
            }
        }

        public static string CodeGen_Query_DanglingFieldColumn {
            get {
                return ResourceManager.GetString("CodeGen_Query_DanglingFieldColumn", resourceCulture);
            }
        }

        public static string CodeGen_Query_DanglingOrderByColumn {
            get {
                return ResourceManager.GetString("CodeGen_Query_DanglingOrderByColumn", resourceCulture);
            }
        }

        public static string CodeGen_Query_InvalidName {
            get {
                return ResourceManager.GetString("CodeGen_Query_InvalidName", resourceCulture);
            }
        }

        public static string CodeGen_Query_ReservedMethodName {
            get {
                return ResourceManager.GetString("CodeGen_Query_ReservedMethodName", resourceCulture);
            }
        }

        public static string CodeGen_Query_DuplicateMethodName {
            get {
                return ResourceManager.GetString("CodeGen_Query_DuplicateMethodName", resourceCulture);
            }
        }

        public static string CodeGen_Query_InvalidParameterName {
            get {
                return ResourceManager.GetString("CodeGen_Query_InvalidParameterName", resourceCulture);
            }
        }

        public static string CodeGen_Query_DuplicateParameterName {
            get {
                return ResourceManager.GetString("CodeGen_Query_DuplicateParameterName", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnresolvedTypeToken {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnresolvedTypeToken", resourceCulture);
            }
        }

        public static string CodeGen_Query_ConditionInvalid {
            get {
                return ResourceManager.GetString("CodeGen_Query_ConditionInvalid", resourceCulture);
            }
        }

        public static string CodeGen_Query_ScalarRequiresType {
            get {
                return ResourceManager.GetString("CodeGen_Query_ScalarRequiresType", resourceCulture);
            }
        }

        public static string CodeGen_Query_ScalarDslUnsupported {
            get {
                return ResourceManager.GetString("CodeGen_Query_ScalarDslUnsupported", resourceCulture);
            }
        }

        public static string CodeGen_Query_ProjectionRequiresFields {
            get {
                return ResourceManager.GetString("CodeGen_Query_ProjectionRequiresFields", resourceCulture);
            }
        }

        public static string CodeGen_Query_InvalidResultTypeName {
            get {
                return ResourceManager.GetString("CodeGen_Query_InvalidResultTypeName", resourceCulture);
            }
        }

        public static string CodeGen_Query_ProjectionDslRequiresColumns {
            get {
                return ResourceManager.GetString("CodeGen_Query_ProjectionDslRequiresColumns", resourceCulture);
            }
        }

        public static string CodeGen_Query_PagingRequiresList {
            get {
                return ResourceManager.GetString("CodeGen_Query_PagingRequiresList", resourceCulture);
            }
        }

        public static string CodeGen_Query_OrderByRequiresList {
            get {
                return ResourceManager.GetString("CodeGen_Query_OrderByRequiresList", resourceCulture);
            }
        }

        public static string CodeGen_Query_OrderByColumnNotFound {
            get {
                return ResourceManager.GetString("CodeGen_Query_OrderByColumnNotFound", resourceCulture);
            }
        }

        public static string CodeGen_Query_UnknownSqlDialect {
            get {
                return ResourceManager.GetString("CodeGen_Query_UnknownSqlDialect", resourceCulture);
            }
        }

        public static string CodeGen_Query_InvalidFieldName {
            get {
                return ResourceManager.GetString("CodeGen_Query_InvalidFieldName", resourceCulture);
            }
        }

        public static string CodeGen_Query_FieldColumnNotFound {
            get {
                return ResourceManager.GetString("CodeGen_Query_FieldColumnNotFound", resourceCulture);
            }
        }

        public static string CodeGen_Query_ParameterColumnNotFound {
            get {
                return ResourceManager.GetString("CodeGen_Query_ParameterColumnNotFound", resourceCulture);
            }
        }

        public static string CodeGen_Query_DuplicateResultTypeName {
            get {
                return ResourceManager.GetString("CodeGen_Query_DuplicateResultTypeName", resourceCulture);
            }
        }

        public static string CodeGen_Query_RawSqlUndeclaredParameter {
            get {
                return ResourceManager.GetString("CodeGen_Query_RawSqlUndeclaredParameter", resourceCulture);
            }
        }

        public static string CodeGen_Query_RawSqlUnusedParameter {
            get {
                return ResourceManager.GetString("CodeGen_Query_RawSqlUnusedParameter", resourceCulture);
            }
        }

        public static string CodeGen_Query_RawSqlMultipleStatements {
            get {
                return ResourceManager.GetString("CodeGen_Query_RawSqlMultipleStatements", resourceCulture);
            }
        }

        public static string CodeGen_Query_RawSqlIssue {
            get {
                return ResourceManager.GetString("CodeGen_Query_RawSqlIssue", resourceCulture);
            }
        }

        public static string CodeGen_RuntimePackageGuidanceHeading {
            get {
                return ResourceManager.GetString("CodeGen_RuntimePackageGuidanceHeading", resourceCulture);
            }
        }

        public static string ApiDoc_Navigation_ParentReference {
            get {
                return ResourceManager.GetString("ApiDoc_Navigation_ParentReference", resourceCulture);
            }
        }

        public static string ApiDoc_Navigation_ChildCollection {
            get {
                return ResourceManager.GetString("ApiDoc_Navigation_ChildCollection", resourceCulture);
            }
        }

        public static string ApiDoc_Di_QuickerRepository {
            get {
                return ResourceManager.GetString("ApiDoc_Di_QuickerRepository", resourceCulture);
            }
        }

        public static string ApiDoc_Di_KeyedMultiDialect {
            get {
                return ResourceManager.GetString("ApiDoc_Di_KeyedMultiDialect", resourceCulture);
            }
        }

        public static string ApiDoc_Di_EfCore {
            get {
                return ResourceManager.GetString("ApiDoc_Di_EfCore", resourceCulture);
            }
        }

        public static string ApiDoc_Di_InMemory {
            get {
                return ResourceManager.GetString("ApiDoc_Di_InMemory", resourceCulture);
            }
        }
    }
}
