//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.CodeGen.CSharp.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.CodeGen.CSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string CodeGen_Error_MultiTargetEfCoreExclusive {
            get {
                return ResourceManager.GetString("CodeGen_Error_MultiTargetEfCoreExclusive", resourceCulture);
            }
        }

        public static string CodeGen_Error_InMemoryRuntimePackagesExclusive {
            get {
                return ResourceManager.GetString("CodeGen_Error_InMemoryRuntimePackagesExclusive", resourceCulture);
            }
        }

        public static string CodeGen_Error_TypeMismatch {
            get {
                return ResourceManager.GetString("CodeGen_Error_TypeMismatch", resourceCulture);
            }
        }

        public static string CodeGen_Error_NoGenerationTarget {
            get {
                return ResourceManager.GetString("CodeGen_Error_NoGenerationTarget", resourceCulture);
            }
        }

        public static string CodeGen_Error_MapperRequiresEntityAndEditModel {
            get {
                return ResourceManager.GetString("CodeGen_Error_MapperRequiresEntityAndEditModel", resourceCulture);
            }
        }

        public static string CodeGen_Error_RepositoryRequiresEntity {
            get {
                return ResourceManager.GetString("CodeGen_Error_RepositoryRequiresEntity", resourceCulture);
            }
        }

        public static string CodeGen_Error_RepositoryRequiresDataAnnotations {
            get {
                return ResourceManager.GetString("CodeGen_Error_RepositoryRequiresDataAnnotations", resourceCulture);
            }
        }

        public static string CodeGen_Error_NoEntities {
            get {
                return ResourceManager.GetString("CodeGen_Error_NoEntities", resourceCulture);
            }
        }

        public static string CodeGen_Error_EmptyTableName {
            get {
                return ResourceManager.GetString("CodeGen_Error_EmptyTableName", resourceCulture);
            }
        }

        public static string CodeGen_Warning_CompositeKey {
            get {
                return ResourceManager.GetString("CodeGen_Warning_CompositeKey", resourceCulture);
            }
        }

        public static string CodeGen_Error_UnsupportedRepositoryDialect {
            get {
                return ResourceManager.GetString("CodeGen_Error_UnsupportedRepositoryDialect", resourceCulture);
            }
        }

        public static string CodeGen_Error_NonGeneratedFileOverwrite {
            get {
                return ResourceManager.GetString("CodeGen_Error_NonGeneratedFileOverwrite", resourceCulture);
            }
        }

        public static string CodeGen_Warning_EntityDisplayNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Warning_EntityDisplayNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Warning_EditModelDisplayNameCollision {
            get {
                return ResourceManager.GetString("CodeGen_Warning_EditModelDisplayNameCollision", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RepositorySingleKeyOnly {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RepositorySingleKeyOnly", resourceCulture);
            }
        }

        public static string CodeGen_Warning_ManyToManySkipped {
            get {
                return ResourceManager.GetString("CodeGen_Warning_ManyToManySkipped", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RelationshipTargetNotFound {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RelationshipTargetNotFound", resourceCulture);
            }
        }

        public static string CodeGen_Warning_RelationshipKeyUnknown {
            get {
                return ResourceManager.GetString("CodeGen_Warning_RelationshipKeyUnknown", resourceCulture);
            }
        }

        public static string CodeGen_Warning_ValueObjectDefinitionMismatch {
            get {
                return ResourceManager.GetString("CodeGen_Warning_ValueObjectDefinitionMismatch", resourceCulture);
            }
        }
    }
}
