using AwesomeAssertions;
using QuickER.CodeGen.CSharp;
using QuickER.Model;
using QuickER.Provider;
using QuickER.SqlServer;

namespace QuickER.Tests.CodeGen.CSharp;

/// <summary>
/// 生成ファイルのヘッダーへ刻む版の行・内容ハッシュの行が、全出力モードの <c>.g.cs</c> に付き、
/// API リファレンスには版だけが載り、ランタイムパッケージ用ソースには付かないことを検証するテストクラス。
/// </summary>
/// <remarks>
/// 刻む処理は生成サービスの 1 箇所（描画・連結の後）だけにある。出力モードごとに描画経路が違う
/// （単一スペック＝テンプレートのヘッダー・連結＝サービスが組むヘッダー）ため、両経路を含むモードを網羅する。
/// </remarks>
public sealed class GeneratedHeaderStampTests
{
    private static readonly string ExpectedVersionLine =
        GeneratedContentHash.VersionLinePrefix + RuntimePackages.ResolveGuidanceVersion();

    /// <summary>Order エンティティ 1 つの最小図を作る</summary>
    private static ErDiagram CreateDiagram()
    {
        var order = new Entity { TableName = "Order" };
        order.Columns.Add(
            new Column
            {
                Name = "OrderId",
                DataType = "int",
                IsPrimaryKey = true,
                IsNullable = false,
            }
        );
        order.Columns.Add(new Column { Name = "Memo", DataType = "nvarchar(200)" });

        return new ErDiagram { Entities = { order } };
    }

    /// <summary>実経路（SqlServer プロバイダ）で生成する</summary>
    private static CodeGenerationResult Generate(CodeGenerationOptions options)
    {
        var provider = new SqlServerProvider();
        var result = DiagramCodeGenerator.Generate(
            provider.TypeMapper,
            provider.TypeCatalog,
            CreateDiagram(),
            options
        );

        result.HasErrors.Should().BeFalse();
        return result;
    }

    public static TheoryData<string, CodeGenerationOptions> OutputModes =>
        new()
        {
            {
                "非分割",
                new CodeGenerationOptions { GenerateRepositories = true }
            },
            {
                "分割",
                new CodeGenerationOptions
                {
                    GenerateRepositories = true,
                    SplitFilesByCategory = true,
                }
            },
            {
                "非分割マルチ方言（連結ヘッダー経路）",
                new CodeGenerationOptions
                {
                    GenerateRepositories = true,
                    RepositoryDialects = ["sqlserver", "sqlite"],
                }
            },
            {
                "層別",
                new CodeGenerationOptions
                {
                    RootNamespace = "Acme.App",
                    LayeredOutput = true,
                    GenerateRepositories = true,
                    GenerateEditModels = true,
                    GenerateMappers = true,
                    GenerateRemoteServices = true,
                }
            },
            {
                "パッケージ参照",
                new CodeGenerationOptions
                {
                    GenerateRepositories = true,
                    SplitFilesByCategory = true,
                    UseRuntimePackages = true,
                }
            },
        };

    [Theory(DisplayName = "生成: 全出力モードの .g.cs は版の行と一致する内容ハッシュを持つ")]
    [MemberData(nameof(OutputModes))]
    public void Generate_AllCSharpFiles_AreStamped(string mode, CodeGenerationOptions options)
    {
        var files = Generate(options).Files.Where(file => file.FileName.EndsWith(".g.cs")).ToList();

        files.Should().NotBeEmpty(mode);

        foreach (var file in files)
        {
            var lines = file.Content.Split(["\r\n", "\n"], StringSplitOptions.None);

            lines[0]
                .Should()
                .Be(GeneratedContentHash.AutoGeneratedLine, $"{mode}: {file.FileName}");
            lines[1].Should().Be(ExpectedVersionLine, $"{mode}: {file.FileName}");
            lines[2]
                .Should()
                .Be(
                    GeneratedContentHash.HashLinePrefix
                        + GeneratedContentHash.Compute(file.Content),
                    $"{mode}: {file.FileName}"
                );
            GeneratedContentHash
                .Verify(file.Content)
                .Should()
                .Be(GeneratedContentHashStatus.Unchanged, $"{mode}: {file.FileName}");
        }
    }

    [Fact(DisplayName = "生成: API リファレンスは英日とも版の行だけを持ち、内容ハッシュは持たない")]
    public void Generate_ApiDocs_CarryVersionOnly()
    {
        var docs = Generate(
            new CodeGenerationOptions
            {
                GenerateRepositories = true,
                GenerateApiDocs = true,
                ApiDocsLanguage = ApiDocsLanguage.Both,
            }
        )
            .Files.Where(file => file.FileName.EndsWith(".g.md"))
            .ToList();

        docs.Should().HaveCount(2);

        foreach (var doc in docs)
        {
            doc.Content.Should()
                .Contain(
                    $"<!-- Generated by QuickER {RuntimePackages.ResolveGuidanceVersion()} -->"
                );
            doc.Content.Should().NotContain(GeneratedContentHash.HashLinePrefix);
        }
    }

    [Fact(DisplayName = "パッケージ用ソース: 版の行・内容ハッシュの行を持たない")]
    public void RuntimePackageSources_AreNotStamped()
    {
        var renderer = new RuntimePackageSourceRenderer();
        var sources = new[]
        {
            renderer.RenderCore(),
            renderer.RenderSqlServer(),
            renderer.RenderSqlite(),
            renderer.RenderEfCore(),
            renderer.RenderInMemory(),
            renderer.RenderAspNetCore(),
            renderer.RenderSync(),
        };

        foreach (var source in sources)
        {
            source.Should().NotContain(GeneratedContentHash.VersionLinePrefix);
            source.Should().NotContain(GeneratedContentHash.HashLinePrefix);
        }
    }
}
