//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.AI.Mock.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.AI.Mock.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Mock_WindowTitle {
            get {
                return ResourceManager.GetString("Mock_WindowTitle", resourceCulture);
            }
        }

        public static string Mock_TabApiKey {
            get {
                return ResourceManager.GetString("Mock_TabApiKey", resourceCulture);
            }
        }

        public static string Mock_Provider {
            get {
                return ResourceManager.GetString("Mock_Provider", resourceCulture);
            }
        }

        public static string Mock_ProviderTooltip {
            get {
                return ResourceManager.GetString("Mock_ProviderTooltip", resourceCulture);
            }
        }

        public static string Mock_ModelName {
            get {
                return ResourceManager.GetString("Mock_ModelName", resourceCulture);
            }
        }

        public static string Mock_ApiKey {
            get {
                return ResourceManager.GetString("Mock_ApiKey", resourceCulture);
            }
        }

        public static string Mock_ApiKeyTooltip {
            get {
                return ResourceManager.GetString("Mock_ApiKeyTooltip", resourceCulture);
            }
        }

        public static string Mock_ApiKeyOptionalNote {
            get {
                return ResourceManager.GetString("Mock_ApiKeyOptionalNote", resourceCulture);
            }
        }

        public static string Mock_Save {
            get {
                return ResourceManager.GetString("Mock_Save", resourceCulture);
            }
        }

        public static string Mock_Endpoint {
            get {
                return ResourceManager.GetString("Mock_Endpoint", resourceCulture);
            }
        }

        public static string Mock_EndpointTooltip {
            get {
                return ResourceManager.GetString("Mock_EndpointTooltip", resourceCulture);
            }
        }

        public static string Mock_Model {
            get {
                return ResourceManager.GetString("Mock_Model", resourceCulture);
            }
        }

        public static string Mock_ConversationHeader {
            get {
                return ResourceManager.GetString("Mock_ConversationHeader", resourceCulture);
            }
        }

        public static string Mock_Generating {
            get {
                return ResourceManager.GetString("Mock_Generating", resourceCulture);
            }
        }

        public static string Mock_Interrupt {
            get {
                return ResourceManager.GetString("Mock_Interrupt", resourceCulture);
            }
        }

        public static string Mock_NewConversation {
            get {
                return ResourceManager.GetString("Mock_NewConversation", resourceCulture);
            }
        }

        public static string Mock_InputTooltip {
            get {
                return ResourceManager.GetString("Mock_InputTooltip", resourceCulture);
            }
        }

        public static string Mock_Send {
            get {
                return ResourceManager.GetString("Mock_Send", resourceCulture);
            }
        }

        public static string Mock_PreviewHeader {
            get {
                return ResourceManager.GetString("Mock_PreviewHeader", resourceCulture);
            }
        }

        public static string Mock_ExportHtml {
            get {
                return ResourceManager.GetString("Mock_ExportHtml", resourceCulture);
            }
        }

        public static string Mock_ExportDesignDoc {
            get {
                return ResourceManager.GetString("Mock_ExportDesignDoc", resourceCulture);
            }
        }

        public static string Mock_DesignDocSaved {
            get {
                return ResourceManager.GetString("Mock_DesignDocSaved", resourceCulture);
            }
        }

        public static string Mock_DesignDocSavedMessageFormat {
            get {
                return ResourceManager.GetString("Mock_DesignDocSavedMessageFormat", resourceCulture);
            }
        }

        public static string Mock_DesignDocSaveFailedFormat {
            get {
                return ResourceManager.GetString("Mock_DesignDocSaveFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Step2Header {
            get {
                return ResourceManager.GetString("Mock_Step2Header", resourceCulture);
            }
        }

        public static string Mock_OutputFolder {
            get {
                return ResourceManager.GetString("Mock_OutputFolder", resourceCulture);
            }
        }

        public static string Mock_Browse {
            get {
                return ResourceManager.GetString("Mock_Browse", resourceCulture);
            }
        }

        public static string Mock_MockFolder {
            get {
                return ResourceManager.GetString("Mock_MockFolder", resourceCulture);
            }
        }

        public static string Mock_MockFolderTooltip {
            get {
                return ResourceManager.GetString("Mock_MockFolderTooltip", resourceCulture);
            }
        }

        public static string Mock_PickMockFolderTitle {
            get {
                return ResourceManager.GetString("Mock_PickMockFolderTitle", resourceCulture);
            }
        }

        public static string Mock_ScreensHeader {
            get {
                return ResourceManager.GetString("Mock_ScreensHeader", resourceCulture);
            }
        }

        public static string Mock_NotAMockFolder {
            get {
                return ResourceManager.GetString("Mock_NotAMockFolder", resourceCulture);
            }
        }

        public static string Mock_MockFolderOpenFailedFormat {
            get {
                return ResourceManager.GetString("Mock_MockFolderOpenFailedFormat", resourceCulture);
            }
        }

        public static string Mock_WarningsHeading {
            get {
                return ResourceManager.GetString("Mock_WarningsHeading", resourceCulture);
            }
        }

        public static string Mock_ProjectName {
            get {
                return ResourceManager.GetString("Mock_ProjectName", resourceCulture);
            }
        }

        public static string Mock_MockGenInstructions {
            get {
                return ResourceManager.GetString("Mock_MockGenInstructions", resourceCulture);
            }
        }

        public static string Mock_MockGenInstructionsTooltip {
            get {
                return ResourceManager.GetString("Mock_MockGenInstructionsTooltip", resourceCulture);
            }
        }

        public static string Mock_OpenFolder {
            get {
                return ResourceManager.GetString("Mock_OpenFolder", resourceCulture);
            }
        }

        public static string Mock_GenerateProject {
            get {
                return ResourceManager.GetString("Mock_GenerateProject", resourceCulture);
            }
        }

        public static string Mock_TargetLabel {
            get {
                return ResourceManager.GetString("Mock_TargetLabel", resourceCulture);
            }
        }

        public static string MockPreview_EmptyText {
            get {
                return ResourceManager.GetString("MockPreview_EmptyText", resourceCulture);
            }
        }

        public static string MockPreview_UnavailableTitle {
            get {
                return ResourceManager.GetString("MockPreview_UnavailableTitle", resourceCulture);
            }
        }

        public static string MockPreview_UnavailableMessage {
            get {
                return ResourceManager.GetString("MockPreview_UnavailableMessage", resourceCulture);
            }
        }

        public static string Mock_CodexNotConnected {
            get {
                return ResourceManager.GetString("Mock_CodexNotConnected", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_InProgress {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_InProgress", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_NoScreens {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_NoScreens", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ClaudeCli {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ClaudeCli", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ApiKeyNotReady {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ApiKeyNotReady", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_CodexNotReady {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_CodexNotReady", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_Dotnet {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_Dotnet", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_OutputFolder {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_OutputFolder", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ProjectName {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ProjectName", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ProjectNameInvalid {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ProjectNameInvalid", resourceCulture);
            }
        }

        public static string Mock_ConversationStarted {
            get {
                return ResourceManager.GetString("Mock_ConversationStarted", resourceCulture);
            }
        }

        public static string Mock_SendFailedFormat {
            get {
                return ResourceManager.GetString("Mock_SendFailedFormat", resourceCulture);
            }
        }

        public static string Mock_HtmlFileFilter {
            get {
                return ResourceManager.GetString("Mock_HtmlFileFilter", resourceCulture);
            }
        }

        public static string Mock_HtmlSaved {
            get {
                return ResourceManager.GetString("Mock_HtmlSaved", resourceCulture);
            }
        }

        public static string Mock_HtmlSaveFailedFormat {
            get {
                return ResourceManager.GetString("Mock_HtmlSaveFailedFormat", resourceCulture);
            }
        }

        public static string Mock_HtmlSavedMessageFormat {
            get {
                return ResourceManager.GetString("Mock_HtmlSavedMessageFormat", resourceCulture);
            }
        }

        public static string Mock_Clear {
            get {
                return ResourceManager.GetString("Mock_Clear", resourceCulture);
            }
        }

        public static string Mock_ClearConfirm {
            get {
                return ResourceManager.GetString("Mock_ClearConfirm", resourceCulture);
            }
        }

        public static string Mock_PickOutputFolderTitle {
            get {
                return ResourceManager.GetString("Mock_PickOutputFolderTitle", resourceCulture);
            }
        }

        public static string Mock_OutputFolderNotEmpty {
            get {
                return ResourceManager.GetString("Mock_OutputFolderNotEmpty", resourceCulture);
            }
        }

        public static string Mock_GeneratingProject {
            get {
                return ResourceManager.GetString("Mock_GeneratingProject", resourceCulture);
            }
        }

        public static string Mock_GenerationErrorLogFormat {
            get {
                return ResourceManager.GetString("Mock_GenerationErrorLogFormat", resourceCulture);
            }
        }

        public static string Mock_GenerationFailedFormat {
            get {
                return ResourceManager.GetString("Mock_GenerationFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Codex_AutoContinueNotice {
            get {
                return ResourceManager.GetString("Mock_Codex_AutoContinueNotice", resourceCulture);
            }
        }

        public static string Mock_GenResultSuccessBodyFormat {
            get {
                return ResourceManager.GetString("Mock_GenResultSuccessBodyFormat", resourceCulture);
            }
        }

        public static string Mock_GenResultFailureBodyFormat {
            get {
                return ResourceManager.GetString("Mock_GenResultFailureBodyFormat", resourceCulture);
            }
        }

        public static string Mock_MockUpdated {
            get {
                return ResourceManager.GetString("Mock_MockUpdated", resourceCulture);
            }
        }

        public static string Mock_UpdateNoteFormat {
            get {
                return ResourceManager.GetString("Mock_UpdateNoteFormat", resourceCulture);
            }
        }

        public static string Mock_ResponseCompleted {
            get {
                return ResourceManager.GetString("Mock_ResponseCompleted", resourceCulture);
            }
        }

        public static string Mock_ErrorSystemFormat {
            get {
                return ResourceManager.GetString("Mock_ErrorSystemFormat", resourceCulture);
            }
        }

        public static string Mock_ErrorStatusFormat {
            get {
                return ResourceManager.GetString("Mock_ErrorStatusFormat", resourceCulture);
            }
        }

        public static string Mock_Interrupted {
            get {
                return ResourceManager.GetString("Mock_Interrupted", resourceCulture);
            }
        }

        public static string Mock_PreviewUpdateFailedFormat {
            get {
                return ResourceManager.GetString("Mock_PreviewUpdateFailedFormat", resourceCulture);
            }
        }

        public static string Mock_ErrorUnknown {
            get {
                return ResourceManager.GetString("Mock_ErrorUnknown", resourceCulture);
            }
        }

        public static string Mock_Run_Start {
            get {
                return ResourceManager.GetString("Mock_Run_Start", resourceCulture);
            }
        }

        public static string Mock_Run_OutputFolderFormat {
            get {
                return ResourceManager.GetString("Mock_Run_OutputFolderFormat", resourceCulture);
            }
        }

        public static string Mock_Run_ProjectNameFormat {
            get {
                return ResourceManager.GetString("Mock_Run_ProjectNameFormat", resourceCulture);
            }
        }

        public static string Mock_Run_TimedOutFormat {
            get {
                return ResourceManager.GetString("Mock_Run_TimedOutFormat", resourceCulture);
            }
        }

        public static string Mock_Run_Canceled {
            get {
                return ResourceManager.GetString("Mock_Run_Canceled", resourceCulture);
            }
        }

        public static string Mock_Run_ClientCompleted {
            get {
                return ResourceManager.GetString("Mock_Run_ClientCompleted", resourceCulture);
            }
        }

        public static string Mock_Run_ClientFailedFormat {
            get {
                return ResourceManager.GetString("Mock_Run_ClientFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Run_ArtifactsFound {
            get {
                return ResourceManager.GetString("Mock_Run_ArtifactsFound", resourceCulture);
            }
        }

        public static string Mock_Run_ArtifactsMissing {
            get {
                return ResourceManager.GetString("Mock_Run_ArtifactsMissing", resourceCulture);
            }
        }

        public static string Mock_Run_BuildVerify {
            get {
                return ResourceManager.GetString("Mock_Run_BuildVerify", resourceCulture);
            }
        }

        public static string Mock_Run_BuildSucceeded {
            get {
                return ResourceManager.GetString("Mock_Run_BuildSucceeded", resourceCulture);
            }
        }

        public static string Mock_Run_BuildFailed {
            get {
                return ResourceManager.GetString("Mock_Run_BuildFailed", resourceCulture);
            }
        }

        public static string Mock_Run_BuildVerifyCanceled {
            get {
                return ResourceManager.GetString("Mock_Run_BuildVerifyCanceled", resourceCulture);
            }
        }

        public static string Mock_Result_Success {
            get {
                return ResourceManager.GetString("Mock_Result_Success", resourceCulture);
            }
        }

        public static string Mock_Result_TimedOut {
            get {
                return ResourceManager.GetString("Mock_Result_TimedOut", resourceCulture);
            }
        }

        public static string Mock_Result_Canceled {
            get {
                return ResourceManager.GetString("Mock_Result_Canceled", resourceCulture);
            }
        }

        public static string Mock_Result_NotLoggedIn {
            get {
                return ResourceManager.GetString("Mock_Result_NotLoggedIn", resourceCulture);
            }
        }

        public static string Mock_CodexNotLoggedIn {
            get {
                return ResourceManager.GetString("Mock_CodexNotLoggedIn", resourceCulture);
            }
        }

        public static string Mock_Result_ClientFailedFormat {
            get {
                return ResourceManager.GetString("Mock_Result_ClientFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Result_ArtifactsMissing {
            get {
                return ResourceManager.GetString("Mock_Result_ArtifactsMissing", resourceCulture);
            }
        }

        public static string Mock_Result_BuildFailed {
            get {
                return ResourceManager.GetString("Mock_Result_BuildFailed", resourceCulture);
            }
        }

        public static string Mock_Result_Failed {
            get {
                return ResourceManager.GetString("Mock_Result_Failed", resourceCulture);
            }
        }

        public static string Mock_DotnetStartFailed {
            get {
                return ResourceManager.GetString("Mock_DotnetStartFailed", resourceCulture);
            }
        }

        public static string Mock_ScaffoldFailedFormat {
            get {
                return ResourceManager.GetString("Mock_ScaffoldFailedFormat", resourceCulture);
            }
        }

        public static string Mock_RemoveModelFromHistory {
            get {
                return ResourceManager.GetString("Mock_RemoveModelFromHistory", resourceCulture);
            }
        }

        public static string Toolbar_MockGeneration {
            get {
                return ResourceManager.GetString("Toolbar_MockGeneration", resourceCulture);
            }
        }

        public static string Toolbar_MockGenerationTooltip {
            get {
                return ResourceManager.GetString("Toolbar_MockGenerationTooltip", resourceCulture);
            }
        }
        public static string Mock_FunctionToolLabel {
            get {
                return ResourceManager.GetString("Mock_FunctionToolLabel", resourceCulture);
            }
        }

        public static string Mock_FolderDesignInstructionsTemplate {
            get {
                return ResourceManager.GetString("Mock_FolderDesignInstructionsTemplate", resourceCulture);
            }
        }

        public static string Mock_ResponseLanguageRule {
            get {
                return ResourceManager.GetString("Mock_ResponseLanguageRule", resourceCulture);
            }
        }

        public static string Mock_FolderInitialPromptTemplate {
            get {
                return ResourceManager.GetString("Mock_FolderInitialPromptTemplate", resourceCulture);
            }
        }

        public static string Mock_PromptUserInstructionsHeading {
            get {
                return ResourceManager.GetString("Mock_PromptUserInstructionsHeading", resourceCulture);
            }
        }

        public static string Mock_ScreenSavedResult {
            get {
                return ResourceManager.GetString("Mock_ScreenSavedResult", resourceCulture);
            }
        }

        public static string Mock_ScreenRemovedResult {
            get {
                return ResourceManager.GetString("Mock_ScreenRemovedResult", resourceCulture);
            }
        }

        public static string Mock_StylesheetSavedResult {
            get {
                return ResourceManager.GetString("Mock_StylesheetSavedResult", resourceCulture);
            }
        }

        public static string Mock_ScreenNotFoundResult {
            get {
                return ResourceManager.GetString("Mock_ScreenNotFoundResult", resourceCulture);
            }
        }

        public static string Mock_UnknownToolResult {
            get {
                return ResourceManager.GetString("Mock_UnknownToolResult", resourceCulture);
            }
        }

        public static string Mock_ArgumentsParseFailedResult {
            get {
                return ResourceManager.GetString("Mock_ArgumentsParseFailedResult", resourceCulture);
            }
        }

        public static string Mock_ResumePromptIntro {
            get {
                return ResourceManager.GetString("Mock_ResumePromptIntro", resourceCulture);
            }
        }

        public static string Mock_ResumePromptTitleHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptTitleHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptScreensHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptScreensHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptNoScreens {
            get {
                return ResourceManager.GetString("Mock_ResumePromptNoScreens", resourceCulture);
            }
        }

        public static string Mock_ResumePromptEntitiesLabelFormat {
            get {
                return ResourceManager.GetString("Mock_ResumePromptEntitiesLabelFormat", resourceCulture);
            }
        }

        public static string Mock_ResumePromptEntitiesNone {
            get {
                return ResourceManager.GetString("Mock_ResumePromptEntitiesNone", resourceCulture);
            }
        }

        public static string Mock_ResumePromptTransitionsHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptTransitionsHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptNoTransitions {
            get {
                return ResourceManager.GetString("Mock_ResumePromptNoTransitions", resourceCulture);
            }
        }

        public static string Mock_ResumePromptRevisionsHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptRevisionsHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptNoRevisions {
            get {
                return ResourceManager.GetString("Mock_ResumePromptNoRevisions", resourceCulture);
            }
        }

        public static string Mock_ResumePromptStylesheetHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptStylesheetHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptStylesheetBodyFormat {
            get {
                return ResourceManager.GetString("Mock_ResumePromptStylesheetBodyFormat", resourceCulture);
            }
        }

        public static string Mock_ResumePromptSchemaHeading {
            get {
                return ResourceManager.GetString("Mock_ResumePromptSchemaHeading", resourceCulture);
            }
        }

        public static string Mock_ResumePromptSchemaChangedNote {
            get {
                return ResourceManager.GetString("Mock_ResumePromptSchemaChangedNote", resourceCulture);
            }
        }

        public static string Mock_ResumePromptGetScreenNote {
            get {
                return ResourceManager.GetString("Mock_ResumePromptGetScreenNote", resourceCulture);
            }
        }

        public static string Mock_ApiKeyOneShotNote {
            get {
                return ResourceManager.GetString("Mock_ApiKeyOneShotNote", resourceCulture);
            }
        }

        public static string Mock_ApiRun_CommonPart {
            get {
                return ResourceManager.GetString("Mock_ApiRun_CommonPart", resourceCulture);
            }
        }

        public static string Mock_ApiRun_Screen {
            get {
                return ResourceManager.GetString("Mock_ApiRun_Screen", resourceCulture);
            }
        }

        public static string Mock_ApiRun_Emit {
            get {
                return ResourceManager.GetString("Mock_ApiRun_Emit", resourceCulture);
            }
        }

        public static string Mock_ApiRun_EmitRejectedFormat {
            get {
                return ResourceManager.GetString("Mock_ApiRun_EmitRejectedFormat", resourceCulture);
            }
        }

        public static string Mock_ApiRun_NoEmit {
            get {
                return ResourceManager.GetString("Mock_ApiRun_NoEmit", resourceCulture);
            }
        }

        public static string Mock_ApiRun_Build {
            get {
                return ResourceManager.GetString("Mock_ApiRun_Build", resourceCulture);
            }
        }

        public static string Mock_ApiRun_BuildOk {
            get {
                return ResourceManager.GetString("Mock_ApiRun_BuildOk", resourceCulture);
            }
        }

        public static string Mock_ApiRun_BuildFailedFixing {
            get {
                return ResourceManager.GetString("Mock_ApiRun_BuildFailedFixing", resourceCulture);
            }
        }

        public static string Mock_ApiRun_Rebuild {
            get {
                return ResourceManager.GetString("Mock_ApiRun_Rebuild", resourceCulture);
            }
        }

        public static string Mock_ApiRun_BuildFail {
            get {
                return ResourceManager.GetString("Mock_ApiRun_BuildFail", resourceCulture);
            }
        }

        public static string Mock_ApiRun_ErrorBuildFailed {
            get {
                return ResourceManager.GetString("Mock_ApiRun_ErrorBuildFailed", resourceCulture);
            }
        }

        public static string Mock_ApiRun_ErrorTurnFailedFormat {
            get {
                return ResourceManager.GetString("Mock_ApiRun_ErrorTurnFailedFormat", resourceCulture);
            }
        }

        public static string MockDoc_DefaultTitle {
            get {
                return ResourceManager.GetString("MockDoc_DefaultTitle", resourceCulture);
            }
        }

        public static string MockDoc_ScreenListHeading {
            get {
                return ResourceManager.GetString("MockDoc_ScreenListHeading", resourceCulture);
            }
        }

        public static string MockDoc_TransitionDiagramHeading {
            get {
                return ResourceManager.GetString("MockDoc_TransitionDiagramHeading", resourceCulture);
            }
        }

        public static string MockDoc_CrudHeading {
            get {
                return ResourceManager.GetString("MockDoc_CrudHeading", resourceCulture);
            }
        }

        public static string MockDoc_ColScreen {
            get {
                return ResourceManager.GetString("MockDoc_ColScreen", resourceCulture);
            }
        }

        public static string MockDoc_ColDescription {
            get {
                return ResourceManager.GetString("MockDoc_ColDescription", resourceCulture);
            }
        }

        public static string MockDoc_ColKind {
            get {
                return ResourceManager.GetString("MockDoc_ColKind", resourceCulture);
            }
        }

        public static string MockDoc_ColItem {
            get {
                return ResourceManager.GetString("MockDoc_ColItem", resourceCulture);
            }
        }

        public static string MockDoc_ColNote {
            get {
                return ResourceManager.GetString("MockDoc_ColNote", resourceCulture);
            }
        }

        public static string MockDoc_TransitionFrom {
            get {
                return ResourceManager.GetString("MockDoc_TransitionFrom", resourceCulture);
            }
        }

        public static string MockDoc_TransitionTo {
            get {
                return ResourceManager.GetString("MockDoc_TransitionTo", resourceCulture);
            }
        }

        public static string MockDoc_TriggerFormat {
            get {
                return ResourceManager.GetString("MockDoc_TriggerFormat", resourceCulture);
            }
        }

        public static string MockDoc_KindInput {
            get {
                return ResourceManager.GetString("MockDoc_KindInput", resourceCulture);
            }
        }

        public static string MockDoc_KindChoice {
            get {
                return ResourceManager.GetString("MockDoc_KindChoice", resourceCulture);
            }
        }

        public static string MockDoc_KindButton {
            get {
                return ResourceManager.GetString("MockDoc_KindButton", resourceCulture);
            }
        }

        public static string MockDoc_KindTableColumn {
            get {
                return ResourceManager.GetString("MockDoc_KindTableColumn", resourceCulture);
            }
        }

        public static string MockDoc_NoteMultiline {
            get {
                return ResourceManager.GetString("MockDoc_NoteMultiline", resourceCulture);
            }
        }

        public static string MockDoc_NoteRequired {
            get {
                return ResourceManager.GetString("MockDoc_NoteRequired", resourceCulture);
            }
        }

        public static string MockDoc_NoteRadio {
            get {
                return ResourceManager.GetString("MockDoc_NoteRadio", resourceCulture);
            }
        }

        public static string MockDoc_NoteCheckbox {
            get {
                return ResourceManager.GetString("MockDoc_NoteCheckbox", resourceCulture);
            }
        }

        public static string MockDoc_NoteOptionCountFormat {
            get {
                return ResourceManager.GetString("MockDoc_NoteOptionCountFormat", resourceCulture);
            }
        }

        public static string MockDoc_ItemTableFormat {
            get {
                return ResourceManager.GetString("MockDoc_ItemTableFormat", resourceCulture);
            }
        }

    }
}
