//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.AI.Mock.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.AI.Mock.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Mock_WindowTitle {
            get {
                return ResourceManager.GetString("Mock_WindowTitle", resourceCulture);
            }
        }

        public static string Mock_TabApiKey {
            get {
                return ResourceManager.GetString("Mock_TabApiKey", resourceCulture);
            }
        }

        public static string Mock_Provider {
            get {
                return ResourceManager.GetString("Mock_Provider", resourceCulture);
            }
        }

        public static string Mock_ModelName {
            get {
                return ResourceManager.GetString("Mock_ModelName", resourceCulture);
            }
        }

        public static string Mock_ApiKey {
            get {
                return ResourceManager.GetString("Mock_ApiKey", resourceCulture);
            }
        }

        public static string Mock_ApiKeyTooltip {
            get {
                return ResourceManager.GetString("Mock_ApiKeyTooltip", resourceCulture);
            }
        }

        public static string Mock_Save {
            get {
                return ResourceManager.GetString("Mock_Save", resourceCulture);
            }
        }

        public static string Mock_Endpoint {
            get {
                return ResourceManager.GetString("Mock_Endpoint", resourceCulture);
            }
        }

        public static string Mock_EndpointTooltip {
            get {
                return ResourceManager.GetString("Mock_EndpointTooltip", resourceCulture);
            }
        }

        public static string Mock_Model {
            get {
                return ResourceManager.GetString("Mock_Model", resourceCulture);
            }
        }

        public static string Mock_ConversationHeader {
            get {
                return ResourceManager.GetString("Mock_ConversationHeader", resourceCulture);
            }
        }

        public static string Mock_Generating {
            get {
                return ResourceManager.GetString("Mock_Generating", resourceCulture);
            }
        }

        public static string Mock_Interrupt {
            get {
                return ResourceManager.GetString("Mock_Interrupt", resourceCulture);
            }
        }

        public static string Mock_NewConversation {
            get {
                return ResourceManager.GetString("Mock_NewConversation", resourceCulture);
            }
        }

        public static string Mock_InputTooltip {
            get {
                return ResourceManager.GetString("Mock_InputTooltip", resourceCulture);
            }
        }

        public static string Mock_Send {
            get {
                return ResourceManager.GetString("Mock_Send", resourceCulture);
            }
        }

        public static string Mock_PreviewHeader {
            get {
                return ResourceManager.GetString("Mock_PreviewHeader", resourceCulture);
            }
        }

        public static string Mock_SaveHtml {
            get {
                return ResourceManager.GetString("Mock_SaveHtml", resourceCulture);
            }
        }

        public static string Mock_Step2Header {
            get {
                return ResourceManager.GetString("Mock_Step2Header", resourceCulture);
            }
        }

        public static string Mock_OutputFolder {
            get {
                return ResourceManager.GetString("Mock_OutputFolder", resourceCulture);
            }
        }

        public static string Mock_Browse {
            get {
                return ResourceManager.GetString("Mock_Browse", resourceCulture);
            }
        }

        public static string Mock_ProjectName {
            get {
                return ResourceManager.GetString("Mock_ProjectName", resourceCulture);
            }
        }

        public static string Mock_OpenFolder {
            get {
                return ResourceManager.GetString("Mock_OpenFolder", resourceCulture);
            }
        }

        public static string Mock_GenerateWpf {
            get {
                return ResourceManager.GetString("Mock_GenerateWpf", resourceCulture);
            }
        }

        public static string MockPreview_EmptyText {
            get {
                return ResourceManager.GetString("MockPreview_EmptyText", resourceCulture);
            }
        }

        public static string MockPreview_UnavailableTitle {
            get {
                return ResourceManager.GetString("MockPreview_UnavailableTitle", resourceCulture);
            }
        }

        public static string MockPreview_UnavailableMessage {
            get {
                return ResourceManager.GetString("MockPreview_UnavailableMessage", resourceCulture);
            }
        }

        public static string Mock_CodexNotConnected {
            get {
                return ResourceManager.GetString("Mock_CodexNotConnected", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_InProgress {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_InProgress", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ConfirmHtml {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ConfirmHtml", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ClaudeCodeOnly {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ClaudeCodeOnly", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ClaudeCli {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ClaudeCli", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_Dotnet {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_Dotnet", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_OutputFolder {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_OutputFolder", resourceCulture);
            }
        }

        public static string Mock_DisabledReason_ProjectName {
            get {
                return ResourceManager.GetString("Mock_DisabledReason_ProjectName", resourceCulture);
            }
        }

        public static string Mock_ConversationStarted {
            get {
                return ResourceManager.GetString("Mock_ConversationStarted", resourceCulture);
            }
        }

        public static string Mock_SendFailedFormat {
            get {
                return ResourceManager.GetString("Mock_SendFailedFormat", resourceCulture);
            }
        }

        public static string Mock_HtmlFileFilter {
            get {
                return ResourceManager.GetString("Mock_HtmlFileFilter", resourceCulture);
            }
        }

        public static string Mock_HtmlSaved {
            get {
                return ResourceManager.GetString("Mock_HtmlSaved", resourceCulture);
            }
        }

        public static string Mock_HtmlSaveFailedFormat {
            get {
                return ResourceManager.GetString("Mock_HtmlSaveFailedFormat", resourceCulture);
            }
        }

        public static string Mock_PickOutputFolderTitle {
            get {
                return ResourceManager.GetString("Mock_PickOutputFolderTitle", resourceCulture);
            }
        }

        public static string Mock_OutputFolderNotEmpty {
            get {
                return ResourceManager.GetString("Mock_OutputFolderNotEmpty", resourceCulture);
            }
        }

        public static string Mock_GeneratingProject {
            get {
                return ResourceManager.GetString("Mock_GeneratingProject", resourceCulture);
            }
        }

        public static string Mock_GenerationErrorLogFormat {
            get {
                return ResourceManager.GetString("Mock_GenerationErrorLogFormat", resourceCulture);
            }
        }

        public static string Mock_GenerationFailedFormat {
            get {
                return ResourceManager.GetString("Mock_GenerationFailedFormat", resourceCulture);
            }
        }

        public static string Mock_MockUpdated {
            get {
                return ResourceManager.GetString("Mock_MockUpdated", resourceCulture);
            }
        }

        public static string Mock_UpdateNoteFormat {
            get {
                return ResourceManager.GetString("Mock_UpdateNoteFormat", resourceCulture);
            }
        }

        public static string Mock_ResponseCompleted {
            get {
                return ResourceManager.GetString("Mock_ResponseCompleted", resourceCulture);
            }
        }

        public static string Mock_ErrorSystemFormat {
            get {
                return ResourceManager.GetString("Mock_ErrorSystemFormat", resourceCulture);
            }
        }

        public static string Mock_ErrorStatusFormat {
            get {
                return ResourceManager.GetString("Mock_ErrorStatusFormat", resourceCulture);
            }
        }

        public static string Mock_Interrupted {
            get {
                return ResourceManager.GetString("Mock_Interrupted", resourceCulture);
            }
        }

        public static string Mock_PreviewUpdateFailedFormat {
            get {
                return ResourceManager.GetString("Mock_PreviewUpdateFailedFormat", resourceCulture);
            }
        }

        public static string Mock_ErrorUnknown {
            get {
                return ResourceManager.GetString("Mock_ErrorUnknown", resourceCulture);
            }
        }

        public static string Mock_Run_Start {
            get {
                return ResourceManager.GetString("Mock_Run_Start", resourceCulture);
            }
        }

        public static string Mock_Run_OutputFolderFormat {
            get {
                return ResourceManager.GetString("Mock_Run_OutputFolderFormat", resourceCulture);
            }
        }

        public static string Mock_Run_ProjectNameFormat {
            get {
                return ResourceManager.GetString("Mock_Run_ProjectNameFormat", resourceCulture);
            }
        }

        public static string Mock_Run_TimedOutFormat {
            get {
                return ResourceManager.GetString("Mock_Run_TimedOutFormat", resourceCulture);
            }
        }

        public static string Mock_Run_Canceled {
            get {
                return ResourceManager.GetString("Mock_Run_Canceled", resourceCulture);
            }
        }

        public static string Mock_Run_ClientCompleted {
            get {
                return ResourceManager.GetString("Mock_Run_ClientCompleted", resourceCulture);
            }
        }

        public static string Mock_Run_ClientFailedFormat {
            get {
                return ResourceManager.GetString("Mock_Run_ClientFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Run_ArtifactsFound {
            get {
                return ResourceManager.GetString("Mock_Run_ArtifactsFound", resourceCulture);
            }
        }

        public static string Mock_Run_ArtifactsMissing {
            get {
                return ResourceManager.GetString("Mock_Run_ArtifactsMissing", resourceCulture);
            }
        }

        public static string Mock_Run_BuildVerify {
            get {
                return ResourceManager.GetString("Mock_Run_BuildVerify", resourceCulture);
            }
        }

        public static string Mock_Run_BuildSucceeded {
            get {
                return ResourceManager.GetString("Mock_Run_BuildSucceeded", resourceCulture);
            }
        }

        public static string Mock_Run_BuildFailed {
            get {
                return ResourceManager.GetString("Mock_Run_BuildFailed", resourceCulture);
            }
        }

        public static string Mock_Run_BuildVerifyCanceled {
            get {
                return ResourceManager.GetString("Mock_Run_BuildVerifyCanceled", resourceCulture);
            }
        }

        public static string Mock_Result_Success {
            get {
                return ResourceManager.GetString("Mock_Result_Success", resourceCulture);
            }
        }

        public static string Mock_Result_TimedOut {
            get {
                return ResourceManager.GetString("Mock_Result_TimedOut", resourceCulture);
            }
        }

        public static string Mock_Result_Canceled {
            get {
                return ResourceManager.GetString("Mock_Result_Canceled", resourceCulture);
            }
        }

        public static string Mock_Result_NotLoggedIn {
            get {
                return ResourceManager.GetString("Mock_Result_NotLoggedIn", resourceCulture);
            }
        }

        public static string Mock_Result_ClientFailedFormat {
            get {
                return ResourceManager.GetString("Mock_Result_ClientFailedFormat", resourceCulture);
            }
        }

        public static string Mock_Result_ArtifactsMissing {
            get {
                return ResourceManager.GetString("Mock_Result_ArtifactsMissing", resourceCulture);
            }
        }

        public static string Mock_Result_BuildFailed {
            get {
                return ResourceManager.GetString("Mock_Result_BuildFailed", resourceCulture);
            }
        }

        public static string Mock_Result_Failed {
            get {
                return ResourceManager.GetString("Mock_Result_Failed", resourceCulture);
            }
        }

        public static string Mock_DotnetStartFailed {
            get {
                return ResourceManager.GetString("Mock_DotnetStartFailed", resourceCulture);
            }
        }

        public static string Mock_ScaffoldFailedFormat {
            get {
                return ResourceManager.GetString("Mock_ScaffoldFailedFormat", resourceCulture);
            }
        }
    }
}
