// <auto-generated />
// このファイルは QuickER の Scriban テンプレート（Templates/CSharpRuntime.scriban）から生成される
// ランタイムパッケージ用ソースです。手で編集しないでください（再生成で上書きされます）。
#nullable enable

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Common;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using QuickER.Runtime;

namespace QuickER.Runtime.EntityFrameworkCore;

/// <summary>エンティティ型の属性からテーブル・カラム情報、CRUD 用 SQL、カスケード子ナビゲーションを構築・保持し、行マッピングとパラメータ束縛を提供するメタデータ</summary>
/// <remarks>型をキーに 1 度だけ構築しキャッシュする（リフレクションコスト削減）。Repository の CRUD・グラフ保存・JSON クエリプランナ・カスケード削除プランナが共用する</remarks>
public sealed class EntitySaveMetadata
{
    private static readonly ConcurrentDictionary<Type, EntitySaveMetadata> _cache = new();

    /// <summary>主キーに対応するプロパティ</summary>
    public required PropertyInfo KeyProperty { get; init; }

    /// <summary>マッピング対象の全カラムプロパティ（ナビゲーション・基底プロパティ除く）。INSERT / BulkInsert は常にこれを使う</summary>
    public required IReadOnlyList<PropertyInfo> AllProperties { get; init; }

    /// <summary>SELECT / UPDATE 対象の列プロパティ（全列から無制限バイナリ列を除いたもの。除外列なしは全列と一致）。行マッピングで使う</summary>
    public required IReadOnlyList<PropertyInfo> SelectProperties { get; init; }

    /// <summary>SELECT / UPDATE から除外する無制限バイナリ列（<see cref="UnboundedBinaryColumnAttribute"/> 付き）。除外列なしは空</summary>
    public required IReadOnlyList<PropertyInfo> ExcludedProperties { get; init; }

    /// <summary>SELECT 対象列の (プロパティ, カラム名) をビルド時に確定した配列。行マッピングは列名解決を都度リフレクションせずこれを列挙する</summary>
    public required IReadOnlyList<(PropertyInfo Property, string ColumnName)> SelectColumns { get; init; }

    /// <summary>列プロパティ → カラム名の確定済み対応（射影・除外列など任意プロパティ列の列名解決に使う）</summary>
    public required IReadOnlyDictionary<PropertyInfo, string> ColumnNameByProperty { get; init; }

    /// <summary>カラム名 → 列プロパティの対応（クエリ WHERE 句パラメータの型明示化で列型を引くのに使う）</summary>
    public required IReadOnlyDictionary<string, PropertyInfo> PropertyByColumn { get; init; }

    /// <summary>SELECT 用の角括弧付きカラム一覧（例: [id], [name]）</summary>
    public required string ColumnList { get; init; }

    /// <summary>カスケード対象の子ナビゲーション</summary>
    public required IReadOnlyList<CascadeNavigation> CascadeNavigations { get; init; }

    /// <summary>指定型のメタデータを取得する（型ごとに 1 度だけ構築しキャッシュ）</summary>
    public static EntitySaveMetadata For(Type entityType) => _cache.GetOrAdd(entityType, Build);

    /// <summary>ナビゲーションプロパティ → <see cref="NavigationReferenceAttribute"/> の解決をプロパティ単位でキャッシュする</summary>
    private static readonly ConcurrentDictionary<
        PropertyInfo,
        NavigationReferenceAttribute?
    > _navigationAttributeCache = new();

    /// <summary>ナビゲーションプロパティの <see cref="NavigationReferenceAttribute"/> を取得する（Include 解決で毎ノード反射しないようキャッシュ）</summary>
    public static NavigationReferenceAttribute? NavigationAttribute(PropertyInfo property) =>
        _navigationAttributeCache.GetOrAdd(
            property,
            static p => p.GetCustomAttribute<NavigationReferenceAttribute>()
        );

    private static EntitySaveMetadata Build(Type entityType)
    {
        var tableAttribute =
            entityType.GetCustomAttribute<TableAttribute>()
            ?? throw new InvalidOperationException(
                $"{entityType.Name} に [Table] 属性が必要です。"
            );
        var allProperties = entityType
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToList();
        var columns = allProperties
            .Where(property =>
                property.CanRead
                && property.CanWrite
                && property.DeclaringType != typeof(EntityBase)
                && property.GetCustomAttribute<NavigationReferenceAttribute>() is null
            )
            .ToList();
        var keyProperties = columns
            .Where(property => property.GetCustomAttribute<KeyAttribute>() is not null)
            .ToList();
        var keyProperty = keyProperties.Count switch
        {
            0 => throw new InvalidOperationException(
                $"{entityType.Name} に [Key] 属性付きプロパティが必要です。"
            ),
            1 => keyProperties[0],
            _ => throw new InvalidOperationException(
                $"{entityType.Name} の [Key] 属性付きプロパティは 1 つのみ許可されます（複合キーは Repository 非対応。対象: {string.Join(", ", keyProperties.Select(property => property.Name))}）。"
            ),
        };
        // 無制限バイナリ列（UnboundedBinaryColumnAttribute）を SELECT / UPDATE から外す。全列（AllProperties）は
        // INSERT / BulkInsert のため保持し、SELECT 用列集合（selectProperties）だけを縮小する。除外列なしは全列と一致
        var excludedColumns = columns
            .Where(property =>
                property.GetCustomAttribute<UnboundedBinaryColumnAttribute>() is not null
            )
            .ToList();
        var selectProperties =
            excludedColumns.Count == 0
                ? columns
                : columns.Where(property => !excludedColumns.Contains(property)).ToList();
        var columnList = string.Join(", ", selectProperties.Select(property => $"[{GetColumnName(property)}]"));
        var cascades = allProperties
            .Select(property =>
                (property, attribute: property.GetCustomAttribute<NavigationReferenceAttribute>())
            )
            .Where(pair => pair.attribute is { Cascade: true })
            .Select(pair => new CascadeNavigation(
                pair.property,
                pair.attribute!.IsCollection,
                pair.attribute.IsCollection
                    ? pair.property.PropertyType.GetGenericArguments()[0]
                    : pair.property.PropertyType,
                pair.attribute.PrincipalColumn,
                pair.attribute.DependentColumn
            ))
            .ToList();

        return new EntitySaveMetadata
        {
            KeyProperty = keyProperty,
            AllProperties = columns,
            SelectProperties = selectProperties,
            ExcludedProperties = excludedColumns,
            // 行マッピングの列名解決をビルド時に確定させ、行ごとの [Column] リフレクションを排除する
            SelectColumns = selectProperties.Select(property => (property, GetColumnName(property))).ToList(),
            ColumnNameByProperty = columns.ToDictionary(property => property, GetColumnName),
            // SelectColumns（固定 SELECT 集合）用の式木マテリアライザを型ごとに 1 度だけコンパイルする
            SelectMaterializer = BuildSelectMaterializer(entityType, selectProperties),
            PropertyByColumn = columns.ToDictionary(
                GetColumnName,
                property => property,
                StringComparer.Ordinal
            ),
            ColumnList = columnList,
            CascadeNavigations = cascades,
        };
    }

    // ===== 行マテリアライザ（式木コンパイル・ホットパスのリフレクション除去） =====

    /// <summary><see cref="DbDataReader.GetValue(int)"/> の解決済み <see cref="MethodInfo"/>（型特化できない列のフォールバックで使う）</summary>
    private static readonly MethodInfo _getValueMethod = typeof(DbDataReader).GetMethod(
        nameof(DbDataReader.GetValue),
        new[] { typeof(int) }
    )!;

    /// <summary><see cref="SetColumnValue"/> の解決済み <see cref="MethodInfo"/>（型特化できない列のフォールバックで呼ぶ）</summary>
    private static readonly MethodInfo _setColumnValueMethod = typeof(EntitySaveMetadata).GetMethod(
        nameof(SetColumnValue),
        BindingFlags.NonPublic | BindingFlags.Static
    )!;

    /// <summary><see cref="EntityBase.RowState"/> の解決済み <see cref="PropertyInfo"/></summary>
    private static readonly PropertyInfo _rowStateProperty = typeof(EntityBase).GetProperty(
        nameof(EntityBase.RowState)
    )!;

    /// <summary>SelectColumns（固定 SELECT 集合）1 行分を式木コンパイル済みでマテリアライズするデリゲート（型ごとに 1 度構築しキャッシュ）</summary>
    /// <remarks>引数は <c>(reader, ordinals)</c>。<c>ordinals</c> は SelectColumns と同順の列 ordinal で、行ループの前に 1 度だけ解決する。</remarks>
    public required Func<DbDataReader, int[], EntityBase> SelectMaterializer { get; init; }

    /// <summary>
    /// SelectColumns（固定 SELECT 集合）の 1 行を、事前解決した ordinal 配列を用いてエンティティへマテリアライズする
    /// 式木コンパイル済みデリゲートを構築する（型ごとに 1 度）。
    /// </summary>
    /// <remarks>
    /// 型特化アクセサを持つ列はボクシングなしで直接読み（<c>DBNull</c> は既定値＝従来の <c>SetValue(null)</c> と同値）、
    /// それ以外の列は従来の <see cref="SetColumnValue"/>（方言別変換／値オブジェクト包み直し）へフォールバックする。
    /// 生成される最終状態（<c>RowState = Unchanged</c>）は従来の行マッピングと一致する。
    /// </remarks>
    private static Func<DbDataReader, int[], EntityBase> BuildSelectMaterializer(
        Type entityType,
        IReadOnlyList<PropertyInfo> properties
    )
    {
        var readerParam = Expression.Parameter(typeof(DbDataReader), "reader");
        var ordinalsParam = Expression.Parameter(typeof(int[]), "ordinals");
        var entityVar = Expression.Variable(entityType, "entity");

        var body = new List<Expression>
        {
            Expression.Assign(entityVar, Expression.New(entityType)),
        };

        for (var i = 0; i < properties.Count; i++)
        {
            var ordinal = Expression.ArrayIndex(ordinalsParam, Expression.Constant(i));
            body.Add(BuildColumnAssign(entityVar, readerParam, ordinal, properties[i]));
        }

        // DB から読み込んだ行は変更なし扱いにする（従来の行マッピングと同じ事後状態）
        body.Add(
            Expression.Assign(
                Expression.Property(entityVar, _rowStateProperty),
                Expression.Constant(RowState.Unchanged)
            )
        );
        body.Add(Expression.Convert(entityVar, typeof(EntityBase)));

        var block = Expression.Block(typeof(EntityBase), new[] { entityVar }, body);
        return Expression
            .Lambda<Func<DbDataReader, int[], EntityBase>>(block, readerParam, ordinalsParam)
            .Compile();
    }

    /// <summary>1 列分の代入式を作る。型特化できる列はボクシングなしで直接読み、それ以外は <see cref="SetColumnValue"/> へフォールバックする</summary>
    private static Expression BuildColumnAssign(
        Expression entityExpr,
        ParameterExpression readerParam,
        Expression ordinal,
        PropertyInfo property
    )
    {

        // フォールバック: 従来の SetColumnValue（DBNull→null／方言別変換／値オブジェクト包み直し）を ordinal 経由で呼ぶ
        return Expression.Call(
            _setColumnValueMethod,
            Expression.Convert(entityExpr, typeof(EntityBase)),
            Expression.Constant(property, typeof(PropertyInfo)),
            Expression.Call(readerParam, _getValueMethod, ordinal)
        );
    }

    /// <summary>SelectColumns の各列名を、このリーダー上の ordinal へ 1 度だけ解決する（行ループの前に呼ぶ）</summary>
    public int[] SelectOrdinals(DbDataReader reader)
    {
        var ordinals = new int[SelectColumns.Count];

        for (var i = 0; i < ordinals.Length; i++)
        {
            ordinals[i] = reader.GetOrdinal(SelectColumns[i].ColumnName);
        }

        return ordinals;
    }

    /// <summary>データリーダーの 1 行をエンティティへマッピングする（ordinal 事前解決版・ホットループ用）</summary>
    public TEntity MapEntity<TEntity>(
        DbDataReader reader,
        int[] ordinals
    )
        where TEntity : EntityBase => (TEntity)SelectMaterializer(reader, ordinals);

    /// <summary>データリーダーの 1 行をエンティティへマッピングする（SelectColumns の ordinal を都度解決する単一行版）</summary>
    public TEntity MapEntity<TEntity>(DbDataReader reader)
        where TEntity : EntityBase, new() => (TEntity)SelectMaterializer(reader, SelectOrdinals(reader));

    /// <summary>
    /// 生 SQL 用の厳密な行マッピング（列集合・列型が可変のため型特化せず、従来の寛容な <see cref="SetColumnValue"/> を使う）。
    /// </summary>
    private TEntity MapEntityStrict<TEntity>(DbDataReader reader)
        where TEntity : EntityBase, new()
    {
        var entity = new TEntity();

        // 無制限バイナリ列は既定で SELECT 除外のため SelectColumns（＝SelectProperties の確定済み対応）のみをマップする
        foreach (var (property, columnName) in SelectColumns)
        {
            SetColumnValue(entity, property, reader[columnName]);
        }

        // DB から読み込んだ行は変更なし扱いにする（その後の編集で Updated に遷移）
        entity.RowState = RowState.Unchanged;
        return entity;
    }

    /// <summary>
    /// 読み取った列値を対象プロパティへ設定する（行マッピングの共通処理）。<c>DBNull</c> は <c>null</c> を代入し、
    /// それ以外は値オブジェクトの包み直し／SQLite の格納型寄せ／SQL Server の素通しを方言に応じて行う。
    /// </summary>
    private static void SetColumnValue(EntityBase entity, PropertyInfo property, object value)
    {
        if (value is DBNull)
        {
            property.SetValue(entity, null);
        }
        else
        {
            // 値オブジェクトは内包型へ変換して包み直す（Wrap 内で Convert.ChangeType 済み）
            property.SetValue(entity, SqlValueObjectActivator.Wrap(value, property.PropertyType));
        }
    }

    /// <summary>
    /// 生 SQL の結果行を {TEntity} へマップする。<see cref="MapEntityStrict"/> と同じ厳密マッピング（SELECT 対象列は必須）だが、
    /// 列不足（部分 SELECT）で列が引けなかった場合は、必要な列を含む <see cref="InvalidOperationException"/> でラップして
    /// 分かりやすくする。未知の列参照で投げられる例外はデータリーダーの実装で異なる
    /// （<see cref="IndexOutOfRangeException"/> と <see cref="ArgumentOutOfRangeException"/>）ため両方を捕捉する。
    /// 無制限バイナリ列は既定では取得しないが、生 SQL の SELECT に明示的に含まれていれば追加でマップする（ユーザーが意図して選んだ場合に取得できる）。
    /// </summary>
    public TEntity MapEntityFromRawSql<TEntity>(DbDataReader reader)
        where TEntity : EntityBase, new()
    {
        TEntity entity;

        try
        {
            entity = MapEntityStrict<TEntity>(reader);
        }
        catch (Exception ex) when (ex is IndexOutOfRangeException or ArgumentOutOfRangeException)
        {
            throw new InvalidOperationException(
                $"生 SQL の SELECT には {typeof(TEntity).Name} の列（{ColumnList}）が必要です（SELECT * または全列指定）。"
                    + $"結果セットに不足している列があります: {ex.Message}",
                ex
            );
        }

        // 除外列（無制限バイナリ）が生 SQL の結果に含まれていれば opportunistic に取り込む
        if (ExcludedProperties.Count > 0)
        {
            var present = RawReaderColumnNames(reader);

            foreach (var property in ExcludedProperties)
            {
                var columnName = ColumnNameByProperty[property];

                if (!present.Contains(columnName))
                {
                    continue;
                }

                SetColumnValue(entity, property, reader[columnName]);
            }

            // opportunistic な代入で状態が動かないよう変更なしを再確定する（列プロパティは素の auto-property だが念のため）
            entity.RowState = RowState.Unchanged;
        }

        return entity;
    }

    /// <summary>データリーダーの列名集合を大文字小文字無視で 1 度だけ列挙する（生 SQL の除外列有無判定に使う）</summary>
    private static HashSet<string> RawReaderColumnNames(DbDataReader reader)
    {
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        for (var i = 0; i < reader.FieldCount; i++)
        {
            names.Add(reader.GetName(i));
        }

        return names;
    }

    /// <summary>
    /// 射影セレクタが参照する列プロパティ名集合を、SELECT すべき列プロパティ（<see cref="PropertyInfo"/>）へ解決する。
    /// 参照がすべて列プロパティ（無制限バイナリ列を含む）なら順序どおりの一覧を返し、1 つでもナビゲーション等の
    /// 非列名が混じる、あるいは参照が 0 件なら <c>null</c>（＝サーバー側列刈り込み不可・従来経路へフォールバック）を返す。
    /// </summary>
    public IReadOnlyList<PropertyInfo>? ResolveProjectionColumns(
        IReadOnlyCollection<string> propertyNames
    )
    {
        // 参照列が 0 件だと SELECT する列が無くフォールバックが必要（例: 定数のみの射影）
        if (propertyNames.Count == 0)
        {
            return null;
        }

        var resolved = new List<PropertyInfo>(propertyNames.Count);

        foreach (var name in propertyNames)
        {
            // 全列（AllProperties）から名前一致で引く（除外＝無制限バイナリ列も射影が参照していれば取得対象にする）
            var property = AllProperties.FirstOrDefault(candidate => candidate.Name == name);

            if (property is null)
            {
                // 列でない（ナビゲーション等）が混じった＝安全に刈り込めない
                return null;
            }

            resolved.Add(property);
        }

        return resolved;
    }

    private static string GetColumnName(PropertyInfo property) =>
        property.GetCustomAttribute<ColumnAttribute>()?.Name ?? property.Name;

    /// <summary>C# プロパティ名から対応する列プロパティを引く（無制限バイナリ列＝除外列を含む全列から探す）。Stream アクセサが Repository / インメモリ双方で使う</summary>
    public PropertyInfo ColumnByPropertyName(string propertyName) =>
        AllProperties.FirstOrDefault(property => property.Name == propertyName)
        ?? throw new InvalidOperationException(
            $"プロパティ {propertyName} は列として見つかりませんでした。"
        );
}

/// <summary>1 回の Save 呼び出しの間だけ生きる Save フックのセッション（レジストリ・context ファクトリ・スキップ集合を持ち回る）</summary>
/// <remarks>
/// context ファクトリはバックエンド（QuickER 方言・EF Core・InMemory）が進行中のトランザクション文脈を閉じ込めて渡す。
/// スキップ集合は参照等価（<see cref="ReferenceEqualityComparer"/>）で追跡し、コミット後の <c>AcceptChanges</c> で状態据え置きに使う。
/// </remarks>
public sealed class SaveHookSession(
    ISaveHookRegistry registry,
    Func<EntityBase, ISaveHookContext> contextFactory
)
{
    private readonly ISaveHookRegistry _registry = registry;
    private readonly Func<EntityBase, ISaveHookContext> _contextFactory = contextFactory;
    private readonly HashSet<EntityBase> _skipped = new(ReferenceEqualityComparer.Instance);

    /// <summary>Before で <c>false</c>（スキップ）されたエンティティ集合（参照等価）。AcceptChanges の状態据え置きに使う</summary>
    public IReadOnlySet<EntityBase> Skipped => _skipped;

    /// <summary>エンティティをスキップ集合へ追加する</summary>
    public void Skip(EntityBase entity) => _skipped.Add(entity);

    /// <summary>登録順に Before を呼び最初の <c>false</c> で短絡する（フックが無い型は <c>true</c>）</summary>
    public Task<bool> InvokeBeforeAsync(
        EntityBase entity,
        SaveOperation operation,
        CancellationToken cancellationToken
    )
    {
        var invoker = _registry.GetInvoker(entity.GetType());
        return invoker is null
            ? Task.FromResult(true)
            : invoker.InvokeBeforeAsync(entity, operation, cancellationToken);
    }

    /// <summary>登録順に After を呼ぶ（フックが無い型は何もしない）。context はエンティティ型に束縛して生成する</summary>
    public Task InvokeAfterAsync(
        EntityBase entity,
        SaveOperation operation,
        CancellationToken cancellationToken
    )
    {
        var invoker = _registry.GetInvoker(entity.GetType());
        return invoker is null
            ? Task.CompletedTask
            : invoker.InvokeAfterAsync(
                entity,
                operation,
                _contextFactory(entity),
                cancellationToken
            );
    }
}

/// <summary>RowState に従ってエンティティのグラフを 1 トランザクションで保存する内部エンジン</summary>
public static class EntityGraphSaver
{
    /// <summary>自身、または（cascade 時）子に変更があるか</summary>
    public static bool HasChanges(EntityBase entity, bool cascade) =>
        entity.HasChanges
        || (cascade && EnumerateCascadeChildren(entity).Any(child => HasChanges(child, true)));

    /// <summary>コミット後に保存済みエンティティを Unchanged に確定する</summary>
    public static void AcceptChanges(EntityBase entity, bool cascade) =>
        AcceptChanges(entity, cascade, null);

    /// <summary>
    /// コミット後に保存済みエンティティを Unchanged に確定する。<paramref name="skip"/> に含まれるエンティティ
    /// （Save フックの Before が <c>false</c> を返してスキップされた行）は操作していないため状態を据え置く。
    /// </summary>
    public static void AcceptChanges(
        EntityBase entity,
        bool cascade,
        IReadOnlySet<EntityBase>? skip
    )
    {
        if (entity.IsRemoved)
        {
            return;
        }

        // スキップされたエンティティは INSERT / UPDATE を行っていないため RowState を据え置く
        if (skip is null || !skip.Contains(entity))
        {
            entity.MarkUnchanged();
        }

        if (cascade)
        {
            foreach (var child in EnumerateCascadeChildren(entity))
            {
                AcceptChanges(child, true, skip);
            }
        }
    }

    /// <summary>カスケード対象の子エンティティを列挙する（null は除外）</summary>
    private static IEnumerable<EntityBase> EnumerateCascadeChildren(EntityBase entity)
    {
        foreach (var navigation in EntitySaveMetadata.For(entity.GetType()).CascadeNavigations)
        {
            var value = navigation.Property.GetValue(entity);

            if (value is null)
            {
                continue;
            }

            if (navigation.IsCollection)
            {
                if (value is IEnumerable<EntityBase> children)
                {
                    foreach (var child in children)
                    {
                        if (child is not null)
                        {
                            yield return child;
                        }
                    }
                }
            }
            else if (value is EntityBase child)
            {
                yield return child;
            }
        }
    }
}

/// <summary>
/// 文字列値オブジェクト（<see cref="ValueObjectStringBase{TSelf}"/> 由来）の Contains/StartsWith/EndsWith を
/// SQL の LIKE へ翻訳する EF Core メソッド呼び出しトランスレータ。
/// </summary>
/// <remarks>
/// <para>
/// 値オブジェクト列はコンバータで string 列へ射影されるが、EF Core 既定ではこれらのインスタンスメソッドを翻訳できない。
/// QuickER の SQL Server 実装と同じ意味論（Ordinal 部分一致 → LIKE・ワイルドカード <c>\ % _ [</c> のエスケープ・
/// <c>ESCAPE '\'</c>・null 引数は空文字扱い）に合わせて <c>ISqlExpressionFactory.Like</c> を生成する。
/// </para>
/// <para>
/// 引数は string オーバーロードと TSelf（値オブジェクト）オーバーロードの両方を受け付ける。定数はクライアント側で
/// エスケープし、パラメータは REPLACE の連鎖（方言非依存）で SQL 側エスケープする。
/// </para>
/// </remarks>
public sealed class ValueObjectStringMethodTranslator(
    ISqlExpressionFactory sqlExpressionFactory,
    RelationalTypeMapping stringTypeMapping,
    LikeEscapeBehavior escapeBehavior
) : IMethodCallTranslator
{
    private readonly ISqlExpressionFactory _sqlExpressionFactory = sqlExpressionFactory;
    private readonly RelationalTypeMapping _stringTypeMapping = stringTypeMapping;
    private readonly LikeEscapeBehavior _escapeBehavior = escapeBehavior;

    /// <summary>
    /// REPLACE で順にエスケープする（元文字, 置換後）の組。エスケープ文字自身を最初に二重化する。
    /// <c>[</c> は SQL Server のみ文字クラス開始のためエスケープ対象で、他方言（<c>[</c> はワイルドカードでない）では
    /// エスケープしない。特に Oracle は非ワイルドカードのエスケープを ORA-01424 で拒否するため <c>[</c> を含めてはならない。
    /// エスケープ文字は方言依存で、MySQL は文字列リテラルでバックスラッシュがクォート打ち消しとして
    /// 誤解釈されるため <c>\</c> 以外（<see cref="LikeEscapeBehavior.EscapeChar"/>）を用いる。
    /// </summary>
    private IEnumerable<(string From, string To)> EscapePairs()
    {
        var e = _escapeBehavior.EscapeChar;

        // エスケープ文字自身 → 二重化（必ず最初に処理する）
        yield return (e, e + e);
        yield return ("%", e + "%");
        yield return ("_", e + "_");

        if (_escapeBehavior.EscapeBracket)
        {
            yield return ("[", e + "[");
        }
    }

    /// <summary>対象メソッドなら LIKE 式を返し、そうでなければ null（他トランスレータに委ねる）</summary>
    public SqlExpression? Translate(
        SqlExpression? instance,
        MethodInfo method,
        IReadOnlyList<SqlExpression> arguments,
        IDiagnosticsLogger<DbLoggerCategory.Query> logger
    )
    {
        // 文字列値オブジェクトの単一引数 Contains / StartsWith / EndsWith のみを対象にする
        if (
            instance is null
            || arguments.Count != 1
            || method.Name is not ("Contains" or "StartsWith" or "EndsWith")
            || method.DeclaringType is not { IsGenericType: true } declaring
            || declaring.GetGenericTypeDefinition() != typeof(ValueObjectStringBase<>)
        )
        {
            return null;
        }

        // 引数のマッピングを決める。string 引数は素の string、TSelf 引数は列と同じコンバータ付き
        // マッピング（VO→素値変換）で束縛する
        var parameterType = method.GetParameters()[0].ParameterType;
        SqlExpression argument;

        if (parameterType == typeof(string))
        {
            argument = _sqlExpressionFactory.ApplyTypeMapping(arguments[0], _stringTypeMapping);
        }
        else if (parameterType == declaring.GetGenericArguments()[0])
        {
            argument = _sqlExpressionFactory.ApplyTypeMapping(arguments[0], instance.TypeMapping);
        }
        else
        {
            return null;
        }

        // 列を素の string としてコアースし、コンバータ経由の再読込（string→VO の不正キャスト）を避ける
        var column = _sqlExpressionFactory.ApplyTypeMapping(instance, _stringTypeMapping);
        var pattern = BuildLikePattern(method.Name, argument);

        // ESCAPE の明示は方言依存。既定エスケープ文字が既にバックスラッシュの PostgreSQL では明示しない。
        // SQL Server / Oracle は既定にエスケープ文字を持たないため明示する。MySQL は文字列リテラルの
        // バックスラッシュ誤解釈を避けるためエスケープ文字を \ 以外にしたうえで明示する。
        var escapeChar = _escapeBehavior.EmitEscapeClause
            ? _sqlExpressionFactory.Constant(_escapeBehavior.EscapeChar, _stringTypeMapping)
            : null;

        return _sqlExpressionFactory.Like(column, pattern, escapeChar);
    }

    /// <summary>メソッド名に応じた LIKE パターン式（'%'＋エスケープ済み引数＋'%' 等）を組み立てる</summary>
    private SqlExpression BuildLikePattern(string methodName, SqlExpression argument)
    {
        // 定数はクライアント側でエスケープして 1 つの定数パターンへ畳み込む（QuickER 版と同じ形）。
        // TSelf オーバーロードの定数（EF Core が Create(...) を定数へ畳んだもの）は素値へ開いてから扱う
        if (argument is SqlConstantExpression { Value: var constantValue })
        {
            var raw = SqlParameterValue.Unwrap(constantValue) as string ?? string.Empty;
            var escaped = EscapeLikePattern(raw);
            var constantPattern = methodName switch
            {
                "Contains" => "%" + escaped + "%",
                "StartsWith" => escaped + "%",
                _ => "%" + escaped,
            };
            return _sqlExpressionFactory.Constant(constantPattern, _stringTypeMapping);
        }

        // パラメータ等は SQL 側でエスケープする。null は QuickER 版（null→空文字）に合わせ COALESCE で空文字へ
        SqlExpression escapedArgument = _sqlExpressionFactory.Coalesce(
            argument,
            _sqlExpressionFactory.Constant(string.Empty, _stringTypeMapping)
        );

        foreach (var (from, to) in EscapePairs())
        {
            escapedArgument = _sqlExpressionFactory.Function(
                "REPLACE",
                [
                    escapedArgument,
                    _sqlExpressionFactory.Constant(from, _stringTypeMapping),
                    _sqlExpressionFactory.Constant(to, _stringTypeMapping),
                ],
                nullable: true,
                argumentsPropagateNullability: [true, false, false],
                typeof(string),
                _stringTypeMapping
            );
        }

        var wildcard = _sqlExpressionFactory.Constant("%", _stringTypeMapping);
        return methodName switch
        {
            "Contains" => _sqlExpressionFactory.Add(
                wildcard,
                _sqlExpressionFactory.Add(escapedArgument, wildcard)
            ),
            "StartsWith" => _sqlExpressionFactory.Add(escapedArgument, wildcard),
            _ => _sqlExpressionFactory.Add(wildcard, escapedArgument),
        };
    }

    /// <summary>
    /// LIKE のワイルドカードをエスケープする（定数パターン用）。エスケープ文字自身・<c>%</c>・<c>_</c> は全方言共通、
    /// <c>[</c> は SQL Server のみ（<see cref="LikeEscapeBehavior.EscapeBracket"/>）対象にする。
    /// エスケープ文字は方言依存（<see cref="LikeEscapeBehavior.EscapeChar"/>）。
    /// </summary>
    private string EscapeLikePattern(string value)
    {
        var e = _escapeBehavior.EscapeChar;
        var escaped = value.Replace(e, e + e).Replace("%", e + "%").Replace("_", e + "_");
        return _escapeBehavior.EscapeBracket ? escaped.Replace("[", e + "[") : escaped;
    }
}

/// <summary>
/// 値オブジェクト（<see cref="ValueObjectBase{TSelf, TValue}"/> 由来）の <c>.Value</c> メンバ参照を、
/// 素値の列として翻訳する EF Core メンバトランスレータ。
/// </summary>
/// <remarks>
/// これにより <c>string.IsNullOrEmpty(x.Col.Value)</c> や <c>x.Col.Value &gt; 100</c> のような、素値を開いた
/// 述語を EF Core が翻訳できるようになる（QuickER の SQL Server 実装の「列は素の列でも VO の .Value でもよい」と同じ扱い）。
/// 列はコンバータで素値へ射影済みのため、CONVERT で素値型へ明示コアースし、後段の翻訳が
/// コンバータ経由で再読込（不正キャスト）しないようにする。
/// </remarks>
public sealed class ValueObjectValueMemberTranslator(
    ISqlExpressionFactory sqlExpressionFactory,
    IRelationalTypeMappingSource typeMappingSource
) : IMemberTranslator
{
    private readonly ISqlExpressionFactory _sqlExpressionFactory = sqlExpressionFactory;
    private readonly IRelationalTypeMappingSource _typeMappingSource = typeMappingSource;

    /// <summary>値オブジェクトの .Value なら素値の列として返し、そうでなければ null</summary>
    public SqlExpression? Translate(
        SqlExpression? instance,
        MemberInfo member,
        Type returnType,
        IDiagnosticsLogger<DbLoggerCategory.Query> logger
    )
    {
        if (
            instance is null
            || member.Name != "Value"
            || member.DeclaringType is not { IsGenericType: true } declaring
            || declaring.GetGenericTypeDefinition() != typeof(ValueObjectBase<,>)
        )
        {
            return null;
        }

        // 素値型（string / int / decimal 等）の既定マッピングが得られない型は対象外（他トランスレータに委ねる）
        if (_typeMappingSource.FindMapping(returnType) is not { } typeMapping)
        {
            return null;
        }

        return _sqlExpressionFactory.Convert(instance, returnType, typeMapping);
    }
}

/// <summary>
/// LIKE 述語の方言差（エスケープ文字・<c>[</c> エスケープ・明示 ESCAPE 句）を吸収する挙動。
/// </summary>
/// <remarks>
/// <list type="bullet">
///   <item><see cref="EscapeChar"/>: LIKE のエスケープ文字。既定は <c>\</c>。ただし MySQL は文字列リテラルで
///   バックスラッシュがクォート打ち消しとして誤解釈されるため <c>!</c> を用いる（リテラル・REPLACE・ESCAPE 句すべてで統一）。</item>
///   <item><see cref="EscapeBracket"/>: <c>[</c> をエスケープするか。<c>[</c> が文字クラス開始となる SQL Server のみ true。</item>
///   <item><see cref="EmitEscapeClause"/>: <c>ESCAPE</c> を明示するか。既定エスケープ文字を持たない
///   SQL Server / Oracle / SQLite と、非既定文字を使う MySQL は true。既定が <c>\</c> の PostgreSQL は false（明示不要）。</item>
/// </list>
/// </remarks>
public readonly record struct LikeEscapeBehavior(
    string EscapeChar,
    bool EscapeBracket,
    bool EmitEscapeClause
)
{
    /// <summary>EF Core プロバイダ名から方言別の LIKE エスケープ挙動を決定する</summary>
    public static LikeEscapeBehavior FromProviderName(string? providerName)
    {
        var name = providerName ?? string.Empty;

        // SQL Server: [ は文字クラス開始のためエスケープ必須。既定にエスケープ文字が無いため ESCAPE を明示。
        if (name.Contains("SqlServer", StringComparison.Ordinal))
        {
            return new LikeEscapeBehavior("\\", EscapeBracket: true, EmitEscapeClause: true);
        }

        // Oracle: [ はワイルドカードでないためエスケープしない（ORA-01424 回避）。既定にエスケープ文字が無いため ESCAPE は明示。
        if (name.Contains("Oracle", StringComparison.Ordinal))
        {
            return new LikeEscapeBehavior("\\", EscapeBracket: false, EmitEscapeClause: true);
        }

        // MySQL: 文字列リテラルの \ 誤解釈を避けるためエスケープ文字を ! にし、ESCAPE '!' を明示する。
        if (name.Contains("MySql", StringComparison.OrdinalIgnoreCase))
        {
            return new LikeEscapeBehavior("!", EscapeBracket: false, EmitEscapeClause: true);
        }

        // SQLite: LIKE は既定のエスケープ文字を持たないため ESCAPE を明示する。[ はワイルドカードでない。
        if (name.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
        {
            return new LikeEscapeBehavior("\\", EscapeBracket: false, EmitEscapeClause: true);
        }

        // PostgreSQL 等: [ はワイルドカードでない。既定エスケープ文字が \ のため ESCAPE は明示しない。
        return new LikeEscapeBehavior("\\", EscapeBracket: false, EmitEscapeClause: false);
    }
}

/// <summary>値オブジェクトの文字列翻訳トランスレータ（メソッド・メンバ）を束ねる EF Core プラグイン</summary>
public sealed class ValueObjectTranslatorPlugin
    : IMethodCallTranslatorPlugin,
        IMemberTranslatorPlugin
{
    private readonly IReadOnlyList<IMemberTranslator> _memberTranslators;

    /// <summary>SQL 式ファクトリ・型マッピング源・方言プロバイダからトランスレータ群を構築する</summary>
    public ValueObjectTranslatorPlugin(
        ISqlExpressionFactory sqlExpressionFactory,
        IRelationalTypeMappingSource typeMappingSource,
        IDatabaseProvider databaseProvider
    )
    {
        var stringTypeMapping = typeMappingSource.FindMapping(typeof(string))!;
        var escapeBehavior = LikeEscapeBehavior.FromProviderName(databaseProvider.Name);
        Translators =
        [
            new ValueObjectStringMethodTranslator(
                sqlExpressionFactory,
                stringTypeMapping,
                escapeBehavior
            ),
        ];
        _memberTranslators =
        [
            new ValueObjectValueMemberTranslator(sqlExpressionFactory, typeMappingSource),
        ];
    }

    /// <summary>メソッド呼び出しトランスレータ群</summary>
    public IEnumerable<IMethodCallTranslator> Translators { get; }

    /// <summary>メンバトランスレータ群</summary>
    IEnumerable<IMemberTranslator> IMemberTranslatorPlugin.Translators => _memberTranslators;
}

/// <summary>
/// 値オブジェクトの文字列翻訳プラグインを EF Core の内部サービスコンテナへ登録する DbContext オプション拡張。
/// </summary>
/// <remarks>
/// <see cref="IMethodCallTranslatorPlugin"/> / <see cref="IMemberTranslatorPlugin"/> は EF Core が定義するサービスのため、
/// プロバイダ固有サービスではなく <c>TryAddEnumerable</c> で（既存プラグインを潰さずに）追加する。
/// </remarks>
public sealed class ValueObjectTranslationDbContextOptionsExtension : IDbContextOptionsExtension
{
    private DbContextOptionsExtensionInfo? _info;

    /// <summary>拡張の情報（ログ断片・サービスプロバイダキャッシュキーへの寄与）</summary>
    public DbContextOptionsExtensionInfo Info => _info ??= new ExtensionInfo(this);

    /// <summary>翻訳プラグインを EF Core の内部サービスコンテナへ登録する</summary>
    public void ApplyServices(IServiceCollection services)
    {
        services.AddScoped<ValueObjectTranslatorPlugin>();
        services.TryAddEnumerable(
            ServiceDescriptor.Scoped<IMethodCallTranslatorPlugin, ValueObjectTranslatorPlugin>(
                sp => sp.GetRequiredService<ValueObjectTranslatorPlugin>()
            )
        );
        services.TryAddEnumerable(
            ServiceDescriptor.Scoped<IMemberTranslatorPlugin, ValueObjectTranslatorPlugin>(
                sp => sp.GetRequiredService<ValueObjectTranslatorPlugin>()
            )
        );
    }

    /// <summary>検証は不要（構成に依存する制約は持たない）</summary>
    public void Validate(IDbContextOptions options) { }

    /// <summary>拡張のメタ情報。サービス構成を変えるが方言プロバイダではない</summary>
    private sealed class ExtensionInfo(IDbContextOptionsExtension extension)
        : DbContextOptionsExtensionInfo(extension)
    {
        /// <summary>方言プロバイダ拡張ではない</summary>
        public override bool IsDatabaseProvider => false;

        /// <summary>ログに出す断片</summary>
        public override string LogFragment => "using ValueObjectTranslation ";

        /// <summary>サービスプロバイダのキャッシュキーへの寄与（一定なら同一構成とみなす）</summary>
        public override int GetServiceProviderHashCode() => 0;

        /// <summary>同一サービス構成なら同じサービスプロバイダを再利用してよい</summary>
        public override bool ShouldUseSameServiceProvider(DbContextOptionsExtensionInfo other) =>
            other is ExtensionInfo;

        /// <summary>デバッグ情報へ有効化フラグを載せる</summary>
        public override void PopulateDebugInfo(IDictionary<string, string> debugInfo) =>
            debugInfo["ValueObjectTranslation"] = "1";
    }
}

/// <summary>エンティティに縛られない生 SQL 実行器の EF Core 版（DbContext の接続上で ADO を直接実行する）</summary>
/// <remarks>
/// <para>
/// EF Core の FromSqlRaw / SqlQueryRaw はマッピング規則が既存 SQL Server 版（厳密全列必須・寛容射影・単一値モード）と
/// 一致しないため、<typeparamref name="TContext"/> の <see cref="DbConnection"/> 上で <see cref="DbCommand"/> を
/// 直接実行し、既存版とマッピング・束縛の実装を共有する（意味論は <see cref="ISqlExecutor"/> の定義どおり）。
/// </para>
/// <para>
/// 具象 DbContext には依存せず <typeparamref name="TContext"/>（<see cref="DbContext"/> 派生）で受け取る。
/// 具象型は生成側（DI 登録・エンティティ別実装）で閉じる。
/// </para>
/// <para>ステートレス（コンテキストファクトリのみ保持）のため DI では Singleton 登録できる。</para>
/// </remarks>
/// <typeparam name="TContext">接続を提供する DbContext の具象型</typeparam>
public sealed partial class EfCoreSqlExecutor<TContext>(IDbContextFactory<TContext> contextFactory)
    : ISqlExecutor
    where TContext : DbContext
{
    /// <summary>DbContext の生成元</summary>
    private readonly IDbContextFactory<TContext> _contextFactory = contextFactory;

    /// <summary>生 SQL の SELECT を実行し、結果行を {TEntity} へ厳密（全列必須）にマップして返す</summary>
    public async Task<IReadOnlyList<TEntity>> QueryBySqlAsync<TEntity>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
        where TEntity : EntityBase, new()
    {
        ArgumentNullException.ThrowIfNull(sql);

        var metadata = EntitySaveMetadata.For(typeof(TEntity));
        var items = new List<TEntity>();

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        await using var command = await CreateCommandAsync(
            context,
            sql,
            parameters,
            cancellationToken
        );
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(metadata.MapEntityFromRawSql<TEntity>(reader));
        }

        return items;
    }

    /// <summary>生 SQL の SELECT を実行し、結果行を任意の <typeparamref name="TResult"/> へ寛容に射影して返す</summary>
    public async Task<IReadOnlyList<TResult>> QueryProjectionBySqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        await using var command = await CreateCommandAsync(
            context,
            sql,
            parameters,
            cancellationToken
        );
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        // 射影マッピング（単一値モード・DTO モード）は共有ヘルパーの 1 系統を使う
        return await RawSqlMapper.ReadProjectionRowsAsync<TResult>(reader, cancellationToken);
    }

    /// <summary>生 SQL（UPDATE/DELETE/任意 DML）を実行し、影響行数を返す</summary>
    /// <remarks>
    /// 呼び出しごとに DbContext（接続）を開閉する（トランザクション引数なし）。複数文をアトミックに
    /// 実行したい場合は、1 回の呼び出し内に方言のトランザクション文（BEGIN ... COMMIT 等）を記述すること。
    /// </remarks>
    public async Task<int> ExecuteSqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        await using var command = await CreateCommandAsync(
            context,
            sql,
            parameters,
            cancellationToken
        );

        return await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>生 SQL を実行し、単一のスカラー値を返す（該当なし・DBNull は <c>default</c>）</summary>
    public async Task<TResult?> ExecuteScalarSqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        await using var command = await CreateCommandAsync(
            context,
            sql,
            parameters,
            cancellationToken
        );

        var scalar = await command.ExecuteScalarAsync(cancellationToken);
        return RawSqlMapper.ConvertSingleValue<TResult>(scalar is DBNull ? null : scalar);
    }

    /// <summary>接続を開き、SQL とパラメータを束縛した DbCommand を生成する（束縛規約は SQL Server 版と同一）</summary>
    private static async Task<DbCommand> CreateCommandAsync(
        TContext context,
        string sql,
        object? parameters,
        CancellationToken cancellationToken
    )
    {
        // 接続は DbContext が所有しており、DbContext の破棄で閉じられる
        await context.Database.OpenConnectionAsync(cancellationToken);

        var command = context.Database.GetDbConnection().CreateCommand();
        command.CommandText = sql;
        RawSqlMapper.BindParameters(command, parameters);
        return command;
    }
}

/// <summary>
/// <see cref="SqlQuery{TEntity}"/> の EF Core 実行器。捕捉された式木を LINQ クエリへ合成し、
/// 短命の <typeparamref name="TContext"/>（AsNoTracking）で実行する。
/// </summary>
/// <remarks>
/// Where は捕捉済みの述語式をそのまま適用し、各方言への翻訳は EF Core プロバイダに委ねる。
/// OrderBy は object? への boxing（Convert）を剥がして実キー型の OrderBy / ThenBy を合成する。
/// Include は <see cref="IncludeNode"/> ツリーから "Orders.Details" 形式のドットパスを組み立てて適用する。
/// 取得結果のグラフは既存 SQL Server 版のマッピングと同じく RowState=Unchanged に揃える。
/// 具象 DbContext には依存せず <typeparamref name="TContext"/>（<see cref="DbContext"/> 派生）で受け取る。
/// </remarks>
/// <typeparam name="TEntity">クエリ対象のエンティティ型</typeparam>
/// <typeparam name="TContext">クエリを実行する DbContext の具象型</typeparam>
public sealed class EfCoreSqlQueryExecutor<TEntity, TContext>(
    IDbContextFactory<TContext> contextFactory
) : ISqlQueryExecutor<TEntity>
    where TEntity : EntityBase
    where TContext : DbContext
{
    /// <summary>DbContext の生成元</summary>
    private readonly IDbContextFactory<TContext> _contextFactory = contextFactory;

    /// <summary>条件に一致するエンティティを（Include 指定分とともに）一覧取得する</summary>
    public async Task<IReadOnlyList<TEntity>> ToListAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var query = ApplyOrderings(
            ApplyIncludes(ApplyPredicates(context.Set<TEntity>().AsNoTracking(), plan), plan),
            plan
        );
        var items = await ApplyPaging(query, plan).ToListAsync(cancellationToken);

        foreach (var item in items)
        {
            MarkGraphUnchanged(item, plan.Includes);
        }

        return items;
    }

    /// <summary>条件に一致するエンティティを射影して取得する（列参照のみ・Include なしのときは EF Core にサーバー側射影させる）</summary>
    /// <remarks>
    /// Include があるか、セレクタから列参照のみを安全に抽出できない場合は、従来経路
    /// （全列取得 → メモリ内で射影）へフォールバックする。刈り込み可能時は、フィルタ・並び順・ページングを
    /// 適用した <see cref="IQueryable{T}"/> に <c>Select(selector)</c> を直適用し、EF Core に列を絞らせる。
    /// </remarks>
    public async Task<IReadOnlyList<TResult>> ToProjectionListAsync<TResult>(
        SqlQueryPlan<TEntity> plan,
        Expression<Func<TEntity, TResult>> selector,
        CancellationToken cancellationToken
    )
    {
        // Include なし・列参照のみのときだけ EF Core の Select 直適用でサーバー側射影する（可否判定は ADO と同じ収集器）
        var prunable =
            plan.Includes.Count == 0
            && ProjectionColumnCollector.TryCollect(selector, out var referenced)
            && EntitySaveMetadata.For(typeof(TEntity)).ResolveProjectionColumns(referenced) is not null;

        if (!prunable)
        {
            // フォールバック: 全列（Include 分含む）を取得してからメモリ内で射影する
            var entities = await ToListAsync(plan, cancellationToken);
            return entities.Select(selector.Compile()).ToList();
        }

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        // Include は無い前提のため適用しない。並び順・ページングを適用してから Select を直適用する
        var query = ApplyPaging(
            ApplyOrderings(ApplyPredicates(context.Set<TEntity>().AsNoTracking(), plan), plan),
            plan
        );

        return await query.Select(selector).ToListAsync(cancellationToken);
    }

    /// <summary>条件に一致する先頭の 1 件を（Include 指定分とともに）取得する（該当なしは null）</summary>
    public async Task<TEntity?> FirstOrDefaultAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var query = ApplyOrderings(
            ApplyIncludes(ApplyPredicates(context.Set<TEntity>().AsNoTracking(), plan), plan),
            plan
        );

        // 既存版と同じく Take は 1 に固定し、Skip のみ尊重する
        if (plan.Skip is int skip)
        {
            query = query.Skip(skip);
        }

        var item = await query.FirstOrDefaultAsync(cancellationToken);

        if (item is not null)
        {
            MarkGraphUnchanged(item, plan.Includes);
        }

        return item;
    }

    /// <summary>条件に一致する件数を取得する（既存版と同じく並び順・ページング・Include は関与しない）</summary>
    public async Task<int> CountAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        return await ApplyPredicates(context.Set<TEntity>().AsNoTracking(), plan)
            .CountAsync(cancellationToken);
    }

    /// <summary>条件に一致するレコードが存在するかを取得する（既存版と同じく並び順・ページング・Include は関与しない）</summary>
    public async Task<bool> AnyAsync(
        SqlQueryPlan<TEntity> plan,
        CancellationToken cancellationToken
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        return await ApplyPredicates(context.Set<TEntity>().AsNoTracking(), plan)
            .AnyAsync(cancellationToken);
    }

    /// <summary>条件に一致する行を一括削除する。cascadeDelete=true で子孫も FK 連鎖で削除する</summary>
    public async Task<int> ExecuteDeleteAsync(
        SqlQueryPlan<TEntity> plan,
        bool cascadeDelete,
        CancellationToken cancellationToken
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        var roots = ApplyPredicates(context.Set<TEntity>(), plan);

        if (!cascadeDelete)
        {
            return await roots.ExecuteDeleteAsync(cancellationToken);
        }

        // カスケード: 子孫 → 本体の順の ExecuteDelete を 1 トランザクションで実行する（既存版の DELETE 文順序と同じ）
        await using var transaction = await context.Database.BeginTransactionAsync(
            cancellationToken
        );
        var rows = await DeleteSubtreeAsync(
            context,
            roots,
            new HashSet<Type> { typeof(TEntity) },
            cancellationToken
        );
        await transaction.CommitAsync(cancellationToken);
        return rows;
    }

    /// <summary>DeleteSubtreeAsync を実行時の子型でジェネリック展開するためのメソッド情報</summary>
    private static readonly MethodInfo _deleteSubtreeMethod = typeof(
        EfCoreSqlQueryExecutor<TEntity, TContext>
    ).GetMethod(nameof(DeleteSubtreeAsync), BindingFlags.NonPublic | BindingFlags.Static)!;

    /// <summary>クエリに一致する行の子孫を末端（孫）から順に削除し、最後に自身を削除する（削除行数を返す）</summary>
    private static async Task<int> DeleteSubtreeAsync<TCurrent>(
        TContext context,
        IQueryable<TCurrent> query,
        ISet<Type> visited,
        CancellationToken cancellationToken
    )
        where TCurrent : class
    {
        var rows = 0;

        foreach (var navigation in EntitySaveMetadata.For(typeof(TCurrent)).CascadeNavigations)
        {
            if (!visited.Add(navigation.ChildType))
            {
                throw new NotSupportedException(
                    $"循環するカスケード（{navigation.ChildType.Name}）は ExecuteDeleteAsync では未対応です。グラフをロードして SaveAsync を使うか、DB の ON DELETE CASCADE を利用してください。"
                );
            }

            // 子クエリ: child => 親クエリの主キー集合.Contains(child.FK)（EF Core が IN サブクエリへ翻訳する）
            var childQuery = BuildChildQuery(context, query, typeof(TCurrent), navigation);
            var subtreeTask = (Task<int>)
                _deleteSubtreeMethod
                    .MakeGenericMethod(navigation.ChildType)
                    .Invoke(null, new object[] { context, childQuery, visited, cancellationToken })!;
            rows += await subtreeTask;

            visited.Remove(navigation.ChildType);
        }

        rows += await query.ExecuteDeleteAsync(cancellationToken);
        return rows;
    }

    /// <summary>DbContext.Set&lt;T&gt;() を実行時型で呼び出すためのメソッド情報</summary>
    private static readonly MethodInfo _setMethod = typeof(DbContext).GetMethod(
        nameof(DbContext.Set),
        Type.EmptyTypes
    )!;

    /// <summary>親クエリの主キー集合を参照する子クエリ（child => parentKeys.Contains(child.FK)）を組み立てる</summary>
    private static IQueryable BuildChildQuery(
        TContext context,
        IQueryable parentQuery,
        Type parentType,
        CascadeNavigation navigation
    )
    {
        var parentKeyProperty = EntitySaveMetadata
            .For(parentType)
            .PropertyByColumn[navigation.PrincipalColumn];
        var childForeignKeyProperty = EntitySaveMetadata
            .For(navigation.ChildType)
            .PropertyByColumn[navigation.DependentColumn];

        // parentKeys = parentQuery.Select(parent => parent.Key)
        var parentParameter = Expression.Parameter(parentType, "parent");
        var keySelector = Expression.Lambda(
            Expression.Property(parentParameter, parentKeyProperty),
            parentParameter
        );
        var parentKeys = parentQuery.Provider.CreateQuery(
            Expression.Call(
                typeof(Queryable),
                nameof(Queryable.Select),
                new[] { parentType, parentKeyProperty.PropertyType },
                parentQuery.Expression,
                Expression.Quote(keySelector)
            )
        );

        // childSet.Where(child => parentKeys.Contains(child.FK))。FK が Nullable の場合はキー型へ変換して比較する
        var childParameter = Expression.Parameter(navigation.ChildType, "child");
        var foreignKeyAccess = (Expression)
            Expression.Property(childParameter, childForeignKeyProperty);

        if (foreignKeyAccess.Type != parentKeyProperty.PropertyType)
        {
            foreignKeyAccess = Expression.Convert(foreignKeyAccess, parentKeyProperty.PropertyType);
        }

        var predicate = Expression.Lambda(
            Expression.Call(
                typeof(Queryable),
                nameof(Queryable.Contains),
                new[] { parentKeyProperty.PropertyType },
                Expression.Constant(
                    parentKeys,
                    typeof(IQueryable<>).MakeGenericType(parentKeyProperty.PropertyType)
                ),
                foreignKeyAccess
            ),
            childParameter
        );
        var childSet = (IQueryable)
            _setMethod.MakeGenericMethod(navigation.ChildType).Invoke(context, null)!;

        return childSet.Provider.CreateQuery(
            Expression.Call(
                typeof(Queryable),
                nameof(Queryable.Where),
                new[] { navigation.ChildType },
                childSet.Expression,
                Expression.Quote(predicate)
            )
        );
    }

    /// <summary>捕捉済みの Where 式を適用する（AND 結合）</summary>
    private static IQueryable<TEntity> ApplyPredicates(
        IQueryable<TEntity> query,
        SqlQueryPlan<TEntity> plan
    )
    {
        foreach (var predicate in plan.Predicates)
        {
            query = query.Where((Expression<Func<TEntity, bool>>)predicate);
        }

        return query;
    }

    /// <summary>捕捉済みの並び順を適用する（boxing を剥がし実キー型で OrderBy / ThenBy を合成する）</summary>
    private static IQueryable<TEntity> ApplyOrderings(
        IQueryable<TEntity> query,
        SqlQueryPlan<TEntity> plan
    )
    {
        var first = true;

        foreach (var ordering in plan.Orderings)
        {
            var body = ordering.KeySelector.Body;

            while (
                body is UnaryExpression
                {
                    NodeType: ExpressionType.Convert or ExpressionType.ConvertChecked
                } unary
            )
            {
                body = unary.Operand;
            }

            var keyLambda = Expression.Lambda(body, ordering.KeySelector.Parameters);
            var methodName = (first, ordering.Descending) switch
            {
                (true, false) => nameof(Queryable.OrderBy),
                (true, true) => nameof(Queryable.OrderByDescending),
                (false, false) => nameof(Queryable.ThenBy),
                (false, true) => nameof(Queryable.ThenByDescending),
            };
            query = query.Provider.CreateQuery<TEntity>(
                Expression.Call(
                    typeof(Queryable),
                    methodName,
                    new[] { typeof(TEntity), body.Type },
                    query.Expression,
                    Expression.Quote(keyLambda)
                )
            );
            first = false;
        }

        return query;
    }

    /// <summary>Include ツリーからドットパス（例: "Orders.Details"）を組み立てて適用する</summary>
    private static IQueryable<TEntity> ApplyIncludes(
        IQueryable<TEntity> query,
        SqlQueryPlan<TEntity> plan
    )
    {
        foreach (var node in plan.Includes)
        {
            foreach (var path in EnumerateIncludePaths(node, node.Property.Name))
            {
                query = query.Include(path);
            }
        }

        return query;
    }

    /// <summary>Include ノードからルート→末端のドットパスを列挙する（子が無いノードはそのパス自身）</summary>
    private static IEnumerable<string> EnumerateIncludePaths(IncludeNode node, string path)
    {
        if (node.Children.Count == 0)
        {
            yield return path;
            yield break;
        }

        foreach (var child in node.Children)
        {
            foreach (var childPath in EnumerateIncludePaths(child, $"{path}.{child.Property.Name}"))
            {
                yield return childPath;
            }
        }
    }

    /// <summary>Skip / Take を適用する（既存版の OFFSET / FETCH と同じ意味）</summary>
    private static IQueryable<TEntity> ApplyPaging(
        IQueryable<TEntity> query,
        SqlQueryPlan<TEntity> plan
    )
    {
        if (plan.Skip is int skip)
        {
            query = query.Skip(skip);
        }

        if (plan.Take is int take)
        {
            query = query.Take(take);
        }

        return query;
    }

    /// <summary>取得したグラフ（ルート＋Include で読んだ範囲）を RowState=Unchanged に揃える（既存版のマッピング後状態と同じ）</summary>
    private static void MarkGraphUnchanged(EntityBase entity, IReadOnlyList<IncludeNode> includes)
    {
        entity.MarkUnchanged();

        foreach (var node in includes)
        {
            var value = node.Property.GetValue(entity);

            if (value is null)
            {
                continue;
            }

            if (value is IEnumerable<EntityBase> children)
            {
                foreach (var child in children)
                {
                    if (child is not null)
                    {
                        MarkGraphUnchanged(child, node.Children);
                    }
                }
            }
            else if (value is EntityBase child)
            {
                MarkGraphUnchanged(child, node.Children);
            }
        }
    }
}

/// <summary>メタデータと EF Core（<typeparamref name="TContext"/>）で CRUD を実装するリポジトリ基底クラス</summary>
/// <remarks>
/// <para>
/// QuickER の SQL Server 実装と同じ契約を DbContext ベースで
/// 実装する。DbContext は呼び出し単位で短命に生成し（呼び出しごとに接続を開く単位と同じ）、
/// 読み取りは AsNoTracking、保存は <c>ChangeTracker.TrackGraph</c> による RowState → EntityState 変換で行う。
/// </para>
/// <para>
/// 具象 DbContext には依存せず <typeparamref name="TContext"/>（<see cref="DbContext"/> 派生）で受け取る。
/// 具象型（QuickErDbContext 等）は生成側（エンティティ別実装・DI 登録）で閉じる。
/// </para>
/// <para>UseSqlServer / UseNpgsql 等の方言選択はアプリ側の DbContextOptions 構成に委ねる（方言非依存）。</para>
/// </remarks>
/// <typeparam name="TEntity">対象エンティティ型</typeparam>
/// <typeparam name="TKey">主キー型</typeparam>
/// <typeparam name="TContext">CRUD を実行する DbContext の具象型</typeparam>
public abstract partial class EfCoreRepository<TEntity, TKey, TContext>(
    IDbContextFactory<TContext> contextFactory,
    ISaveHookRegistry? saveHooks = null
) : IRepository<TEntity, TKey>
    where TEntity : EntityBase, new()
    where TContext : DbContext
{
    /// <summary>エンティティ型ごとに 1 度だけ構築されるメタデータ（静的フィールドで再利用）</summary>
    private static readonly EntitySaveMetadata _metadata = EntitySaveMetadata.For(typeof(TEntity));

    /// <summary>DbContext の生成元</summary>
    private readonly IDbContextFactory<TContext> _contextFactory = contextFactory;

    /// <summary>生 SQL メソッドの委譲先（束縛・マッピングを 1 系統に集約）</summary>
    private readonly ISqlExecutor _sqlExecutor = new EfCoreSqlExecutor<TContext>(contextFactory);

    /// <summary>Save フックのレジストリ（未指定＝null＝フックなしで完全 no-op）</summary>
    private readonly ISaveHookRegistry? _saveHooks = saveHooks;

    /// <summary>TrackGraph で記録した「保存対象エンティティ・EF Core エントリ・実行操作」の 1 件（操作は再試行での切替で更新される）</summary>
    private sealed class TrackedOperation(
        EntityBase entity,
        EntityEntry entry,
        SaveOperation operation
    )
    {
        /// <summary>保存対象エンティティ</summary>
        public EntityBase Entity { get; } = entity;

        /// <summary>対応する EF Core の追跡エントリ（State の落とし込み・再試行での型判定に使う）</summary>
        public EntityEntry Entry { get; } = entry;

        /// <summary>実際に行う操作（<c>insertWhenUpdateMissing</c> の切替時に Update→Insert へ更新される）</summary>
        public SaveOperation Operation { get; set; } = operation;
    }

    /// <summary>主キーによる単一エンティティ取得（該当なしは null）</summary>
    /// <remarks>既存版と同じく単一テーブルのみを読む（ナビゲーションのロードは <see cref="Query"/> の Include で行う）</remarks>
    public async Task<TEntity?> GetByIdAsync(TKey id, CancellationToken cancellationToken = default)
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var entity = await context
            .Set<TEntity>()
            .AsNoTracking()
            .FirstOrDefaultAsync(BuildKeyPredicate(id), cancellationToken);
        // DB から読み込んだ行は変更なし扱いにする（既存版 MapEntity と同じ事後状態）
        entity?.MarkUnchanged();
        return entity;
    }

    /// <summary>全エンティティ取得</summary>
    public async Task<IReadOnlyList<TEntity>> GetAllAsync(
        CancellationToken cancellationToken = default
    )
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var items = await context.Set<TEntity>().AsNoTracking().ToListAsync(cancellationToken);

        foreach (var item in items)
        {
            item.MarkUnchanged();
        }

        return items;
    }

    /// <summary>エンティティ追加</summary>
    public async Task InsertAsync(TEntity entity, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entity);

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        // Add はナビゲーション先まで Added にするため、Entry.State 代入で対象 1 件のみを追加する（既存版の単発 INSERT と同じ範囲）
        context.Entry(entity).State = EntityState.Added;
        await context.SaveChangesAsync(cancellationToken);
    }

    /// <summary>エンティティのコレクションを一括追加する</summary>
    /// <remarks>
    /// EF Core 版は全件を Added で追跡して 1 回の SaveChanges で保存する（バッチ化された INSERT 文）。
    /// SqlBulkCopy を使う既存 SQL Server 版とは性能特性が異なり、大量件数では遅くなる可能性がある。
    /// 挿入範囲は既存版と同じく渡されたエンティティのみで、ナビゲーション先はたどらない。
    /// </remarks>
    public async Task<int> BulkInsertAsync(
        IEnumerable<TEntity> entities,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entities);

        // 件数が確定しているコレクションが空なら DbContext を作らずに終了する
        if (entities is ICollection<TEntity> { Count: 0 })
        {
            return 0;
        }

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        foreach (var entity in entities)
        {
            // AddRange はナビゲーション先まで Added にするため、Entry.State 代入で対象のみを追加する
            context.Entry(entity).State = EntityState.Added;
        }

        return await context.SaveChangesAsync(cancellationToken);
    }

    /// <summary>エンティティ更新（更新対象ありで true）</summary>
    public async Task<bool> UpdateAsync(
        TEntity entity,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entity);

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        context.Entry(entity).State = EntityState.Modified;

        try
        {
            await context.SaveChangesAsync(cancellationToken);
            return true;
        }
        catch (DbUpdateConcurrencyException)
        {
            // 更新対象が存在しない（既存版の「影響 0 行 → false」と同じ契約）
            return false;
        }
    }

    /// <summary>主キーによるエンティティ削除（削除対象ありで true）</summary>
    public async Task<bool> DeleteAsync(TKey id, CancellationToken cancellationToken = default)
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var affected = await context
            .Set<TEntity>()
            .Where(BuildKeyPredicate(id))
            .ExecuteDeleteAsync(cancellationToken);
        return affected > 0;
    }

    /// <summary>検索条件・並び順・Include をチェーン指定して取得するクエリを開始する（EF Core で実行）</summary>
    public SqlQuery<TEntity> Query() =>
        new(new EfCoreSqlQueryExecutor<TEntity, TContext>(_contextFactory));

    /// <summary>RowState に従って 1 トランザクションで追加・更新・削除を保存する（既定で子をカスケード）</summary>
    public async Task<int> SaveAsync(
        TEntity entity,
        bool cascadeSave = true,
        bool cascadeDelete = true,
        bool insertWhenUpdateMissing = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entity);

        // グラフ全体に変更が無ければ DbContext も作らずに終了する
        if (!EntityGraphSaver.HasChanges(entity, cascadeSave))
        {
            return 0;
        }

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var tracked = new List<TrackedOperation>();
        TrackGraph(context, entity, cascadeSave, cascadeDelete, tracked);

        return await SaveTrackedGraphAsync(
            context,
            [entity],
            tracked,
            cascadeSave,
            insertWhenUpdateMissing,
            cancellationToken
        );
    }

    /// <summary>複数の集約ルートを 1 トランザクションでまとめて保存する（全件成功か全件ロールバックの原子的処理）</summary>
    public async Task<int> SaveAsync(
        IEnumerable<TEntity> entities,
        bool cascadeSave = true,
        bool cascadeDelete = true,
        bool insertWhenUpdateMissing = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(entities);

        // 変更のあるグラフだけを対象にする（DbContext を作る前に絞り込む）
        var targets = entities
            .Where(entity => entity is not null && EntityGraphSaver.HasChanges(entity, cascadeSave))
            .ToList();

        if (targets.Count == 0)
        {
            return 0;
        }

        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);

        var tracked = new List<TrackedOperation>();

        foreach (var entity in targets)
        {
            TrackGraph(context, entity, cascadeSave, cascadeDelete, tracked);
        }

        return await SaveTrackedGraphAsync(
            context,
            targets,
            tracked,
            cascadeSave,
            insertWhenUpdateMissing,
            cancellationToken
        );
    }

    /// <summary>
    /// 追跡済みグラフを保存する。記録された型のどれかに Save フックの登録があるときだけフック経路（明示トランザクション内で
    /// Before → SaveChanges → After → Commit）に入り、1 つも無ければ<b>完全に既存経路</b>（明示トランザクションを張らず
    /// SaveChanges を 1 回実行する＝意味的に従来と同一）で処理する。
    /// </summary>
    private async Task<int> SaveTrackedGraphAsync(
        TContext context,
        IReadOnlyList<TEntity> roots,
        List<TrackedOperation> tracked,
        bool cascadeSave,
        bool insertWhenUpdateMissing,
        CancellationToken cancellationToken
    )
    {
        // 記録された型のどれかにフック登録があるときだけフック経路に入る（1 つも無ければ既存経路）
        var hasHooks =
            _saveHooks is not null
            && tracked.Any(op => _saveHooks.GetInvoker(op.Entity.GetType()) is not null);

        if (!hasHooks)
        {
            // 既存経路: 明示トランザクションなしで SaveChanges（内部で 1 トランザクションとして実行される）
            var rowsWithoutHooks = await SaveTrackedChangesAsync(
                context,
                tracked,
                insertWhenUpdateMissing,
                cancellationToken
            );

            foreach (var root in roots)
            {
                EntityGraphSaver.AcceptChanges(root, cascadeSave);
            }

            return rowsWithoutHooks;
        }

        // フック経路: After に保存中 context（＋その CurrentTransaction）を閉じ込めた context を供給するセッション
        var hooks = new SaveHookSession(_saveHooks!, _ => new EfCoreSaveHookContext(context));

        // Before パス（SaveChanges 前）: 記録順に発火し、false は Entry を Unchanged に落として保存対象から除く
        var survivors = new List<TrackedOperation>(tracked.Count);

        foreach (var op in tracked)
        {
            if (await hooks.InvokeBeforeAsync(op.Entity, op.Operation, cancellationToken))
            {
                survivors.Add(op);
            }
            else
            {
                op.Entry.State = EntityState.Unchanged;
                hooks.Skip(op.Entity);
            }
        }

        // After を「操作後・コミット前」に発火するため、SaveChanges を明示トランザクション内で行う
        await using var transaction = await context.Database.BeginTransactionAsync(cancellationToken);

        var rows = await SaveTrackedChangesAsync(
            context,
            survivors,
            insertWhenUpdateMissing,
            cancellationToken
        );

        // After パス（コミット前）: 記録順に、実際に行った操作（切替時は Insert）で発火する
        foreach (var op in survivors)
        {
            await hooks.InvokeAfterAsync(op.Entity, op.Operation, cancellationToken);
        }

        await transaction.CommitAsync(cancellationToken);

        // 保存成功後に状態を確定（Added/Updated → Unchanged）し、スキップされた行は据え置く
        foreach (var root in roots)
        {
            EntityGraphSaver.AcceptChanges(root, cascadeSave, hooks.Skipped);
        }

        return rows;
    }

    /// <summary>生 SQL の SELECT を実行し、結果行を {TEntity} へマップして返す</summary>
    /// <remarks>
    /// マッピング・束縛の意味論は既存 SQL Server 版と同一（全列必須・RowState=Unchanged）。
    /// 実装は <see cref="ISqlExecutor"/>（EF Core 版）へ委譲する（束縛・マッピングの 1 系統化）。
    /// </remarks>
    public Task<IReadOnlyList<TEntity>> QueryBySqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.QueryBySqlAsync<TEntity>(sql, parameters, cancellationToken);

    /// <summary>生 SQL（UPDATE/DELETE/任意 DML）を実行し、影響行数を返す</summary>
    /// <remarks>
    /// 呼び出しごとに DbContext（接続）を開閉する。複数文をアトミックに実行したい場合は、
    /// 1 回の呼び出し内に方言のトランザクション文を記述すること。実装は <see cref="ISqlExecutor"/>（EF Core 版）へ委譲する。
    /// </remarks>
    public Task<int> ExecuteSqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.ExecuteSqlAsync(sql, parameters, cancellationToken);

    /// <summary>生 SQL を実行し、単一のスカラー値を返す（該当なし・DBNull は <c>default</c>）</summary>
    /// <remarks>変換・束縛の意味論は既存 SQL Server 版と同一。実装は <see cref="ISqlExecutor"/>（EF Core 版）へ委譲する。</remarks>
    public Task<TResult?> ExecuteScalarSqlAsync<TResult>(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    ) => _sqlExecutor.ExecuteScalarSqlAsync<TResult>(sql, parameters, cancellationToken);

    /// <summary>主キー等値の述語式（e => e.Key == id）をメタデータから組み立てる</summary>
    private static Expression<Func<TEntity, bool>> BuildKeyPredicate(TKey id)
    {
        var parameter = Expression.Parameter(typeof(TEntity), "e");
        var body = Expression.Equal(
            Expression.Property(parameter, _metadata.KeyProperty),
            Expression.Constant(id, _metadata.KeyProperty.PropertyType)
        );
        return Expression.Lambda<Func<TEntity, bool>>(body, parameter);
    }

    /// <summary>RowState → EntityState の変換でグラフを DbContext へ登録し、保存対象（非 Unchanged）を <paramref name="tracked"/> へ記録する（切断パターンの保存前処理）</summary>
    /// <remarks>記録順はグラフの走査順（ルート→子）で、Save フックの Before/After はこの順で発火する。Deleted サブツリーの子も削除グループとして記録する。</remarks>
    private static void TrackGraph(
        TContext context,
        TEntity entity,
        bool cascadeSave,
        bool cascadeDelete,
        List<TrackedOperation> tracked
    )
    {
        if (!cascadeSave)
        {
            // 子をたどらず、ルート 1 件のみを保存対象にする
            var entry = context.Entry(entity);
            entry.State = ToEntityState(entity.RowState);
            RecordOperation(tracked, entity, entry);
            return;
        }

        context.ChangeTracker.TrackGraph(
            entity,
            node =>
            {
                var current = (EntityBase)node.Entry.Entity;

                // 親が削除対象なら配下の扱いは cascadeDelete に従う（既存版の子孫先行 DELETE と同じ）
                if (node.SourceEntry is { State: EntityState.Deleted })
                {
                    // cascadeDelete=false なら配下は対象外（Detached のままにすると配下の走査も止まる）。
                    // Added（DB 未挿入）の子は削除対象が存在しないため対象外（既存版の DELETE 影響 0 行と同じ結果）
                    if (cascadeDelete && !current.IsAdded)
                    {
                        node.Entry.State = EntityState.Deleted;
                        RecordOperation(tracked, current, node.Entry);
                    }

                    return;
                }

                // Unchanged も追跡させ（EntityState.Unchanged）、配下の変更ノードまで走査を継続する
                node.Entry.State = ToEntityState(current.RowState);
                RecordOperation(tracked, current, node.Entry);
            }
        );
    }

    /// <summary>EntityState が保存対象（Added/Modified/Deleted）ならフック発火用の記録を追加する（Unchanged は無視）</summary>
    private static void RecordOperation(
        List<TrackedOperation> tracked,
        EntityBase entity,
        EntityEntry entry
    )
    {
        var operation = entry.State switch
        {
            EntityState.Added => (SaveOperation?)SaveOperation.Insert,
            EntityState.Modified => SaveOperation.Update,
            EntityState.Deleted => SaveOperation.Delete,
            _ => null,
        };

        if (operation is { } value)
        {
            tracked.Add(new TrackedOperation(entity, entry, value));
        }
    }

    /// <summary>RowState を EF Core の EntityState へ変換する</summary>
    private static EntityState ToEntityState(RowState rowState) =>
        rowState switch
        {
            RowState.Added => EntityState.Added,
            RowState.Updated => EntityState.Modified,
            RowState.Removed => EntityState.Deleted,
            _ => EntityState.Unchanged,
        };

    /// <summary>
    /// SaveChanges を実行し、<see cref="DbUpdateConcurrencyException"/> を既存契約へ変換する
    /// （insertWhenUpdateMissing=true なら更新対象なしの UPDATE を INSERT へ切り替えて再試行、
    /// それ以外は <see cref="SaveConflictException"/>）。
    /// </summary>
    private static async Task<int> SaveTrackedChangesAsync(
        TContext context,
        IReadOnlyList<TrackedOperation> tracked,
        bool insertWhenUpdateMissing,
        CancellationToken cancellationToken
    )
    {
        while (true)
        {
            try
            {
                return await context.SaveChangesAsync(cancellationToken);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                // 更新対象が存在しない（他ユーザーの削除等）。方針に応じて INSERT へ切替、または競合として通知する
                if (
                    insertWhenUpdateMissing
                    && ex.Entries.Count > 0
                    && ex.Entries.All(entry => entry.State == EntityState.Modified)
                )
                {
                    foreach (var entry in ex.Entries)
                    {
                        entry.State = EntityState.Added;

                        // 再試行で INSERT へ切り替えたノードは、After 発火時の操作も Insert に更新する（Before は Update で発火済み）
                        foreach (var op in tracked)
                        {
                            if (ReferenceEquals(op.Entry.Entity, entry.Entity))
                            {
                                op.Operation = SaveOperation.Insert;
                            }
                        }
                    }

                    continue;
                }

                var conflict = ex.Entries.Count > 0 ? ex.Entries[0].Entity : null;
                var description =
                    conflict is null
                        ? "対象不明"
                        : $"{conflict.GetType().Name}、キー {EntitySaveMetadata.For(conflict.GetType()).KeyProperty.GetValue(conflict)}";
                throw new SaveConflictException(
                    $"更新対象のレコードが見つかりませんでした（{description}）。他のユーザーに削除または変更された可能性があります。"
                );
            }
        }
    }
}

/// <summary>Save フックの After に渡す、保存中の DbContext（＋その CurrentTransaction）に参加する EF Core コンテキスト</summary>
/// <remarks>
/// <para>
/// 生 SQL（<see cref="ExecuteSqlAsync"/>）は保存中 context の接続と現在のトランザクションで実行する
/// （EfCoreSqlExecutor と同じ束縛ヘルパー <see cref="RawSqlMapper.BindParameters"/> を流用する）。別接続・別トランザクションは張らない。
/// </para>
/// <para>
/// 除外列バイナリの書き込み（<see cref="WriteBinaryColumnAsync"/>）は、EF Core が方言固有のストリーミングを持てないため
/// <see cref="NotSupportedException"/> を投げる（Stream アクセサの EF Core 方針と同じ）。同一トランザクションで列を更新したい場合は
/// <see cref="ExecuteSqlAsync"/> を使うか、QuickER 版 Repository を利用する。
/// </para>
/// </remarks>
public sealed class EfCoreSaveHookContext(DbContext context) : ISaveHookContext
{
    private readonly DbContext _context = context;

    /// <summary>保存中トランザクション内で生 SQL（任意 DML）を実行し、影響行数を返す（束縛は RawSqlMapper と 1 系統）</summary>
    public async Task<int> ExecuteSqlAsync(
        string sql,
        object? parameters = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(sql);

        // 接続は保存中の DbContext が所有しており、既にトランザクションで開いている
        var connection = _context.Database.GetDbConnection();

        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        // 進行中の保存トランザクションに参加する（別接続・別トランザクションを張らない）
        command.Transaction = _context.Database.CurrentTransaction?.GetDbTransaction();
        RawSqlMapper.BindParameters(command, parameters);
        return await command.ExecuteNonQueryAsync(cancellationToken);
    }

    /// <summary>EF Core モードでは除外列バイナリの書き込みは非対応（Stream アクセサと同方針＝生 SQL か QuickER 版 Repository を使う）</summary>
    public Task<bool> WriteBinaryColumnAsync(
        string propertyName,
        object key,
        Stream? source,
        long? length = null,
        CancellationToken cancellationToken = default
    ) =>
        throw new NotSupportedException(
            "EF Core モードでは Save フックの除外列バイナリ書き込み（WriteBinaryColumnAsync）は使用できません。"
                + "生 SQL（ExecuteSqlAsync）で更新するか、QuickER 版 Repository を使ってください。"
        );
}
