//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.Db.UI.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.Db.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }

        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }

        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }

        public static string Common_Complete {
            get {
                return ResourceManager.GetString("Common_Complete", resourceCulture);
            }
        }

        public static string Toolbar_ImportFromDb {
            get {
                return ResourceManager.GetString("Toolbar_ImportFromDb", resourceCulture);
            }
        }

        public static string Toolbar_ImportFromDbTooltip {
            get {
                return ResourceManager.GetString("Toolbar_ImportFromDbTooltip", resourceCulture);
            }
        }

        public static string Toolbar_SyncToDb {
            get {
                return ResourceManager.GetString("Toolbar_SyncToDb", resourceCulture);
            }
        }

        public static string DbConnection_Title {
            get {
                return ResourceManager.GetString("DbConnection_Title", resourceCulture);
            }
        }

        public static string DbConnection_SavedConnections {
            get {
                return ResourceManager.GetString("DbConnection_SavedConnections", resourceCulture);
            }
        }

        public static string DbConnection_DeleteProfile {
            get {
                return ResourceManager.GetString("DbConnection_DeleteProfile", resourceCulture);
            }
        }

        public static string DbConnection_DeleteProfileTooltip {
            get {
                return ResourceManager.GetString("DbConnection_DeleteProfileTooltip", resourceCulture);
            }
        }

        public static string DbConnection_ProfileName {
            get {
                return ResourceManager.GetString("DbConnection_ProfileName", resourceCulture);
            }
        }

        public static string DbConnection_SaveProfile {
            get {
                return ResourceManager.GetString("DbConnection_SaveProfile", resourceCulture);
            }
        }

        public static string DbConnection_SaveProfileTooltip {
            get {
                return ResourceManager.GetString("DbConnection_SaveProfileTooltip", resourceCulture);
            }
        }

        public static string DbConnection_TargetDb {
            get {
                return ResourceManager.GetString("DbConnection_TargetDb", resourceCulture);
            }
        }

        public static string DbConnection_FilePath {
            get {
                return ResourceManager.GetString("DbConnection_FilePath", resourceCulture);
            }
        }

        public static string DbConnection_Browse {
            get {
                return ResourceManager.GetString("DbConnection_Browse", resourceCulture);
            }
        }

        public static string DbConnection_BrowseTooltip {
            get {
                return ResourceManager.GetString("DbConnection_BrowseTooltip", resourceCulture);
            }
        }

        public static string DbConnection_CreateNewFile {
            get {
                return ResourceManager.GetString("DbConnection_CreateNewFile", resourceCulture);
            }
        }

        public static string DbConnection_CreateNewFileTooltip {
            get {
                return ResourceManager.GetString("DbConnection_CreateNewFileTooltip", resourceCulture);
            }
        }

        public static string DbConnection_CreateFileFailed {
            get {
                return ResourceManager.GetString("DbConnection_CreateFileFailed", resourceCulture);
            }
        }

        public static string DbConnection_Host {
            get {
                return ResourceManager.GetString("DbConnection_Host", resourceCulture);
            }
        }

        public static string DbConnection_Port {
            get {
                return ResourceManager.GetString("DbConnection_Port", resourceCulture);
            }
        }

        public static string DbConnection_PortTooltip {
            get {
                return ResourceManager.GetString("DbConnection_PortTooltip", resourceCulture);
            }
        }

        public static string DbConnection_Database {
            get {
                return ResourceManager.GetString("DbConnection_Database", resourceCulture);
            }
        }

        public static string DbConnection_AuthMethod {
            get {
                return ResourceManager.GetString("DbConnection_AuthMethod", resourceCulture);
            }
        }

        public static string DbConnection_UserName {
            get {
                return ResourceManager.GetString("DbConnection_UserName", resourceCulture);
            }
        }

        public static string DbConnection_Password {
            get {
                return ResourceManager.GetString("DbConnection_Password", resourceCulture);
            }
        }

        public static string DbConnection_SavePassword {
            get {
                return ResourceManager.GetString("DbConnection_SavePassword", resourceCulture);
            }
        }

        public static string DbConnection_SavePasswordTooltip {
            get {
                return ResourceManager.GetString("DbConnection_SavePasswordTooltip", resourceCulture);
            }
        }

        public static string DbConnection_TrustServerCertificate {
            get {
                return ResourceManager.GetString("DbConnection_TrustServerCertificate", resourceCulture);
            }
        }

        public static string DbConnection_TestConnection {
            get {
                return ResourceManager.GetString("DbConnection_TestConnection", resourceCulture);
            }
        }

        public static string DbConnection_Restored {
            get {
                return ResourceManager.GetString("DbConnection_Restored", resourceCulture);
            }
        }

        public static string DbConnection_ProfileDialectMismatch {
            get {
                return ResourceManager.GetString("DbConnection_ProfileDialectMismatch", resourceCulture);
            }
        }

        public static string DbConnection_ProfileLoaded {
            get {
                return ResourceManager.GetString("DbConnection_ProfileLoaded", resourceCulture);
            }
        }

        public static string DbConnection_Connecting {
            get {
                return ResourceManager.GetString("DbConnection_Connecting", resourceCulture);
            }
        }

        public static string DbConnection_ConnectSucceeded {
            get {
                return ResourceManager.GetString("DbConnection_ConnectSucceeded", resourceCulture);
            }
        }

        public static string DbConnection_ConnectFailed {
            get {
                return ResourceManager.GetString("DbConnection_ConnectFailed", resourceCulture);
            }
        }

        public static string DbConnection_ProfileNameRequired {
            get {
                return ResourceManager.GetString("DbConnection_ProfileNameRequired", resourceCulture);
            }
        }

        public static string DbConnection_ProfileSaved {
            get {
                return ResourceManager.GetString("DbConnection_ProfileSaved", resourceCulture);
            }
        }

        public static string DbConnection_SelectProfileToDelete {
            get {
                return ResourceManager.GetString("DbConnection_SelectProfileToDelete", resourceCulture);
            }
        }

        public static string DbConnection_DeleteProfileConfirm {
            get {
                return ResourceManager.GetString("DbConnection_DeleteProfileConfirm", resourceCulture);
            }
        }

        public static string DbConnection_ProfileDeleted {
            get {
                return ResourceManager.GetString("DbConnection_ProfileDeleted", resourceCulture);
            }
        }

        public static string DbConnection_SqliteFileFilter {
            get {
                return ResourceManager.GetString("DbConnection_SqliteFileFilter", resourceCulture);
            }
        }

        public static string DbConnection_FilePathRequired {
            get {
                return ResourceManager.GetString("DbConnection_FilePathRequired", resourceCulture);
            }
        }

        public static string DbConnection_FileNotFound {
            get {
                return ResourceManager.GetString("DbConnection_FileNotFound", resourceCulture);
            }
        }

        public static string DbConnection_HostAndDatabaseRequired {
            get {
                return ResourceManager.GetString("DbConnection_HostAndDatabaseRequired", resourceCulture);
            }
        }

        public static string SchemaSync_Title {
            get {
                return ResourceManager.GetString("SchemaSync_Title", resourceCulture);
            }
        }

        public static string SchemaSync_Recalculate {
            get {
                return ResourceManager.GetString("SchemaSync_Recalculate", resourceCulture);
            }
        }

        public static string SchemaSync_SelectAll {
            get {
                return ResourceManager.GetString("SchemaSync_SelectAll", resourceCulture);
            }
        }

        public static string SchemaSync_DeselectAll {
            get {
                return ResourceManager.GetString("SchemaSync_DeselectAll", resourceCulture);
            }
        }

        public static string SchemaSync_Execute {
            get {
                return ResourceManager.GetString("SchemaSync_Execute", resourceCulture);
            }
        }

        public static string SchemaSync_DiffList {
            get {
                return ResourceManager.GetString("SchemaSync_DiffList", resourceCulture);
            }
        }

        public static string SchemaSync_SqlPreview {
            get {
                return ResourceManager.GetString("SchemaSync_SqlPreview", resourceCulture);
            }
        }

        public static string SchemaSync_Fetching {
            get {
                return ResourceManager.GetString("SchemaSync_Fetching", resourceCulture);
            }
        }

        public static string SchemaSync_ColumnOrderNotSynced {
            get {
                return ResourceManager.GetString("SchemaSync_ColumnOrderNotSynced", resourceCulture);
            }
        }

        public static string SchemaSync_DiffCount {
            get {
                return ResourceManager.GetString("SchemaSync_DiffCount", resourceCulture);
            }
        }

        public static string SchemaSync_NoDiff {
            get {
                return ResourceManager.GetString("SchemaSync_NoDiff", resourceCulture);
            }
        }

        public static string SchemaSync_DiffFailed {
            get {
                return ResourceManager.GetString("SchemaSync_DiffFailed", resourceCulture);
            }
        }

        public static string SchemaSync_NoScript {
            get {
                return ResourceManager.GetString("SchemaSync_NoScript", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteConfirmDestructive {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteConfirmDestructive", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteConfirm {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteConfirm", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteConfirmRebuild {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteConfirmRebuild", resourceCulture);
            }
        }

        public static string SchemaSync_Executing {
            get {
                return ResourceManager.GetString("SchemaSync_Executing", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteSucceeded {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteSucceeded", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteFailedStatus {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteFailedStatus", resourceCulture);
            }
        }

        public static string SchemaSync_RollbackMessage {
            get {
                return ResourceManager.GetString("SchemaSync_RollbackMessage", resourceCulture);
            }
        }

        public static string SchemaSync_ExecuteError {
            get {
                return ResourceManager.GetString("SchemaSync_ExecuteError", resourceCulture);
            }
        }

        public static string Db_ImportTitle {
            get {
                return ResourceManager.GetString("Db_ImportTitle", resourceCulture);
            }
        }

        public static string Db_ImportReplaceConfirm {
            get {
                return ResourceManager.GetString("Db_ImportReplaceConfirm", resourceCulture);
            }
        }

        public static string Db_ImportFailed {
            get {
                return ResourceManager.GetString("Db_ImportFailed", resourceCulture);
            }
        }

        public static string Db_SyncWriteBack {
            get {
                return ResourceManager.GetString("Db_SyncWriteBack", resourceCulture);
            }
        }

        public static string Db_SyncTitle {
            get {
                return ResourceManager.GetString("Db_SyncTitle", resourceCulture);
            }
        }
    }
}
