//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.AI.Chat.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.AI.Chat.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Chat_WindowTitle {
            get {
                return ResourceManager.GetString("Chat_WindowTitle", resourceCulture);
            }
        }

        public static string Chat_TabApiKey {
            get {
                return ResourceManager.GetString("Chat_TabApiKey", resourceCulture);
            }
        }

        public static string Chat_Provider {
            get {
                return ResourceManager.GetString("Chat_Provider", resourceCulture);
            }
        }

        public static string Chat_ModelName {
            get {
                return ResourceManager.GetString("Chat_ModelName", resourceCulture);
            }
        }

        public static string Chat_ApiKey {
            get {
                return ResourceManager.GetString("Chat_ApiKey", resourceCulture);
            }
        }

        public static string Chat_ApiKeyTooltip {
            get {
                return ResourceManager.GetString("Chat_ApiKeyTooltip", resourceCulture);
            }
        }

        public static string Chat_Save {
            get {
                return ResourceManager.GetString("Chat_Save", resourceCulture);
            }
        }

        public static string Chat_Endpoint {
            get {
                return ResourceManager.GetString("Chat_Endpoint", resourceCulture);
            }
        }

        public static string Chat_EndpointTooltip {
            get {
                return ResourceManager.GetString("Chat_EndpointTooltip", resourceCulture);
            }
        }

        public static string Chat_TabCodex {
            get {
                return ResourceManager.GetString("Chat_TabCodex", resourceCulture);
            }
        }

        public static string Chat_CodexLoginGuidance {
            get {
                return ResourceManager.GetString("Chat_CodexLoginGuidance", resourceCulture);
            }
        }

        public static string Chat_CodexLoginButton {
            get {
                return ResourceManager.GetString("Chat_CodexLoginButton", resourceCulture);
            }
        }

        public static string Chat_Logout {
            get {
                return ResourceManager.GetString("Chat_Logout", resourceCulture);
            }
        }

        public static string Chat_TabClaude {
            get {
                return ResourceManager.GetString("Chat_TabClaude", resourceCulture);
            }
        }

        public static string Chat_Model {
            get {
                return ResourceManager.GetString("Chat_Model", resourceCulture);
            }
        }

        public static string Chat_ChatHeader {
            get {
                return ResourceManager.GetString("Chat_ChatHeader", resourceCulture);
            }
        }

        public static string Chat_Responding {
            get {
                return ResourceManager.GetString("Chat_Responding", resourceCulture);
            }
        }

        public static string Chat_Interrupt {
            get {
                return ResourceManager.GetString("Chat_Interrupt", resourceCulture);
            }
        }

        public static string Chat_NewConversation {
            get {
                return ResourceManager.GetString("Chat_NewConversation", resourceCulture);
            }
        }

        public static string Chat_ToolCallHeader {
            get {
                return ResourceManager.GetString("Chat_ToolCallHeader", resourceCulture);
            }
        }

        public static string Chat_InputTooltip {
            get {
                return ResourceManager.GetString("Chat_InputTooltip", resourceCulture);
            }
        }

        public static string Chat_Send {
            get {
                return ResourceManager.GetString("Chat_Send", resourceCulture);
            }
        }

        public static string Chat_CodexNotConnected {
            get {
                return ResourceManager.GetString("Chat_CodexNotConnected", resourceCulture);
            }
        }

        public static string Chat_ConversationStarted {
            get {
                return ResourceManager.GetString("Chat_ConversationStarted", resourceCulture);
            }
        }

        public static string Chat_SwitchBackendConfirm {
            get {
                return ResourceManager.GetString("Chat_SwitchBackendConfirm", resourceCulture);
            }
        }

        public static string Chat_SwitchBackendConfirmTitle {
            get {
                return ResourceManager.GetString("Chat_SwitchBackendConfirmTitle", resourceCulture);
            }
        }

        public static string Chat_SendFailedFormat {
            get {
                return ResourceManager.GetString("Chat_SendFailedFormat", resourceCulture);
            }
        }

        public static string Chat_BrowserOpenFailedFormat {
            get {
                return ResourceManager.GetString("Chat_BrowserOpenFailedFormat", resourceCulture);
            }
        }

        public static string Chat_ResponseCompleted {
            get {
                return ResourceManager.GetString("Chat_ResponseCompleted", resourceCulture);
            }
        }

        public static string Chat_ErrorSystemFormat {
            get {
                return ResourceManager.GetString("Chat_ErrorSystemFormat", resourceCulture);
            }
        }

        public static string Chat_ErrorStatusFormat {
            get {
                return ResourceManager.GetString("Chat_ErrorStatusFormat", resourceCulture);
            }
        }

        public static string Chat_Interrupted {
            get {
                return ResourceManager.GetString("Chat_Interrupted", resourceCulture);
            }
        }

        public static string Chat_ToolsUnavailable {
            get {
                return ResourceManager.GetString("Chat_ToolsUnavailable", resourceCulture);
            }
        }

        public static string Chat_RemoveModelFromHistory {
            get {
                return ResourceManager.GetString("Chat_RemoveModelFromHistory", resourceCulture);
            }
        }

        public static string Toolbar_OpenAiChat {
            get {
                return ResourceManager.GetString("Toolbar_OpenAiChat", resourceCulture);
            }
        }

        public static string Toolbar_OpenAiChatTooltip {
            get {
                return ResourceManager.GetString("Toolbar_OpenAiChatTooltip", resourceCulture);
            }
        }
        public static string ErDesign_CommonDesignPrinciples {
            get {
                return ResourceManager.GetString("ErDesign_CommonDesignPrinciples", resourceCulture);
            }
        }

        public static string ErDesign_SinglePrimaryKeyRule {
            get {
                return ResourceManager.GetString("ErDesign_SinglePrimaryKeyRule", resourceCulture);
            }
        }

        public static string ErDesign_SingleColumnForeignKeyRule {
            get {
                return ResourceManager.GetString("ErDesign_SingleColumnForeignKeyRule", resourceCulture);
            }
        }

        public static string ErDesign_FunctionToolLabel {
            get {
                return ResourceManager.GetString("ErDesign_FunctionToolLabel", resourceCulture);
            }
        }

        public static string ErDesign_ChatInstructionsTemplate {
            get {
                return ResourceManager.GetString("ErDesign_ChatInstructionsTemplate", resourceCulture);
            }
        }

        public static string ErDesign_NamingSnakeCase {
            get {
                return ResourceManager.GetString("ErDesign_NamingSnakeCase", resourceCulture);
            }
        }

        public static string ErDesign_NamingPascalCase {
            get {
                return ResourceManager.GetString("ErDesign_NamingPascalCase", resourceCulture);
            }
        }

        public static string ErDesign_TableNamePlural {
            get {
                return ResourceManager.GetString("ErDesign_TableNamePlural", resourceCulture);
            }
        }

        public static string ErDesign_TableNameSingular {
            get {
                return ResourceManager.GetString("ErDesign_TableNameSingular", resourceCulture);
            }
        }

        public static string QueryTool_SetSuccessUpdated {
            get {
                return ResourceManager.GetString("QueryTool_SetSuccessUpdated", resourceCulture);
            }
        }

        public static string QueryTool_SetSuccessAdded {
            get {
                return ResourceManager.GetString("QueryTool_SetSuccessAdded", resourceCulture);
            }
        }

        public static string QueryTool_Warning {
            get {
                return ResourceManager.GetString("QueryTool_Warning", resourceCulture);
            }
        }

        public static string QueryTool_SetValidationFailed {
            get {
                return ResourceManager.GetString("QueryTool_SetValidationFailed", resourceCulture);
            }
        }

        public static string QueryTool_RemoveSuccess {
            get {
                return ResourceManager.GetString("QueryTool_RemoveSuccess", resourceCulture);
            }
        }

        public static string QueryTool_QueryNotFound {
            get {
                return ResourceManager.GetString("QueryTool_QueryNotFound", resourceCulture);
            }
        }

        public static string QueryTool_ListHeader {
            get {
                return ResourceManager.GetString("QueryTool_ListHeader", resourceCulture);
            }
        }

        public static string QueryTool_UnknownEntity {
            get {
                return ResourceManager.GetString("QueryTool_UnknownEntity", resourceCulture);
            }
        }

        public static string QueryTool_MissingArgument {
            get {
                return ResourceManager.GetString("QueryTool_MissingArgument", resourceCulture);
            }
        }

        public static string QueryTool_InvalidReturns {
            get {
                return ResourceManager.GetString("QueryTool_InvalidReturns", resourceCulture);
            }
        }

        public static string QueryTool_InvalidImplementation {
            get {
                return ResourceManager.GetString("QueryTool_InvalidImplementation", resourceCulture);
            }
        }

        public static string QueryTool_TableNotFound {
            get {
                return ResourceManager.GetString("QueryTool_TableNotFound", resourceCulture);
            }
        }

        public static string QueryTool_UnexpectedStatus {
            get {
                return ResourceManager.GetString("QueryTool_UnexpectedStatus", resourceCulture);
            }
        }

        public static string QueryTool_ListDescription {
            get {
                return ResourceManager.GetString("QueryTool_ListDescription", resourceCulture);
            }
        }

        public static string QueryTool_ListScalarType {
            get {
                return ResourceManager.GetString("QueryTool_ListScalarType", resourceCulture);
            }
        }

        public static string QueryTool_ListCondition {
            get {
                return ResourceManager.GetString("QueryTool_ListCondition", resourceCulture);
            }
        }

        public static string QueryTool_ListSqlDialects {
            get {
                return ResourceManager.GetString("QueryTool_ListSqlDialects", resourceCulture);
            }
        }

        public static string QueryTool_ListParameters {
            get {
                return ResourceManager.GetString("QueryTool_ListParameters", resourceCulture);
            }
        }

        public static string QueryTool_ListOrderBy {
            get {
                return ResourceManager.GetString("QueryTool_ListOrderBy", resourceCulture);
            }
        }

        public static string QueryTool_ListPaging {
            get {
                return ResourceManager.GetString("QueryTool_ListPaging", resourceCulture);
            }
        }

        public static string QueryTool_ListResultType {
            get {
                return ResourceManager.GetString("QueryTool_ListResultType", resourceCulture);
            }
        }

        public static string QueryTool_ListFields {
            get {
                return ResourceManager.GetString("QueryTool_ListFields", resourceCulture);
            }
        }

        public static string QueryTool_ColumnRef {
            get {
                return ResourceManager.GetString("QueryTool_ColumnRef", resourceCulture);
            }
        }

        public static string QueryTool_Untyped {
            get {
                return ResourceManager.GetString("QueryTool_Untyped", resourceCulture);
            }
        }

        public static string QueryTool_ListSuffix {
            get {
                return ResourceManager.GetString("QueryTool_ListSuffix", resourceCulture);
            }
        }

        public static string QueryTool_Unknown {
            get {
                return ResourceManager.GetString("QueryTool_Unknown", resourceCulture);
            }
        }

        public static string QueryTool_OrderDesc {
            get {
                return ResourceManager.GetString("QueryTool_OrderDesc", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ParameterMissingName {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ParameterMissingName", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ParameterTypeSourceExclusive {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ParameterTypeSourceExclusive", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ParameterSourceColumnNotFound {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ParameterSourceColumnNotFound", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ScalarRequiresScalarType {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ScalarRequiresScalarType", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ProjectionRequiresResultTypeName {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ProjectionRequiresResultTypeName", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ProjectionRequiresFields {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ProjectionRequiresFields", resourceCulture);
            }
        }

        public static string QueryTool_Diag_OrderByInvalidForReturnShape {
            get {
                return ResourceManager.GetString("QueryTool_Diag_OrderByInvalidForReturnShape", resourceCulture);
            }
        }

        public static string QueryTool_Diag_OrderByMissingColumn {
            get {
                return ResourceManager.GetString("QueryTool_Diag_OrderByMissingColumn", resourceCulture);
            }
        }

        public static string QueryTool_Diag_OrderByColumnNotFound {
            get {
                return ResourceManager.GetString("QueryTool_Diag_OrderByColumnNotFound", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ProjectionFieldMissingName {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ProjectionFieldMissingName", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ProjectionFieldTypeSourceExclusive {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ProjectionFieldTypeSourceExclusive", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ProjectionFieldSourceColumnNotFound {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ProjectionFieldSourceColumnNotFound", resourceCulture);
            }
        }

        public static string QueryTool_Diag_UnknownSqlDialect {
            get {
                return ResourceManager.GetString("QueryTool_Diag_UnknownSqlDialect", resourceCulture);
            }
        }

        public static string QueryTool_Diag_SqlDialectNotString {
            get {
                return ResourceManager.GetString("QueryTool_Diag_SqlDialectNotString", resourceCulture);
            }
        }

        public static string QueryTool_Diag_Condition {
            get {
                return ResourceManager.GetString("QueryTool_Diag_Condition", resourceCulture);
            }
        }

        public static string QueryTool_Diag_RawSql {
            get {
                return ResourceManager.GetString("QueryTool_Diag_RawSql", resourceCulture);
            }
        }

        public static string QueryTool_Diag_ParameterUnusedInCondition {
            get {
                return ResourceManager.GetString("QueryTool_Diag_ParameterUnusedInCondition", resourceCulture);
            }
        }

        public static string QueryTool_Diag_Unexpected {
            get {
                return ResourceManager.GetString("QueryTool_Diag_Unexpected", resourceCulture);
            }
        }

        public static string QueryTool_InvalidArgumentsJson {
            get {
                return ResourceManager.GetString("QueryTool_InvalidArgumentsJson", resourceCulture);
            }
        }

    }
}
