//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.Provider.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.Provider.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Diff_AddTable {
            get {
                return ResourceManager.GetString("Diff_AddTable", resourceCulture);
            }
        }

        public static string Diff_SetTableDescription {
            get {
                return ResourceManager.GetString("Diff_SetTableDescription", resourceCulture);
            }
        }

        public static string Diff_SetColumnDescription {
            get {
                return ResourceManager.GetString("Diff_SetColumnDescription", resourceCulture);
            }
        }

        public static string Diff_RemoveTableDescription {
            get {
                return ResourceManager.GetString("Diff_RemoveTableDescription", resourceCulture);
            }
        }

        public static string Diff_UpdateTableDescription {
            get {
                return ResourceManager.GetString("Diff_UpdateTableDescription", resourceCulture);
            }
        }

        public static string Diff_AddColumn {
            get {
                return ResourceManager.GetString("Diff_AddColumn", resourceCulture);
            }
        }

        public static string Diff_TypeChange {
            get {
                return ResourceManager.GetString("Diff_TypeChange", resourceCulture);
            }
        }

        public static string Diff_NullableChange {
            get {
                return ResourceManager.GetString("Diff_NullableChange", resourceCulture);
            }
        }

        public static string Diff_Nullable_Allow {
            get {
                return ResourceManager.GetString("Diff_Nullable_Allow", resourceCulture);
            }
        }

        public static string Diff_Nullable_Deny {
            get {
                return ResourceManager.GetString("Diff_Nullable_Deny", resourceCulture);
            }
        }

        public static string Diff_ColumnChangePrefix {
            get {
                return ResourceManager.GetString("Diff_ColumnChangePrefix", resourceCulture);
            }
        }

        public static string Diff_RemoveColumnDescription {
            get {
                return ResourceManager.GetString("Diff_RemoveColumnDescription", resourceCulture);
            }
        }

        public static string Diff_UpdateColumnDescription {
            get {
                return ResourceManager.GetString("Diff_UpdateColumnDescription", resourceCulture);
            }
        }

        public static string Diff_DropColumn {
            get {
                return ResourceManager.GetString("Diff_DropColumn", resourceCulture);
            }
        }

        public static string Diff_DropTable {
            get {
                return ResourceManager.GetString("Diff_DropTable", resourceCulture);
            }
        }

        public static string Diff_AddForeignKey {
            get {
                return ResourceManager.GetString("Diff_AddForeignKey", resourceCulture);
            }
        }

        public static string Diff_AddForeignKeyNoColumn {
            get {
                return ResourceManager.GetString("Diff_AddForeignKeyNoColumn", resourceCulture);
            }
        }

        public static string Diff_DropForeignKey {
            get {
                return ResourceManager.GetString("Diff_DropForeignKey", resourceCulture);
            }
        }

        public static string Diff_AddUniqueConstraint {
            get {
                return ResourceManager.GetString("Diff_AddUniqueConstraint", resourceCulture);
            }
        }

        public static string Diff_DropUniqueConstraint {
            get {
                return ResourceManager.GetString("Diff_DropUniqueConstraint", resourceCulture);
            }
        }

        public static string Diff_ReorderColumns {
            get {
                return ResourceManager.GetString("Diff_ReorderColumns", resourceCulture);
            }
        }

        public static string Diff_AlterPrimaryKey {
            get {
                return ResourceManager.GetString("Diff_AlterPrimaryKey", resourceCulture);
            }
        }

        public static string Diff_PrimaryKey_None {
            get {
                return ResourceManager.GetString("Diff_PrimaryKey_None", resourceCulture);
            }
        }

        public static string Diff_AutoForeignKeyRebuild {
            get {
                return ResourceManager.GetString("Diff_AutoForeignKeyRebuild", resourceCulture);
            }
        }

        public static string Diff_AutoUniqueConstraintRebuild {
            get {
                return ResourceManager.GetString("Diff_AutoUniqueConstraintRebuild", resourceCulture);
            }
        }

        public static string Provider_UnsupportedProvider {
            get {
                return ResourceManager.GetString("Provider_UnsupportedProvider", resourceCulture);
            }
        }

        public static string Sync_Error_MySqlStatementFailed {
            get {
                return ResourceManager.GetString("Sync_Error_MySqlStatementFailed", resourceCulture);
            }
        }

        public static string Sync_Error_OracleStatementFailed {
            get {
                return ResourceManager.GetString("Sync_Error_OracleStatementFailed", resourceCulture);
            }
        }

        public static string Sync_Error_SqliteForeignKeyViolation {
            get {
                return ResourceManager.GetString("Sync_Error_SqliteForeignKeyViolation", resourceCulture);
            }
        }

        public static string Sync_Error_RolledBack {
            get {
                return ResourceManager.GetString("Sync_Error_RolledBack", resourceCulture);
            }
        }
    }
}
