//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// ResourceManager.GetString は string? を返すため、Null 許容注釈を無効化して
// 生成プロパティ（string 返却）のコンパイル警告を避ける。
#nullable disable

namespace QuickER.CodeReverse.CSharp.Resources {
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickER.CodeReverse.CSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Reverse_NoTargetClasses {
            get {
                return ResourceManager.GetString("Reverse_NoTargetClasses", resourceCulture);
            }
        }

        public static string Reverse_SyntaxErrors {
            get {
                return ResourceManager.GetString("Reverse_SyntaxErrors", resourceCulture);
            }
        }

        public static string Reverse_SyntaxErrorDetail {
            get {
                return ResourceManager.GetString("Reverse_SyntaxErrorDetail", resourceCulture);
            }
        }

        public static string Reverse_ColumnMissingTypeMeta {
            get {
                return ResourceManager.GetString("Reverse_ColumnMissingTypeMeta", resourceCulture);
            }
        }

        public static string Reverse_TypeTokenUnresolved {
            get {
                return ResourceManager.GetString("Reverse_TypeTokenUnresolved", resourceCulture);
            }
        }

        public static string Reverse_UniqueConstraintMemberUnresolved {
            get {
                return ResourceManager.GetString("Reverse_UniqueConstraintMemberUnresolved", resourceCulture);
            }
        }

        public static string Reverse_UniqueConstraintEmpty {
            get {
                return ResourceManager.GetString("Reverse_UniqueConstraintEmpty", resourceCulture);
            }
        }

        public static string Reverse_ReferentialActionUnknown {
            get {
                return ResourceManager.GetString("Reverse_ReferentialActionUnknown", resourceCulture);
            }
        }
    }
}
