using AwesomeAssertions;
using QuickER.Model;
using QuickER.Sqlite;

namespace QuickER.Tests.Sqlite;

/// <summary>
/// <see cref="SqliteDdlGenerator"/> の DDL 生成（インライン PK / FK / UNIQUE・コメント・識別子クォート）を検証するテストクラス
/// </summary>
public class SqliteDdlGeneratorTests
{
    /// <summary>ヘッダコメントが他方言と同一文言で出力されることを検証する</summary>
    [Fact(DisplayName = "Build: ヘッダコメントが共通文言で出力される")]
    public void Build_EmitsCommonHeader()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "t",
                    Columns =
                    {
                        new Column { Name = "id", DataType = "INT" },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().StartWith("-- DDL auto-generated by QuickER");
    }

    /// <summary>
    /// 単一整数 PK でも宣言型を verbatim に維持し、AUTOINCREMENT を出力しないことを検証する
    /// （モデルに自動採番の概念がなく他方言も IDENTITY 等を出力しない。アプリ側採番前提）
    /// </summary>
    [Fact(DisplayName = "Build: 単一整数 PK は宣言型を維持し AUTOINCREMENT を出力しない")]
    public void Build_SingleIntegerPk_KeepsDeclaredTypeWithoutAutoIncrement()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "users",
                    Columns =
                    {
                        new Column
                        {
                            Name = "id",
                            DataType = "INT",
                            IsPrimaryKey = true,
                            IsNullable = false,
                        },
                        new Column
                        {
                            Name = "name",
                            DataType = "NVARCHAR(50)",
                            IsNullable = true,
                        },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().Contain("CREATE TABLE \"users\"");
        // 宣言型 INT を INTEGER 等へ書き換えない（往復無損失の要）
        sql.Should().Contain("\"id\" INT NOT NULL");
        sql.Should().Contain("\"name\" NVARCHAR(50) NULL");
        sql.Should().NotContain("AUTOINCREMENT");
        // PK は末尾のインライン PRIMARY KEY 制約として出力する
        sql.Should().Contain("CONSTRAINT \"PK_users\" PRIMARY KEY (\"id\")");
    }

    /// <summary>複合主キーは末尾のインライン PRIMARY KEY 制約へまとめて出力されることを検証する</summary>
    [Fact(DisplayName = "Build: 複合 PK は末尾のインライン PRIMARY KEY を生成する")]
    public void Build_CompositePrimaryKey_EmitsInlineConstraint()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "order_items",
                    Columns =
                    {
                        new Column
                        {
                            Name = "order_id",
                            DataType = "INT",
                            IsPrimaryKey = true,
                        },
                        new Column
                        {
                            Name = "line_no",
                            DataType = "INT",
                            IsPrimaryKey = true,
                        },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().NotContain("AUTOINCREMENT");
        sql.Should()
            .Contain("CONSTRAINT \"PK_order_items\" PRIMARY KEY (\"order_id\", \"line_no\")");
    }

    /// <summary>非整数の単一 PK もインライン PRIMARY KEY 制約になることを検証する</summary>
    [Fact(DisplayName = "Build: 非整数の単一 PK はインライン PRIMARY KEY 制約になる")]
    public void Build_NonIntegerSinglePk_UsesInlineConstraint()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "docs",
                    Columns =
                    {
                        new Column
                        {
                            Name = "code",
                            DataType = "NVARCHAR(20)",
                            IsPrimaryKey = true,
                        },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().NotContain("AUTOINCREMENT");
        sql.Should().Contain("CONSTRAINT \"PK_docs\" PRIMARY KEY (\"code\")");
    }

    /// <summary>1 対多リレーションからインライン FK 制約と参照アクションが生成されることを検証する</summary>
    [Fact(
        DisplayName = "Build: 1対多リレーションがインライン FOREIGN KEY と参照アクションを生成する"
    )]
    public void Build_OneToMany_EmitsInlineForeignKeyWithActions()
    {
        var parent = new Entity
        {
            TableName = "parent",
            Columns =
            {
                new Column
                {
                    Name = "id",
                    DataType = "INT",
                    IsPrimaryKey = true,
                },
            },
        };
        var child = new Entity
        {
            TableName = "child",
            Columns =
            {
                new Column
                {
                    Name = "id",
                    DataType = "INT",
                    IsPrimaryKey = true,
                },
                new Column { Name = "parent_id", DataType = "INT" },
            },
        };
        var diagram = new ErDiagram
        {
            Entities = [parent, child],
            Relationships =
            [
                new Relationship
                {
                    SourceEntityId = parent.Id,
                    TargetEntityId = child.Id,
                    Type = RelationshipType.OneToMany,
                    ColumnPairs = [new(parent.Columns[0].Id, child.Columns[1].Id)],
                    ConstraintName = "FK_child_parent",
                    OnDelete = ForeignKeyReferentialAction.Cascade,
                    OnUpdate = ForeignKeyReferentialAction.SetNull,
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        // FK は子テーブルの CREATE TABLE 内にインラインで出る（ALTER TABLE は使わない）
        sql.Should().NotContain("ALTER TABLE");
        sql.Should().Contain("CONSTRAINT \"FK_child_parent\"");
        sql.Should().Contain("FOREIGN KEY (\"parent_id\") REFERENCES \"parent\" (\"id\")");
        sql.Should().Contain("ON DELETE CASCADE");
        sql.Should().Contain("ON UPDATE SET NULL");
    }

    /// <summary>テーブル・カラムの説明が SQL コメント（--）として出力されることを検証する</summary>
    [Fact(DisplayName = "Build: テーブル・カラムの説明が -- コメントで出力される")]
    public void Build_Descriptions_EmittedAsSqlComments()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "products",
                    Description = "商品マスタ",
                    Columns =
                    {
                        new Column
                        {
                            Name = "id",
                            DataType = "INT",
                            IsPrimaryKey = true,
                            Description = "商品ID",
                        },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().Contain("-- products: 商品マスタ");
        sql.Should().Contain("-- id: 商品ID");
    }

    /// <summary>多対多リレーションはコメント行のみ出力されることを検証する</summary>
    [Fact(DisplayName = "Build: 多対多はジャンクションテーブルのコメントを出力する")]
    public void Build_ManyToMany_EmitsComment()
    {
        var a = new Entity
        {
            TableName = "a",
            Columns =
            {
                new Column
                {
                    Name = "id",
                    DataType = "INT",
                    IsPrimaryKey = true,
                },
            },
        };
        var b = new Entity
        {
            TableName = "b",
            Columns =
            {
                new Column
                {
                    Name = "id",
                    DataType = "INT",
                    IsPrimaryKey = true,
                },
            },
        };
        var diagram = new ErDiagram
        {
            Entities = [a, b],
            Relationships =
            [
                new Relationship
                {
                    SourceEntityId = a.Id,
                    TargetEntityId = b.Id,
                    Type = RelationshipType.ManyToMany,
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().Contain("-- Many-to-many (a <-> b): define a junction table separately.");
    }

    /// <summary>日本語・二重引用符を含む識別子がクォート・エスケープされることを検証する</summary>
    [Fact(DisplayName = "Build: 識別子が二重引用符でクォート・エスケープされる")]
    public void Build_Identifiers_AreQuotedAndEscaped()
    {
        var diagram = new ErDiagram
        {
            Entities =
            [
                new Entity
                {
                    TableName = "顧客",
                    Columns =
                    {
                        new Column
                        {
                            Name = "co\"l",
                            DataType = "NVARCHAR(10)",
                            IsPrimaryKey = true,
                        },
                    },
                },
            ],
        };

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().Contain("CREATE TABLE \"顧客\"");
        sql.Should().Contain("\"co\"\"l\"");
    }

    /// <summary>一意制約を持つエンティティの図を組み立てる</summary>
    /// <param name="withPrimaryKey">主キー列を含めるかどうか（PK 行との区切りカンマ検証用）</param>
    private static (ErDiagram Diagram, Entity Entity) BuildUniqueDiagram(bool withPrimaryKey = true)
    {
        var entity = new Entity { TableName = "shops" };

        if (withPrimaryKey)
        {
            entity.Columns.Add(
                new Column
                {
                    Name = "id",
                    DataType = "INT",
                    IsPrimaryKey = true,
                    IsNullable = false,
                }
            );
        }

        entity.Columns.Add(
            new Column
            {
                Name = "code",
                DataType = "NVARCHAR(20)",
                IsNullable = false,
            }
        );
        entity.Columns.Add(
            new Column
            {
                Name = "region",
                DataType = "NVARCHAR(10)",
                IsNullable = false,
            }
        );

        return (new ErDiagram { Entities = { entity } }, entity);
    }

    /// <summary>名前付き単一列の一意制約が PK 制約行の直後へ出力されることを検証する</summary>
    [Fact(DisplayName = "Build: 名前付き単一列 UNIQUE が PK の直後に出力される")]
    public void Build_NamedSingleColumnUnique_EmitsConstraint()
    {
        var (diagram, entity) = BuildUniqueDiagram();
        entity.UniqueConstraints.Add(
            new UniqueConstraint { Name = "UQ_shops_code", ColumnIds = [entity.Columns[1].Id] }
        );

        var sql = new SqliteDdlGenerator().Build(diagram);

        // PK 行には後続制約があるため区切りカンマが付く
        sql.Should().Contain("CONSTRAINT \"PK_shops\" PRIMARY KEY (\"id\"),");
        sql.Should().Contain("CONSTRAINT \"UQ_shops_code\" UNIQUE (\"code\")");
        // 最後の制約行に余分なカンマは付かない
        sql.Should().NotContain("UNIQUE (\"code\"),");
    }

    /// <summary>制約名なしの複合一意制約が合成名・宣言順で出力されることを検証する</summary>
    [Fact(DisplayName = "Build: 名前なし複合 UNIQUE は UQ_テーブル_列… の合成名になる")]
    public void Build_UnnamedCompositeUnique_SynthesizesName()
    {
        var (diagram, entity) = BuildUniqueDiagram();
        // 宣言順は region → code（列定義順とは逆）
        entity.UniqueConstraints.Add(
            new UniqueConstraint { ColumnIds = [entity.Columns[2].Id, entity.Columns[1].Id] }
        );

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().Contain("CONSTRAINT \"UQ_shops_region_code\" UNIQUE (\"region\", \"code\")");
    }

    /// <summary>PK が無くても列定義の末尾カンマが一意制約行の有無で正しく付くことを検証する</summary>
    [Fact(DisplayName = "Build: PK なしでも UNIQUE 行の前の列にカンマが付く")]
    public void Build_WithoutPrimaryKey_KeepsCommaBeforeUnique()
    {
        var (diagram, entity) = BuildUniqueDiagram(withPrimaryKey: false);
        entity.UniqueConstraints.Add(new UniqueConstraint { ColumnIds = [entity.Columns[0].Id] });

        var sql = new SqliteDdlGenerator().Build(diagram);

        sql.Should().NotContain("PRIMARY KEY");
        sql.Should().Contain("\"region\" NVARCHAR(10) NOT NULL,");
        sql.Should().Contain("CONSTRAINT \"UQ_shops_code\" UNIQUE (\"code\")");
    }

    /// <summary>制約行が PK → UNIQUE → FK の順に並ぶことを検証する</summary>
    [Fact(DisplayName = "Build: 制約行は PK → UNIQUE → FK の順に並ぶ")]
    public void Build_ConstraintOrder_IsPkThenUniqueThenForeignKey()
    {
        var ownerId = new Column
        {
            Name = "id",
            DataType = "INT",
            IsPrimaryKey = true,
            IsNullable = false,
        };
        var owner = new Entity { TableName = "owners", Columns = { ownerId } };

        var (diagram, shop) = BuildUniqueDiagram();
        var ownerRef = new Column
        {
            Name = "owner_id",
            DataType = "INT",
            IsNullable = false,
        };
        shop.Columns.Add(ownerRef);
        shop.UniqueConstraints.Add(
            new UniqueConstraint { Name = "UQ_shops_code", ColumnIds = [shop.Columns[1].Id] }
        );

        diagram.Entities.Add(owner);
        diagram.Relationships.Add(
            new Relationship
            {
                SourceEntityId = owner.Id,
                TargetEntityId = shop.Id,
                Type = RelationshipType.OneToMany,
                ColumnPairs = [new(ownerId.Id, ownerRef.Id)],
                ConstraintName = "FK_shops_owners",
            }
        );

        var sql = new SqliteDdlGenerator().Build(diagram);

        var pkIndex = sql.IndexOf("CONSTRAINT \"PK_shops\"", StringComparison.Ordinal);
        var uqIndex = sql.IndexOf("CONSTRAINT \"UQ_shops_code\"", StringComparison.Ordinal);
        var fkIndex = sql.IndexOf("CONSTRAINT \"FK_shops_owners\"", StringComparison.Ordinal);

        pkIndex.Should().BeGreaterThan(-1);
        uqIndex.Should().BeGreaterThan(pkIndex);
        fkIndex.Should().BeGreaterThan(uqIndex);
        // 中間の制約行には区切りカンマが付き、最後の FK 行には付かない
        sql.Should().Contain("CONSTRAINT \"UQ_shops_code\" UNIQUE (\"code\"),");
    }

    /// <summary>一意制約を持たない図では UNIQUE 行を 1 行も出力しないことを検証する（既存出力のバイト不変）</summary>
    [Fact(DisplayName = "Build: 一意制約が無ければ UNIQUE を出力しない")]
    public void Build_WithoutUniqueConstraints_EmitsNoUnique()
    {
        var (diagram, _) = BuildUniqueDiagram();

        new SqliteDdlGenerator().Build(diagram).Should().NotContain("UNIQUE");
    }
}
